### PR TITLE
🌐 Add Urdu translation for `docs/ur/docs/benchmarks.md`

### PR DESCRIPTION
**Pull request by AhsanSheraz**
Urdu translation of benchmark documentation

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 02349819bad9e0b428771ab1eb7bf854a0d3f5f5 at: https://64c7c2f77c57f0074f23c55f--fastapi.netlify.app

**Comment by tiangolo** [comment]
📝 Docs preview for commit 7ca0697f89ab37d3bfe79f3e4d4efdeaf79e6c70 at: https://64c7cf633fb0c50e8ea44821--fastapi.netlify.app

**Comment by AhsanSheraz** [comment]
@tiangolo can you please add labels here as well? Thanks

**Comment by talhaumer** [comment]
Looks good

**Review by talhaumer — APPROVED** [review]
Looks good approved

**Review by sulemanhelp — APPROVED** [review]

**Comment by tiangolo** [comment]
Great, thanks @AhsanSheraz! 🚀 

And thanks for the reviews @sulemanhelp and @talhaumer 🙇

**Pull request merged**
