### PR TITLE
🌐 Add German translation for `docs/de/docs/reference/request.md`

### PR DESCRIPTION
**Pull request by nilslindemann**
← `reference/background.md` (#10820)
→ `reference/websockets.md` (#10822)

[German translation progress](https://github.com/tiangolo/fastapi/discussions/10582)

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 8a605ebee04666a444a18d08207901942ae916b0 at: https://b64670aa.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit b20011652be35e8aa33742d7a484b709a1620706 at: https://96bbeea2.fastapitiangolo.pages.dev

**Review by dpinezich — APPROVED** [review]
Quercheck noch gemacht das es an mehreren Orten "Pfadoperation" heisst, well done 👍

**Comment by alejsdev** [comment]
Thanks! @nilslindemann 🚀✨ 

And thanks for the review @dpinezich 🤓

**Comment by nilslindemann** [comment]
Super!

**Pull request merged**
