### PR TITLE
🌐 Fix Korean translation for `docs/ko/docs/tutorial/security/first-steps.md`

### PR DESCRIPTION
**Pull request by DevDae**
* Fix Korean translation for `docs/ko/docs/tutorial/security/first-steps.md`
* Related [FEATURE] Korean translations #2017

If we check 파이썬 한국어 번역 and search the word, "application", it is translated as 응용 프로그램, so we follow the rules of that guide (check of it on #2017 ).

The word "exotic" means "이국적인" in literal translation, but in this sentence, i think "익숙하지 않은" can represent that's meaning more properly.

### CODE REVIEW

**Comment by DevDae** [comment]
I'm waiting for any reviews! 😄 
Please check my work and share your idea 🚀

**Review by kty4119 — APPROVED** [review]

**Comment by joonas-yoon** [comment]
Hi, this is too late comment.

I supposed that title should be "translation for `tutorial/first-steps`", not for security.

file changes look good :)

**Comment by tiangolo** [comment]
📝 Docs preview for commit aca444fa0159a150b331bd0a775cd113c527243a at: https://649a12812199541006357e65--fastapi.netlify.app

**Comment by tiangolo** [comment]
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

**Pull request closed without merging**
