### PR TITLE
docs: semver MINOR releases do not contain breaking changes

### PR DESCRIPTION
**Pull request by pcharlan**
I'm assuming this was a typo.  Of course feel free to close if the wording is as intended.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit c6f00009f753b4ed60177fcdaf725772539fc5cd at: https://64a759281a13030a31e99ea4--fastapi.netlify.app

**Comment by tiangolo** [comment]
📝 Docs preview for commit 2fb3cf9199d5e6a4a0aaaa39017a1ac0607a6b4e at: https://64a8a45636a1f1205dddd896--fastapi.netlify.app

**Comment by Kludex** [comment]
It's not a typo: https://0ver.org/

**Comment by pcharlan** [comment]
> It's not a typo: https://0ver.org/

I see, the semver major version being `0` allows there to be breaking changes with minor version updates.  Thanks for helping me understand this.  Sorry for the noise; I'll close this PR.

**Pull request closed without merging**
