### PR TITLE
Change .dict() to .model_dump()

### PR DESCRIPTION
**Pull request by sulavmhrzn**
Use .model_dump() method because .dict() method is deprecated

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 1274a5c51646265fd915bbcaec1adc95278b3285 at: https://923d3cfb.fastapitiangolo.pages.dev

**Review by iudeen — APPROVED** [review]

**Comment by nilslindemann** [comment]
For the records (#10052, #10811), a "search in files" in VS Code for `.dict(` in `./` of the master branch of the repo gives 103 results in 37 files.

**Review by hasansezertasan — APPROVED** [review]
LGTM

**Review by nilslindemann — CHANGES_REQUESTED** [review]
@sulavmhrzn The PR title "Change .dict() to .model_dump()" (unlike #10811) implies that you are willing to do this for the whole repo, which would be nice :-)

**Review by yezz123 — APPROVED** [review]

**Review by alejsdev — APPROVED** [review]

**Comment by tiangolo** [comment]
📝 Docs preview for commit 97debd45219e73e53ca59b278d29cea6952ff0d1 at: https://7d7943a9.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
Thanks @sulavmhrzn! ☕ 

And thanks for the help here @nilslindemann and everyone! 🙇 

The problem is that FastAPI is still compatible with Pydantic v1, and the examples are currently compatible with both Pydantic v1 and v2, updating them to use `.model_dump()` makes them no longer compatible with Pydantic v1.

To alleviate the problem a bit, I added notes to the docs suggesting people to use `.model_dump()`, while keeping the examples compatible with Pydantic v1 here: https://github.com/tiangolo/fastapi/pull/10929

Given that, I'll pass on this, but thanks for the effort! 🍰

**Pull request closed without merging**
