### PR TITLE
Update docs.py to hide default DB schema

### PR DESCRIPTION
**Pull request by akihiro-inui**
As `docs/` endpoint adds DB schemas as default, I added a flag to hide it.

### CODE REVIEW

**Comment by Mause** [comment]
This looks like a less configurable version of https://github.com/tiangolo/fastapi/pull/2568

**Comment by akihiro-inui** [comment]
> This looks like a less configurable version of #2568

Yes, please close this when #2558 is merged.

**Comment by RayBB** [comment]
@akihiro-inui I think since #2568 is merged and released you can probably close this ticket!

**Comment by tiangolo** [comment]
As this was covered by that other PR, I'm gonna close this one. Thanks! ☕

**Pull request closed without merging**
