### PR TITLE
📝 Add location info to `tutorial/bigger-applications.md`

### PR DESCRIPTION
**Pull request by nilslindemann**
This will help the reader when reading [Bigger Applications](https://fastapi.tiangolo.com/tutorial/bigger-applications/), which is about structuring a FastAPI app in multiple modules. So it uses code examples for multiple modules.

This PR adds a comment on top of each module, denoting the location of the current module (commit 1). The code highlights in the documentation are updated accordingly (commit 2).

#10554 is a translation of this.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 5f58aab64fd10bcaef3c9571e42419ba1ee0e9b1 at: https://0c00ab7a.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
Good idea! 🤓 

I would prefer to do it outside the file, in the code block title: https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-a-title

**Comment by nilslindemann** [comment]
Good Idea, I will do that.

**Comment by tiangolo** [comment]
📝 Docs preview for commit 666885c711f9860941ac64dec460be54e9b14e77 at: https://d6855de5.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 44fcd3b66b606cddfdf88f5bd82d362281aaed01 at: https://b3bcaaa7.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit b23067db731b52699ac60f1d76c420574db13099 at: https://3fa4a649.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 3703989cd82d6c1c513d262e8a26a8614a21358b at: https://cc942a9c.fastapitiangolo.pages.dev

**Review by alejsdev — APPROVED** [review]

**Comment by tiangolo** [comment]
Amazing, thank you! 🚀 🙇

**Pull request merged**
