### PR TITLE
🌐 Add Spanish translation for `docs/es/docs/help-fastapi.md`

### PR DESCRIPTION
**Pull request by pablocm83**
- Version >= 0.108.0

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 9b6de176e164f3bdbc29627e776e585eea9c710b at: https://f3cfc394.fastapitiangolo.pages.dev

**Review by LaurEars — COMMENTED** [review]
Looking good!

- Algunas correcciones 😅
- Funciona localmente (✅ URLs y  ✅ hover)

**Comment by tiangolo** [comment]
📝 Docs preview for commit 870bcb2371c65f308e29a2cc17f14db8c04d7ea8 at: https://4f56a111.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit ed02b7fc5d073ae490bbcfe6a238bd2b4de96da5 at: https://519da2a7.fastapitiangolo.pages.dev

**Review by LaurEars — APPROVED** [review]
✅ Docs preview good

¡Gracias!

**Comment by tiangolo** [comment]
📝 Docs preview for commit ae18099e5089c49856a1b130d8d22ab84ad6abe1 at: https://aaf098c8.fastapitiangolo.pages.dev

**Review by jeison-araya — APPROVED** [review]

**Comment by tiangolo** [comment]
This was covered in another PR, so I'll close this one now, thanks for the effort! :cake: :coffee:

**Pull request closed without merging**
