### PR TITLE
🌐 Add Vietnamese translation for `docs/vi/docs/features.md` and `docs/vi/docs/index.md`

### PR DESCRIPTION
**Pull request by magiskboy**

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 43343a39711f63767f9c2df9dfb59076f8acf9cf at: https://6485b02e09e5ab0857779339--fastapi.netlify.app

**Comment by tiangolo** [comment]
📝 Docs preview for commit 5464352ba59612ce019096fc83f8ee24fe6d592d at: https://6485b2a1aab7f404c566163a--fastapi.netlify.app

**Comment by tiangolo** [comment]
📝 Docs preview for commit 39dbc628782149e87fd642f2329fc4ab9e5b031d at: https://6485d5976038ce1a744f62f6--fastapi.netlify.app

**Comment by tiangolo** [comment]
📝 Docs preview for commit 5024084e86694426e4b4803c844c82fca95412cf at: https://648683e0ad38cc78b71d3ca7--fastapi.netlify.app

**Comment by tiangolo** [comment]
📝 Docs preview for commit 3372c2ec92bc56d0bdf7f78640f5944feea97f62 at: https://64868f95ce3df7085688fc19--fastapi.netlify.app

**Comment by tiangolo** [comment]
📝 Docs preview for commit 9f6d6be3191948ce5f0f119472a0ce4a42c07526 at: https://648ae4e911066302f84f3ef4--fastapi.netlify.app

**Comment by magiskboy** [comment]
@tiangolo what do you need to do on this pr?

**Comment by tiangolo** [comment]
Nice! 🚀 

To take it I would need to PR approvals from native speakers. If you have colleagues that would like to contribute, that would be best. You can read more about it in the docs: https://fastapi.tiangolo.com/contributing/#translations

**Comment by tiangolo** [comment]
📝 Docs preview for commit 11843cd15941d6c98c9d0545a9498fa4df2af6a2 at: https://649a30e2ec68df215ae6b31b--fastapi.netlify.app

**Comment by tiangolo** [comment]
I just added a GitHub Discussion to coordinate the Vietnamese translations here: https://github.com/tiangolo/fastapi/discussions/9752

**Review by phamquanganh31101998 — APPROVED** [review]

**Review by vuamitom — APPROVED** [review]
The translation looks good to me

**Comment by tiangolo** [comment]
Thank you @magiskboy! 🚀 

And thanks for the reviews @phamquanganh31101998 and @vuamitom! 🙇 

There are now Vietnamese translations for the FastAPI docs thanks to you! 🎉

**Pull request merged**
