### PR TITLE
🌐 Fix Korean translation for `docs/ko/docs/tutorial/response-status-code.md`

### PR DESCRIPTION
**Pull request by nayeonkinn**
I corrected minor Markdown syntax errors and removed bold formatting as per the original text.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 9ea61ae7c8debd44c42f5dcc3d847afcebfa926b at: https://58062c73.fastapitiangolo.pages.dev

**Review by hard-coders — CHANGES_REQUESTED** [review]
LGTM, but there's one more thing.
Could you replace "당신" with "여러분" in the following text? See the [discussion](https://github.com/tiangolo/fastapi/discussions/3167#discussioncomment-721448)

https://github.com/tiangolo/fastapi/blob/9ea61ae7c8debd44c42f5dcc3d847afcebfa926b/docs/ko/docs/tutorial/response-status-code.md?plain=1#L85

**Comment by tiangolo** [comment]
📝 Docs preview for commit d07724cf629eb067a8a61e88cf98cdeccda50806 at: https://4f2499d9.fastapitiangolo.pages.dev

**Comment by nayeonkinn** [comment]
@hard-coders Hi! I made the changes as you suggested. Thank you for letting me know.

**Review by hard-coders — APPROVED** [review]
LGTM 👍🏻

**Review by jujumilk3 — APPROVED** [review]
LTGM 😃

**Comment by alejsdev** [comment]
Thanks for the help! @nayeonkinn @hard-coders @jujumilk3 :nerd_face: :100:

**Pull request merged**
