### PR TITLE
🌐 Remove translation docs references to aiofiles as it's no longer needed since AnyIO

### LINKED ISSUE #3589: Raising exceptions with registered exception handlers from BackgroundTasks causes starlette exception
### First check

* [V ] I added a very descriptive title to this issue.
* [ V] I used the GitHub search to find a similar issue and didn't find it.
* [ V] I searched the FastAPI documentation, with the integrated search.
* [ V] I already searched in Google "How to X in FastAPI" and didn't find any information.
* [ V] I already read and followed all the tutorial in the docs and didn't find an answer.
* [ V] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
* [ V] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
* [ V] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Example

```Python
from fastapi import BackgroundTasks, FastAPI, status
from starlette.requests import Request
from starlette.responses import JSONResponse


class MyException(Exception):
    ...

app = FastAPI()


@app.exception_handler(MyException)
async def sampler_exception_handler(request: Request, exc: MyException):
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content={"error": "i hope someone sees this"},
    )


def write_notification(email: str, message=""):
    raise MyException("this is my exception")
    with open("log.txt", mode="w") as email_file:
        content = f"notification for {email}: {message}"
        email_file.write(content)


@app.post("/send-notification/{email}")
async def send_notification(email: str, background_tasks: BackgroundTasks):
    background_tasks.add_task(write_notification, email, message="some notification")
    return {"message": "Notification sent in the background"}

```

### Description

Raising an exception that an exception_handler is registered for, from a background task - causes an error from starlette, which also hides the original exception.

running the code from the example, and triggering the endpoint,  i expected the error to be either handled by the exception handler, or maybe just ignoring the exception handler as this exception does not happen as part of a request context.

the actual behavior is as follows

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/alonmenczer/.pyenv/versions/3.7.9/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/alonmenczer/.pyenv/versions/3.7.9/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in __call__
    return await self.app(scope, receive, send)
  File "/Users/alonmenczer/.pyenv/versions/3.7.9/lib/python3.7/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/alonmenczer/.pyenv/versions/3.7.9/lib/python3.7/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/alonmenczer/.pyenv/versions/3.7.9/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/alonmenczer/.pyenv/versions/3.7.9/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/alonmenczer/.pyenv/versions/3.7.9/lib/python3.7/site-packages/starlette/exceptions.py", line 86, in __call__
    raise RuntimeError(msg) from exc
RuntimeError: Caught handled exception, but response already started.
```

I understand this might be connected to a starlette design decision from previous discussions, but haven't actually seen this exact cause for the problem.

### Environment

* OS: macOS
* FastAPI Version: 0.67.0
* Python version: Python 3.7.9

### PR DESCRIPTION
**Pull request by alonme**
**2022-05-09 Edit** (by @tiangolo): the scope of this PR was changed to remove docs/translations references to `aiofiles` as the other intended changes were covered in other PRs.

### Original description

Related to #3589 

This Starlette PR (https://github.com/encode/starlette/pull/1158/files#) solves the issue from #3589.

Updating starlette to solve this issue in FastAPI

### CODE REVIEW

**Comment by alonme** [comment]
PR #3372 also updates starlette, however it seems to take a long time to merge as it includes many other changes.

I hope we can merge this smaller branch quicker to resolve #3589 .

I copied the test fix from #3372 to prevent conflicts later

**Review by graingert — CHANGES_REQUESTED** [review]
The docs about aiofiles will need removing

**Comment by alonme** [comment]
@graingert  - Removed aiofiles and tested it still works for `FileResponse` and `StaticFiles`

**Comment by graingert** [comment]
what do you think about the contextlib2 backport changes? Starlette depends on it on python3.6 so FastAPI doesn't need the async_generator or async_exit_stack deps anymore

**Comment by alonme** [comment]
@graingert - Not to familiar with these, aren't these more related to the trio/anyio change? can we remove the backports without changes from #3372 ?

**Comment by graingert** [comment]
@alonme not directly related to anyio/trio no

**Comment by alonme** [comment]
@graingert - Thanks, backported these changes from the other PR.

**Comment by alonme** [comment]
Can anyone enable tests?

**Comment by Mause** [comment]
@tiangolo is the only person with merge and test run access unfortunately

**Comment by GuySpotnix** [comment]
+1
Please merge https://github.com/tiangolo/fastapi/issues/3589

**Comment by alonme** [comment]
resolves #3674

**Comment by graingert** [comment]
> PR #3372 also updates starlette, however it seems to take a long time to merge as it includes many other changes.

I'm not sure which changes in #3372 would delay the PR

**Comment by alonme** [comment]
@graingert, me neither - it just seemed to me that it wasn't getting merge in the time.
This pr was much smaller than #3372 , however after your rightful comments they aren't that different anymore.
This is still simpler, and i hoped it would be possible to merge it quickly as it fixes a bug which i think is pretty bad.

I didn't expect it to take 20 days, however i am not familiar with how long PR's take in this repo.

**Comment by graingert** [comment]
It would be good to get a release with a new Starlette that supports py3.6-py3.10 before the December EOL of Python 3.6

**Comment by alonme** [comment]
@tiangolo  - can we please go forward with this? or at least get a comment?
There are at least 2 issues that this will fix, and another project that waits for features from starlette 0.16

thanks

**Comment by brnosouza** [comment]
any update on this?

**Comment by stephan-hesselmann-by** [comment]
I have to say this is not a good look for the project. Not only this PR but many others are stalled with no comments from the maintainer. Actually it seems like the project is unmaintained.

**Comment by billcrook** [comment]
> @stephan-hesselmann-by you are correct unfortunately, this project is effectively abandoned

:100:  I'm considering dropping down to starlette directly esp considering all the shims and overrides I'm putting into place to get everything how I want it (custom error responses, finer grained transaction control, singleton dependencies, #1359, etc...). API doc is nice I suppose?

**Comment by tiangolo** [comment]
The project is not abandoned at all.

In fact, one of the main things wanted in the existing PRs and issues was a way to improve how models are defined for databases and Pydantic, and support for the latest versions of SQLAlchemy, so I spent months building https://github.com/tiangolo/sqlmodel, which is **made *for* FastAPI**. :rocket:

---

I have a lot of pending PRs to review and a lot of things in the backlog, and I'm covering them all gradually and with the minimum disruption possible. This also applies to all my Docker images, that for example, now support Python 3.9, all of them.

I'm carefully reviewing each PR and issue myself, and I have been changing my whole work-life in the last months, including dealing with visas and German bureaucracy to be able to dedicate much more time to all my open source projects.

Also, the comments claiming that it is abandoned were made 2 hours ago, when the last commit improving the [HTTPS guide](https://fastapi.tiangolo.com/deployment/https/) was done 3 hours ago. :facepalm: :disappointed:

The improved HTTPS guide is part of an effort into improving the information about deployments and how (and when) to use which Docker images, etc. So that will come soon too. :tada:

**Comment by adriangb** [comment]
Thank you for the response @tiangolo! I'm very glad this project is alive 😄

First off, I think it is amazing the amount and quality of work you are able to do as one person. That said, I do think it might be best for the health of the projects to build teams by giving repeat contributors that have shown to produce high quality work more privileges, that way they can get PRs into a good state (by providing feedback to PR authors) before you even have to look at them, even if you are still the one giving the final ✅ . This can also be codified, e.g. w/ `CODEOWNERS` files.

**Comment by v3ss0n** [comment]
> The project is not abandoned at all.
> 
> In fact, one of the main things wanted in the existing PRs and issues was a way to improve how models are defined for databases and Pydantic, and support for the latest versions of SQLAlchemy, so I spent months building https://github.com/tiangolo/sqlmodel, which is **made _for_ FastAPI**. rocket
> 
> I have a lot of pending PRs to review and a lot of things in the backlog, and I'm covering them all gradually and with the minimum disruption possible. This also applies to all my Docker images, that for example, now support Python 3.9, all of them.
> 
> I'm carefully reviewing each PR and issue myself, and I have been changing my whole work-life in the last months, including dealing with visas and German bureaucracy to be able to dedicate much more time to all my open source projects.
> 
> Also, the comments claiming that it is abandoned were made 2 hours ago, when the last commit improving the [HTTPS guide](https://fastapi.tiangolo.com/deployment/https/) was done 3 hours ago. facepalm disappointed
> 
> The improved HTTPS guide is part of an effort into improving the information about deployments and how (and when) to use which Docker images, etc. So that will come soon too. tada

Awesome to hear from you. I am using fastapi for almsot a year now. And the popularity keep rising.
I am sure FastAPI would be benefit from Community Driven development , since the project is growing faster for one person to manage, have you consider starting  a foundation / organization and appointing good contributors to help you review code / merge?

That would make FastAPI grow bigger and FastAPI is really the web framework python deserves.

**Comment by agronholm** [comment]
Does this PR add anything compared to the merged one?

**Review by banuni — APPROVED** [review]

**Comment by tiangolo** [comment]
Thanks for the discussion everyone, this was solved a while ago in another PR and has been available for a while in recent releases.

Given that, I reduced the scope of this particular PR to remove the docs/translations references to `aiofiles`. Thanks for the interest and discussion you all! :coffee:

**Pull request merged**
