### PR TITLE
🐛 Fix wrong OpenApi scheme generation for custom models with computed fields in additional responses

### PR DESCRIPTION
**Pull request by DavideGalilei**
Previously discussed here: **@computed_field not showing in OpenAPI Json** https://github.com/fastapi/fastapi/discussions/9856

### 📕 Description
- When using computed fields in a custom Pydantic model, FastAPI incorrectly uses `mode="validation"` for the additional responses model schema.

- This causes an issue where the response model is interpreted as an `-Input` model, thus excluding read-only computed fields from the documentation (note: the fields are correctly returned in the answer even if they are not shown in the documentation).

#### 👀 Example code
```python
from fastapi import FastAPI
from pydantic import BaseModel
from pydantic.fields import computed_field

app = FastAPI()

class Rectangle(BaseModel):
    width: int
    height: int

    @computed_field
    def area(self) -> int:
        return self.width * self.height

@app.get(
    "/rectangle/",
    responses={200: {"model": Rectangle}},
)
async def rectangle() -> Rectangle:
    return Rectangle(width=10, height=5)
```

#### ❌ Wrong (current) schema
<details>
<summary>Click to expand</summary>

image

```json
{
  "openapi": "3.1.0",
  "info": {
    "title": "FastAPI",
    "version": "0.1.0"
  },
  "paths": {
    "/rectangle/": {
      "get": {
        "summary": "Rectangle",
        "operationId": "rectangle_rectangle__get",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Rectangle-Input"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Rectangle-Input": {
        "properties": {
          "width": {
            "type": "integer",
            "title": "Width"
          },
          "height": {
            "type": "integer",
            "title": "Height"
          }
        },
        "type": "object",
        "required": [
          "width",
          "height"
        ],
        "title": "Rectangle"
      },
      "Rectangle-Output": {
        "properties": {
          "width": {
            "type": "integer",
            "title": "Width"
          },
          "height": {
            "type": "integer",
            "title": "Height"
          },
          "area": {
            "type": "integer",
            "title": "Area",
            "readOnly": true
          }
        },
        "type": "object",
        "required": [
          "width",
          "height",
          "area"
        ],
        "title": "Rectangle"
      }
    }
  }
}
```
</details>

#### ✅ Correct (fixed) schema:
<details>
<summary>Click to expand</summary>

image

```json
{
  "openapi": "3.1.0",
  "info": {
    "title": "FastAPI",
    "version": "0.1.0"
  },
  "paths": {
    "/rectangle/": {
      "get": {
        "summary": "Rectangle",
        "operationId": "rectangle_rectangle__get",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Rectangle"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Rectangle": {
        "properties": {
          "width": {
            "type": "integer",
            "title": "Width"
          },
          "height": {
            "type": "integer",
            "title": "Height"
          },
          "area": {
            "type": "integer",
            "title": "Area",
            "readOnly": true
          }
        },
        "type": "object",
        "required": [
          "width",
          "height",
          "area"
        ],
        "title": "Rectangle"
      }
    }
  }
}
```
</details>

#### OpenApi schema diff (wrong ➡️ correct)
```diff
18c18
<                   "$ref": "#/components/schemas/Rectangle-Input"
---
>                   "$ref": "#/components/schemas/Rectangle"
29,47c29
<       "Rectangle-Input": {
<         "properties": {
<           "width": {
<             "type": "integer",
<             "title": "Width"
<           },
<           "height": {
<             "type": "integer",
<             "title": "Height"
<           }
<         },
<         "type": "object",
<         "required": [
<           "width",
<           "height"
<         ],
<         "title": "Rectangle"
<       },
<       "Rectangle-Output": {
---
>       "Rectangle": {
```

### 💊 Fix
Use `mode="serialization"` for `create_model_field` for additional responses model.

### 🧪 Added tests!
- All tests pass and the code has been formatted
- `tests/test_additional_responses_custom_model_with_computed_fields.py`

### CODE REVIEW

**Comment by DavideGalilei** [comment]
Edit: I just notice this might be a duplicate PR of https://github.com/fastapi/fastapi/pull/11517

**Comment by alejsdev** [comment]
Hi @DavideGalilei, thank you for your interest in contributing to the project! Yes, this is a duplicate. We'll review both PRs in detail later. We currently have a high volume of PRs, so we're working through them and classifying them. We appreciate your patience as we manage the queue. 🙇‍♀️

**Comment by alejsdev** [comment]
Hi @DavideGalilei, thank you for your interest in contributing to the project! Yes, this is a duplicate. We'll review both PRs in detail later. We currently have a high volume of PRs, we appreciate your patience as we manage the queue. 🙇‍♀️

**Comment by flxdot** [comment]
> Hi @DavideGalilei, thank you for your interest in contributing to the project! Yes, this is a duplicate. We'll review both PRs in detail later. We currently have a high volume of PRs, we appreciate your patience as we manage the queue. 🙇‍♀️

And the PR is a duplicate of #10895 :)

**Review by svlandeg — COMMENTED** [review]
Hi @DavideGalilei, thanks for the contribution!

Your fix is correct, but the PR is indeed a duplicate of #11517 and #10895. My suggestion is to merge the earliest PR #10895 and close this one, but I'll leave the final review for Tiangolo.

Thanks again though! 🙏

**Comment by tiangolo** [comment]
Thanks for the interest @DavideGalilei! As @svlandeg was saying, this was handled in https://github.com/fastapi/fastapi/pull/10895. That is now available in FastAPI `0.115.1`. So I'll now pass on this one, but thanks for the effort! :coffee:

**Pull request closed without merging**
