### PR TITLE
chinese translation add tutorial/sql-databases.md

### PR DESCRIPTION
**Pull request by maoyibo**
chinese translation add tutorial/sql-databases.md

### CODE REVIEW

**Comment by maoyibo** [comment]
docs/zh query_params.md rm superfluous content #2384
The last chapter "Optional 类型声明" not exists any more in English tutorial, and tutorial007.py not exists too. so this chapter should be removed.

**Comment by waynerv** [comment]
You should create a single pull request per page translated. It's too hard to review all 3 pages in one PR.

**Comment by maoyibo** [comment]
> You should create a single pull request per page translated. It's too hard to review all 3 pages in one PR.

OK, I will close this PR, and Create separate PR for each chapter.

**Comment by maoyibo** [comment]
Chinese translation add tutorial/sql-databases #2408
Chinese translation add tutorial/body-nested-models #2409
Chinese translation add tutorial/extra-data-types #2410
Chinese translation add tutorial/schema-extra-example #2411
Chinese translation add tutorial/header-params #2412

**Pull request closed without merging**
