### PR TITLE
📝 Update includes in `docs/en/docs/tutorial/bigger-applications.md` WIP

### PR DESCRIPTION
**Pull request by FarhanAliRaza**
related to https://github.com/fastapi/fastapi/issues/12554

### CODE REVIEW

**Comment by alejsdev** [comment]
Hi @FarhanAliRazam, thanks for your interest in contributing to FastAPI! 
There's a problem in the preview of the docs. Are you still working on this? Could you fix it? Thank you! :raised_hands: 

image

**Comment by FarhanAliRaza** [comment]
They syntax for title="title" is not clear for new syntax.

**Comment by FarhanAliRaza** [comment]
https://github.com/fastapi/fastapi/issues/12554#issuecomment-2439677965

**Comment by tiangolo** [comment]
Thanks for the effort! :cake: 

This was handled in another PR, so I'll close this one now. :coffee:

**Pull request closed without merging**
