### PR TITLE
✨ Add allow disabling `redirect_slashes` at the FastAPI app level

### PR DESCRIPTION
**Pull request by cyberlis**
Right now `redirect_slashes` parameter in sub routers created with `APIRouter` ignored, because only main router's `redirect_slashes` inside FastAPI class is taken into account. FastAPI class creates new router without `redirect_slashes` argument and that's why router always uses default value `redirect_slashes=True` and always redirects on trailing slashes.
https://github.com/tiangolo/fastapi/blob/master/fastapi/applications.py#L69

Here is how to reproduce this problem
```python
from fastapi import FastAPI
from fastapi.routing import APIRouter

router = APIRouter(redirect_slashes=False)

@router.get('/hello/')
def hello_page() -> str:
    return 'Hello, World!'

app = FastAPI()
app.include_router(router)
```

And if you request page `http://127.0.0.1:8080/hello` (without trailing slash) you will be redirected even with `redirect_slashes=False`

```bash
uvicorn main:app
INFO:     Started server process [96046]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:57330 - "GET /hello HTTP/1.1" 307 Temporary Redirect
INFO:     127.0.0.1:57330 - "GET /hello/ HTTP/1.1" 200 OK
```

I added `redirect_slashes` to `__init__` method of FastAPI class and passed it to router's constructor.
That way I can change trailing slashes redirect behaviour globally for application instance.

### CODE REVIEW

**Comment by cyberlis** [comment]
please review @tiangolo

**Comment by StashOfCode** [comment]
Hey @tiangolo, any news on this pr? It solves a lot of hassle with 'slash/no slash' related redirects @Kludex @jaystone776

**Review by sk- — APPROVED** [review]
LGTM

**Comment by sk-** [comment]
@Kludex @tiangolo is there any chance this PR could be reviewed? I did review the code myself and it looks good and tested.

Some others have also spent the time writing a PR solving the same issue. See https://github.com/tiangolo/fastapi/pull/5392.

Our motivation for having this merged:
We have stumbled across this issue, because some times customers make the mistake of adding/removing the trailing slash which increases the latency and later on they complain that our provided endpoints are slow.

It'd be great if we could control whether `redirect_slashes` is set.

**Review by yezz123 — APPROVED** [review]

**Comment by cyberlis** [comment]
@Kludex @tiangolo  please review PR

**Review by lieryan — APPROVED** [review]

**Comment by xpinguin** [comment]
Hi guys, could you please update us about the status of this PR? We're waiting waiting for this feature in master for a long time already and custom hacks aren't good. Thanks a lot!

**Comment by cyberlis** [comment]
> Hi guys, could you please update us about the status of this PR? We're waiting for this feature in master for a long time already and custom hacks aren't good. Thanks a lot!

I'll update it tomorrow

**Comment by cyberlis** [comment]
Hey @tiangolo,
This PR is ready to be merged
It has tests and people still need it

**Review by lieryan — APPROVED** [review]

**Review by Kludex — APPROVED** [review]

**Comment by Kludex** [comment]
`Starlette` class doesn't have this parameter. It only exists on the `Router` class in Starlette. jfyk @tiangolo

**Comment by tiangolo** [comment]
Makes sense, thank you @cyberlis! 🚀 

Thanks everyone for the reviews, especially for commenting that you tried out the code and confirming that this works and is useful for you. 🙇 🍰 

This will be available in FastAPI `0.98.0`, released in the next hours. 🎉

**Pull request merged**
