### PR TITLE
📝 Tweak docs and translations links, typos, format

### PR DESCRIPTION
**Pull request by nilslindemann**
Regeneration of #10985 minus ambiguous changes, which I outsource to #11390. It should now be easier to review. All changes here are unambiguous improvements.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit beef2fb6690ea49d8641fb229b641e90e2563d19 at: https://d1be5c2a.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit f502f5186518e368b51b23aa2fece939c9a624d7 at: https://063f9634.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit e613636da8d9491572d59a03707898af09441b39 at: https://9fc802bb.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
Nice, thank you @nilslindemann! :rocket: :cake:

**Comment by nilslindemann** [comment]
Dito @tiangolo, thank you.

**Pull request merged**
