### PR TITLE
✏️ Remove broken links from `external_links.yml`

### PR DESCRIPTION
**Pull request by Torabek**
A little bit of clean-up of external articles

### CODE REVIEW

**Review by hasansezertasan — APPROVED** [review]
LGTM.

**Comment by tiangolo** [comment]
📝 Docs preview for commit ef94d6c7e3f8a03fe233f862b0a334e3dfa75515 at: https://52ec2de8.fastapitiangolo.pages.dev

**Review by Kludex — APPROVED** [review]

**Comment by Kludex** [comment]
@tiangolo I did this some years ago for Awesome FastAPI: https://github.com/mjhea0/awesome-fastapi/blob/main/.github/workflows/expired-links.yml

Detects 404 links on MkDocs.

**Comment by tiangolo** [comment]
Nice, thank you @Torabek! 🤓 

Good tip @Kludex! Thanks! I was precisely thinking about something like this. I'll probably have to do it in a custom script/action as the source is in YAML, but the markdown one looks interesting as well for other places. 🤔

**Pull request merged**
