### PR TITLE
✨ Support Python internal description on Pydantic model's docstring

### PR DESCRIPTION
**Pull request by Kludex**
## Problem

Currently, on FastAPI endpoint functions we can document for OpenAPI description/Swagger and for internal Python purposes:
```python
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI()

@app.get("/")
def useful():
    """My description.
    \f
    Internal documentation.
    """
    ...
```
On Swagger we'll have:
image
 
When documenting models, it doesn't have the same behavior:
```python
from enum import Enum
from fastapi import FastAPI

class Banana(str, Enum):
    """My description.
    \f
    Internal documentation.
    """
    HAHA = "haha"
    HOHO = "hoho"

app = FastAPI()

@app.get("/")
def useful(banana: Banana):
    ...
```
On Swagger, we'll have:
image
    
## Solution

The proposed _two lines of code_ on this PR, makes it possible to have the same behavior as the endpoint description:
image

It follows the same idea as: https://github.com/tiangolo/fastapi/blob/10397ddc30ef9bb26e9247f04fe20ce3045081c4/fastapi/routing.py#L350

## Related issues
- https://github.com/tiangolo/fastapi/issues/3024

## Questions & Alternatives
- Should Pydantic handle this on the [model_process_schema()](https://github.com/samuelcolvin/pydantic/blob/e68c277afe6bf6e7966bfecfe9b228d33f2de44b/pydantic/schema.py#L519) function instead?

### CODE REVIEW

**Comment by Kludex** [comment]
Do you have an opinion on this? @prettywood

**Comment by killswitch-GUI** [comment]
Just bumping.

**Comment by tiangolo** [comment]
Awesome, thanks @Kludex! :cake:

**Comment by killswitch-GUI** [comment]
@tiangolo and @Kludex thanks for helping fix this! The team will be thankful!

**Comment by Kludex** [comment]
@tiangolo Even if coverage didn't drop, Kludex forgot a test case for this, jfyk.

**Pull request merged**
