### PR TITLE
📝 Update FastAPI instrumentation external link

### PR DESCRIPTION
**Pull request by softwarebloat**

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit dcf3433f5c938a20a96feaea21dd56a607ebb416 at: https://0af41abd.fastapitiangolo.pages.dev

**Review by codespearhead — APPROVED** [review]
This improves the wording of a specific section of the English documentation.

**Comment by codespearhead** [comment]
@softwarebloat Do you happen to know two other developers that speak English which you can ask a [PR review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) from?

**Comment by softwarebloat** [comment]
@codespearhead no, not really

**Comment by alejsdev** [comment]
Updated! @softwarebloat  :nerd_face: :v:

**Pull request merged**
