### PR TITLE
🌐 Add German translation for `docs/de/docs/reference/encoders.md`

### PR DESCRIPTION
**Pull request by nilslindemann**
← `reference/security/index.md` (#10839)
→ `reference/staticfiles.md` (#10841)

[German translation progress](https://github.com/tiangolo/fastapi/discussions/10582)

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 0820ed947574491741147adc84faf83cdcaa6f4a at: https://913d12e6.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 0a44bf867494de27589f4db901e2aab5b75e6153 at: https://38d8d600.fastapitiangolo.pages.dev

**Review by dpinezich — APPROVED** [review]
well done 👍

**Comment by alejsdev** [comment]
Thanks for your contribution! @nilslindemann 😄🎉 

And thanks for the help @dpinezich 🔍

**Comment by nilslindemann** [comment]
Klasse!

**Pull request merged**
