### PR TITLE
✏️ Fix typo: convert every 're-use' to 'reuse'.

### PR DESCRIPTION
**Pull request by hasansezertasan**
First of all, I'm not a native English speaker.

I was reading the documentation and I saw that the author used both "reuse" and "re-use" in different places. I taught, which is correct?

I did some research and decided to change it to "reuse".

### CODE REVIEW

**Comment by hasansezertasan** [comment]
Meanwhile Grammarly...

image

**Comment by tiangolo** [comment]
📝 Docs preview for commit 91d72876c8390518be1871ee8ecec2a9e96b8764 at: https://1de6d8db.fastapitiangolo.pages.dev

**Comment by alejsdev** [comment]
You're right, thank you! @hasansezertasan :partying_face:

**Comment by hasansezertasan** [comment]
> You're right, thank you! @hasansezertasan 🥳

Happy to hear that I'm right 🤖.

**Pull request merged**
