### PR TITLE
🌐 Update code highlights in `docs/zh/docs/tutorial/body.md`

### PR DESCRIPTION
**Pull request by wushuangX**

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 2d55b5b97aa9f9c21e38ca9699125c9d96003f35 at: https://649a2184acd72b175a61ec06--fastapi.netlify.app

**Review by Sefank — CHANGES_REQUESTED** [review]
I think this change is outdated as the EN docs have been updated. May be a duplicate of #9738.

**Comment by xzmeng** [comment]
this PR should be closed since #9738 has been merged

**Comment by tiangolo** [comment]
Thank you @wushuangX! 🙇 

And thanks for the pointer @xzmeng. 🤓 

As this was included in that other PR, I'll close this one.

**Pull request closed without merging**
