### PR TITLE
🌐 Add Chinese translation for `docs/zh/docs/deployment/https.md`

### PR DESCRIPTION
**Pull request by jaystone776**
as title

### CODE REVIEW

**Review by zy7y — COMMENTED** [review]
缺少 HTTPS for Developers 之后的内容

**Review by zy7y — COMMENTED** [review]
缺少 HTTPS for Developers之后的内容 当前版本0.73

**Comment by tiangolo** [comment]
📝 Docs preview for commit a96292b488cbc317f660279a2ff3dd9efa778f11 at: https://649a08ee219954094e357f72--fastapi.netlify.app

**Comment by tiangolo** [comment]
It seems this was covered in another PR, so I'll now close this one, but thanks for the effort! :rocket: :cake:

**Pull request closed without merging**
