### PR TITLE
⬆️ Bump Starlette from 0.22.0 to 0.23.0

### PR DESCRIPTION
**Pull request by Kludex**
## Changes

- Remove `websocket_route` decorator in favor of `websocket` from the test suite.
- Add `on_event`, `middleware` and `exception_handler` middlewares on `FastAPI`.
- Add `route` and `on_event` on `APIRouter`.
- Change Starlette range from `==0.22.0` to `>=0.22.0,<=0.23.0` - I know that you pin Starlette because minimal changes there can break FastAPI, but I'm making the range wider just for you to evaluate if it makes sense.

## Preemptive questions you may have when reviewing it

- Sebastián: Do I want to reimplement the decorator methods as it's in this PR, or should I define the decorators, and still call starlette i.e. `super().middleware()`, but suppress the `DeprecationWarning`s with a warning filter?

EDIT: I think I shouldn't have removed the `websocket_route`, but actually implemented it :sweat_smile: You'll see the coverage.

### CODE REVIEW

**Comment by musicinmybrain** [comment]
Thank you for your continued work on keeping up with Starlette releases!

Version 0.23.1 was released two days ago with a [very small bug fix](https://github.com/encode/starlette/compare/0.23.0...0.23.1).

**Comment by musicinmybrain** [comment]
> Thank you for your continued work on keeping up with Starlette releases!
> 
> Version 0.23.1 was released two days ago with a [very small bug fix](https://github.com/encode/starlette/compare/0.23.0...0.23.1).

I just realized this is not news to you, because you released it!

**Comment by musicinmybrain** [comment]
> Any chance of this being merged sometime soon? :)

Support for Starlette 0.23.1 and/or 0.24.0 would be nice as well.

**Comment by tiangolo** [comment]
Thanks @Kludex! :man_dancing: :cake: 

I implemented `websocket_route()`, and tweaked/fixed a couple of things with the tests and coverage.

**Pull request merged**
