### PR TITLE
🌐 Add Chinese translation for for `docs/zh/docs/deployment/index.md` and `docs/zh/docs/external-links.md`

### PR DESCRIPTION
**Pull request by stephenatgithub**
Added Chinese translation for 2 pages:
docs/zh/docs/external-links.md
docs/zh/docs/deployment/index.md

Modified to contain the newly added file
docs/zh/mkdocs.yml

### CODE REVIEW

**Review by iamgabrieldev — APPROVED** [review]

**Comment by tiangolo** [comment]
Thank you for the contribution @stephenatgithub! It would probably be better to have one PR per markdown file, that makes it easier for others to review it, and if something needs changes, it won't block the other file from getting merged. :coffee: 

@iamgabrieldev do you speak Chinese? If you do, thanks for the review! Otherwise, please remove your review, as the idea with reviews is for people that speak the language to approve the translation.

**Comment by iamgabrieldev** [comment]
yes i speak chinese and i live in china =).

**Comment by tiangolo** [comment]
Awesome @iamgabrieldev! Your help is very much appreciated. 🙇 🍪

**Comment by tiangolo** [comment]
📝 Docs preview for commit 78cae43b58c371c9331aeb57910baabb65ea1e99 at: https://649a1e8f2199541688357ec3--fastapi.netlify.app

**Comment by tiangolo** [comment]
📝 Docs preview for commit 62ef1bdc421cb8395fdd872da12562aa9e57eb47 at: https://649d84be32317306e15429b0--fastapi.netlify.app

**Comment by tiangolo** [comment]
📝 Docs preview for commit 62ef1bdc421cb8395fdd872da12562aa9e57eb47 at: https://649d84ddb205ee05f26c99cb--fastapi.netlify.app

**Pull request closed without merging**
