### PR TITLE
⬆️  Bump Uvicorn max range to 0.17.x

### PR DESCRIPTION
**Pull request by pedropozzobon**
I believe this is important to be done due to:

https://github.com/encode/uvicorn/pull/1400
https://github.com/MagicStack/httptools/issues/76

### CODE REVIEW

**Comment by dynalz** [comment]
New versions of Uvicorn are not compatible with FastAPI, doing a few tests websockets stop working all together.

**Comment by pedropozzobon** [comment]
@dynalz Can you give more info on this? I've just run the three examples in https://fastapi.tiangolo.com/advanced/websockets/, using the following environment and they seem to be working:

env-example

**Comment by Kludex** [comment]
> New versions of Uvicorn are not compatible with FastAPI, doing a few tests websockets stop working all together.

An issue on uvicorn on how to reproduce it is appreciated...

**Comment by odiseo0** [comment]
Same here, installed Uvicorn (standard) separately from FastAPI and it's doing fine, currently in 0.17.6

**Comment by tiangolo** [comment]
Thanks @pedropozzobon! And thanks for the conversation everyone.

This was included as part of https://github.com/tiangolo/fastapi/pull/4803, and it will be available in FastAPI `0.75.2` in a couple of hours, so I'll close this one now.

But thanks for the effort @pedropozzobon! :cake:

**Pull request closed without merging**
