### PR TITLE
🌐 Add Portuguese translation for `docs/pt/docs/advanced/async-tests.md`

### PR DESCRIPTION
**Pull request by ceb10n**

### CODE REVIEW

**Review by nazarepiedady — APPROVED** [review]
To me, it is well-done, good enough to be applied to the main branch.

Thanks for your contribution.

**Comment by lucasbalieiro** [comment]
HI, guys!

Everything seems fine to me.

Great work @ceb10n

**Review by Joao-Pedro-P-Holanda — APPROVED** [review]
Great Translation 🚀

**Review by lucasbalieiro — APPROVED** [review]

**Comment by alejsdev** [comment]
Thanks for your contribution! @ceb10n :1st_place_medal: 
And thanks for the reviews @lucasbalieiro @nazarepiedady @Joao-Pedro-P-Holanda :sunglasses:

**Pull request merged**
