### PR TITLE
🐛 Fix padlocks on routes in SwaggerUI for custom authentication implementations

### PR DESCRIPTION
**Pull request by JonasKs**
Context can be found here: https://github.com/Intility/fastapi-azure-auth/issues/106

In short:
* In order to get scopes show up under the padlock, scopes on the route has to be passed on
* The reason I can't just subclass `Oauth2` is because of `mypy`, and my `__call()__` function does not return an `str | None` like yours, but a user instead.

Before these changes with FastAPI-Azure-Auth, you cannot select a scope when clicking the padlock:

<details>
  <summary>Click to see gif before changes</summary>

Screen Recording 2022-11-10 at 20 28 39

</details>

After the change you can select the scope with the padlock:

<details>
  <summary>Click to see gif after changes</summary>

Screen Recording 2022-11-10 at 20 27 21

</details>

For more information, please read the https://github.com/tiangolo/fastapi/pull/5614#issuecomment-1311393661 below.

### CODE REVIEW

**Comment by JonasKs** [comment]
If accepted I'll happily add a test that includes checks for the OpenAPI schema. 

As you can see [here](https://github.com/Intility/fastapi-azure-auth/pull/107#discussion_r1019582602) my openapi schemas changed a bit in FastAPI 0.80.0: we now get duplicate schema name and scope keys in openapi documentation. This unfortunately breaks the padlock too, hence the last commit.

**Comment by JonasKs** [comment]
Hey @tiangolo , since you added the `investigate` label, I decided to add the test and write a little explanation: 

If you run the client in the test (`uvicorn tests.test_security_openapi_custom_oauth2:app`) and open the docs, click authorize, you'll see this:

image

As you can see in the test, there's two dependencies: One `Depends(reusable_custom_oauth2)` and one `Security(reusable_custom_oauth2, scopes=["read:users", "not:valid:scope"])` on the route itself. 

If you click the padlock, you'll see that the `not:valid:scope` is not there, since it is not defined as a valid scope in the `securitySchemes`, but you will see the `read:users` scope as expected:

image


If you run this test on `master`, you'll see this openapi.json diff: (green = this branch, red = master)

```diff
{
  "components": {
    "securitySchemes": {
      "My Custom Oauth2 schema": {
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://some-url.com/authorization",
            "scopes": {
              "read:users": "Read the users",
              "write:users": "Create users"
            },
            "tokenUrl": "https://some-url.com/token"
          }
        },
        "type": "oauth2"
      }
    }
  },
  "info": {
    "title": "FastAPI",
    "version": "0.1.0"
  },
  "openapi": "3.0.2",
  "paths": {
    "/users/me": {
      "get": {
        "operationId": "read_current_user_users_me_get",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {}
              }
            },
            "description": "Successful Response"
          }
        },
        "security": [
-          {
-            "My Custom Oauth2 schema": []
-          },
-          {
-            "My Custom Oauth2 schema": []
-          }
+          { 
+            "My Custom Oauth2 schema": ["read:users", "not:valid:scope"]
+          }
        ],
        "summary": "Read Current User"
      }
    }
  }
}
```

On Master, the padlock is empty when clicking it:


image

**Comment by JonasKs** [comment]
Not sure why coverage went _down_ by adding a test 🤔

**Review by yezz123 — APPROVED** [review]
🌟

**Comment by JonasKs** [comment]
Thanks for the review @yezz123 - I assume your (awesome) `authx` need these changes too.

**Review by BilalAlpaslan — APPROVED** [review]

**Comment by yezz123** [comment]
> Thanks for the review @yezz123 - I assume your (awesome) `authx` package need these changes too.

Yes, I was looking to override much of things, especially the scopes part 🚀

**Comment by JonasKs** [comment]
@tiangolo ready for review

**Comment by JonasKs** [comment]
Rebased with `master` to avoid merge commit added.

**Comment by Pkumar-1988** [comment]
hello @tiangolo and @JonasKs,

Happy new year.. 

do you think this change will be merged and ready for your next release?

thanks,
Praveen

**Comment by JonasKs** [comment]
Oh god, I messed up rebasing. Please hold. :eyes:

**Comment by Pkumar-1988** [comment]
> Oh god, I messed up rebasing. Please hold. 👀

hope its all good now as I can see no conflicts..

**Comment by JonasKs** [comment]
image


There we go, it's up to date with @tiangolo's master branch. 😊

**Comment by Pkumar-1988** [comment]
Hello @JonasKs , @yezz123 , @tiangolo 

Do you have an update on merging this into main?

thanks,
Praveen

**Comment by JonasKs** [comment]
Sorry @Pkumar-1988, but these things can take time. 😊 I have no updates though. I merged in `master`, so if Tiangolo has the time, it will be an updated branch.

**Comment by JonasKs** [comment]
I'll close this as it hasn't been merged for two years - I suspect it's easier to start over than to rebase after all pydantic v2 changes. 

Personally I don't need this fix, it was a request in FastAPI-Azure-Auth, so if someone is reading this and wants it - feel free to use anything from this PR as your own code.

**Pull request closed without merging**
