### PR TITLE
🌐 Add Korean translation for `docs/ko/docs/tutorial/body.md`

### PR DESCRIPTION
**Pull request by strawberry-trap**
translated docs/tutorial/body.md for Korean community.

### CODE REVIEW

**Comment by strawberry-trap** [comment]
I only added single .md file and modified mkdocs.yml, but the test had failed. Could anyone give me a short guideline ?

**Comment by joonas-yoon** [comment]
I have no idea what is the reason to happen error.

and I think this PR is duplicated. The translation for ` docs/ko/docs/tutorial/body.md` is already in progressed and still not merged yet: https://github.com/tiangolo/fastapi/pull/2392

I am so pleased and have my thanks for your works.

For Korean who just like you, I made checklist - https://github.com/tiangolo/fastapi/discussions/3167#discussioncomment-3335089 - and the korean translated page in nightly version (check it in comment)

**Comment by tiangolo** [comment]
📝 Docs preview for commit 3ec550f526267df0d41605963ad8f0fbd8623b8c at: https://649a1b01acd72b13fc61ea0a--fastapi.netlify.app

**Comment by alejsdev** [comment]
Thanks for your effort @strawberry-trap 🐱  

However, this PR has been inactive for a while, and the changes proposed here have already been addressed in another PR (https://github.com/tiangolo/fastapi/pull/11000) that has been merged. As a result, we will be closing this PR. 

We appreciate your effort and encourage you to continue contributing in the future. Please feel free to check out the other open issues and PRs. Thank you! ✨

**Pull request closed without merging**
