### PR TITLE
⬆️ Bump Uvicorn max range to 0.15.0

### PR DESCRIPTION
**Pull request by Kludex**
EDIT: We probably want to add `asgiref` as dependency and use its types.

### CODE REVIEW

**Comment by jedidiahhorne** [comment]
awesome, thanks guys!

**Comment by musicinmybrain** [comment]
I have no influence over the FastAPI project, but:

- Consider bumping the maximum uvicorn dependency in the `dev` extra to match the `all` extra.
- Also, uvicorn 0.15.0 is now released. Can it be safely allowed too?

**Comment by Kludex** [comment]
Thanks for the review @musicinmybrain :)

**Comment by tiangolo** [comment]
Great, thanks @Kludex! :cake: 

For now, I would prefer not to add a dependency on `asgiref` only for the types (`asgiref` as a bunch of other tools apart from the types), and as ASGI is just dicts everywhere I would think we should be able to get the annotations right.

Thanks everyone else for the comments too! :coffee:

**Comment by Kludex** [comment]
The thing is that Starlette is too generic on its ASGI types, and uvicorn is strict now.

In any case, FastAPI shouldn't care about asgiref, I'm going to take care on Starlette.

**Comment by tiangolo** [comment]
> In any case, FastAPI shouldn't care about asgiref, I'm going to take care on Starlette.

Woohoo! Nice :tada: :sunglasses: :nerd_face:

**Pull request merged**
