### PR TITLE
fix: typo in First Steps doc

### PR DESCRIPTION
**Pull request by IgnatovFedor**
In first program example function returns`{"message": "Hello World"}` instead of `{"hello": "world"}` (see https://fastapi.tiangolo.com/tutorial/first-steps/).

### CODE REVIEW

**Comment by alimcmaster1** [comment]
This isn’t a typo? It’s just a JSON example of the response body.

**Comment by IgnatovFedor** [comment]
> This isn’t a typo? It’s just a JSON example of the response body.

@alimcmaster1 an example of simplest FastAPI server is shown in documentation and below is not some JSON example of the response body but expected response of this server.

**Comment by alimcmaster1** [comment]
Ahh yes you are correct - didn’t see the top of the example. This LGTM - @tiangolo

**Comment by tiangolo** [comment]
Oops! :sweat_smile: Thanks @IgnatovFedor ! :tada: :cake: Good catch! :male_detective: :mag: :bug: :memo: 

And thanks @alimcmaster1 for the review!

**Pull request merged**
