### PR TITLE
🌐 Add Korean translation for `docs/ko/docs/learn/index.md`

### PR DESCRIPTION
**Pull request by KaniKim**
- Add Korean translation for docs/ko/docs/learn/index.md

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 6c4804283eb42cef0c1d46d86aa90ad7d2663527 at: https://72ae6ff0.fastapitiangolo.pages.dev

**Review by junah201 — APPROVED** [review]

**Comment by tiangolo** [comment]
📝 Docs preview for commit 1230a3f19c8f68dab07d5ea2395b3b17f2bb0de4 at: https://24129860.fastapitiangolo.pages.dev

**Review by hard-coders — APPROVED** [review]
LGTM 🚀

**Comment by alejsdev** [comment]
Thank you! @KaniKim 🤓 

And thanks for the reviews @hard-coders @junah201 ✌️

**Pull request merged**
