### PR TITLE
✨ Pydantic v2 migration, initial implementation

### PR DESCRIPTION
**Pull request by tiangolo**
✨ Pydantic v2 migration, initial implementation

Continues from https://github.com/tiangolo/fastapi/pull/9442, but from a branch in this repo, to let me push to it. :nerd_face: 

**2023-06-16**:

Most of the initial implementation is done. Tests are passing locally for both Pydantic v1 and v2.

Still missing:

- Set up CI to run both Pydantic v1 and v2
- Refactor `_compat.py` to remove continuous runtime checks for `PYDANTIC_V2`
- Update docs for usage with Pydantic v1 and v2
- Deprecations and warnings

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit a1318c481c7c35b59a2891ae6ce08574b8df9754 at: https://648c4aebc9851702789b2e21--fastapi.netlify.app

**Comment by tiangolo** [comment]
📝 Docs preview for commit 8b4a258d306fd79c88f94d3b451f966a5ad476e6 at: https://648c708af0fb641b71284db8--fastapi.netlify.app

**Comment by Kludex** [comment]
👀 👍

**Comment by wu-clan** [comment]
😲😲😲

**Pull request merged**
