### PR TITLE
📝 Update `docs/en/docs/tutorial/body.md` with Python 3.10 union type example

### PR DESCRIPTION
**Pull request by rangzen**
Small update for the union note because the default example is from the non-default displayed version.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit b0759c463f912237824b422252f1e79fff5bb472 at: https://bfd4257d.fastapitiangolo.pages.dev

**Comment by rangzen** [comment]
Looks good, see https://bfd4257d.fastapitiangolo.pages.dev/tutorial/body/#request-body-path-query-parameters

**Review by svlandeg — APPROVED** [review]
Thanks for the PR! I took the liberty of updating it with `master`. 

I was reading through this page recently, and I actually noticed this same occurrence. I also thought it was weird to comment only on the `Python 3.8`-style of code (probably due to historical reasons...). Anyway, I definitely think this edit is an improvement and will avoid confusion by readers.

**Comment by tiangolo** [comment]
Good idea, thanks @rangzen! :rocket: 

In fact, I updated it a bit to mention Python 3.10 first, that's the most important. :sunglasses: 

Thanks @svlandeg for your help! :cake:

**Pull request merged**
