### PR TITLE
🐛 Allow exit code for dependencies with `yield` to always execute, by removing capacity limiter for them, to e.g. allow closing DB connections without deadlocks

### LINKED ISSUE #3205: Using dependency injection to get SQLAlchemy session can lead to deadlock
### First check

- [x] I added a very descriptive title to this issue.
- [x] I used the GitHub search to find a similar issue and didn't find it.
- [x] I searched the FastAPI documentation, with the integrated search.
- [x] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [x] I already read and followed all the tutorial in the docs and didn't find an answer.
- [x] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [x] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [x] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).
- [x] After submitting this, I commit to one of:
  - Read open issues with questions until I find 2 issues where I can help someone and add a comment to help there.
  - I already hit the "watch" button in this repository to receive notifications and I commit to help at least 2 people that ask questions in the future.
  - Implement a Pull Request for a confirmed bug.

I've noticed that when using dependency injection with SQLAlchemy, a large number of concurrent requests can leave the app in a deadlocked state. This is especially noticeable with a small SQLAlchemy connection pool size (relative to the FastAPI thread pool size). Below is a self-contained example (you might have to tweak the pool size and the request body's sleep length but this should be a good starting point).

<details>
  <summary>View <code>app.py</code></summary>

```python
"""
Setup: pip install fastapi sqlalchemy uvicorn
Run: python app.py
"""
import time
import uvicorn

from fastapi import Depends, FastAPI, Request
from sqlalchemy import create_engine
from sqlalchemy.orm import Session, sessionmaker
from sqlalchemy.pool import QueuePool


# SQLAlchemy setup
engine = create_engine(
    'sqlite:///test.db',
    connect_args={'check_same_thread': False},
    poolclass=QueuePool,
    pool_size=4,
    max_overflow=0,
    pool_timeout=None,  # Wait forever for a connection
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

# FastAPI
app = FastAPI()

def get_db(request: Request):
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

@app.get('/')
def index(db: Session = Depends(get_db)):
    # Some blocking work
    _ = db.execute('select 1')
    time.sleep(1)
    return {'hello': 'world'}

# Run
if __name__ == '__main__':
    uvicorn.run('app:app', reload=True, host='0.0.0.0', port=80)
```

</details>

When running the above with 100 concurrent requests (I used [locust](https://locust.io/)), I noticed that only around 5 requests are served, and then the app freezes and is unable to serve any more requests. Below is the locustfile.

<details>
  <summary>View <code>locustfile.py</code></summary>

```python
"""
Setup: pip install locust
Run: Save as locustfile.py and run locust in terminal. Open http://localhost:8089 and run with 100, 100, http://localhost.
"""
from locust import HttpUser, task


class User(HttpUser):
    @task
    def index(self):
        self.client.get("/")
```

</details>

I suspect the following is happening. (Note that `SessionLocal()` is lazy, so `db = SessionLocal()` will return immediately even if no connections are available.)

1. The first `N` requests come in (where `N` >= thread pool size). Their `get_db` dependencies run and yield, and we start executing their path operation functions. At this point, the entire thread pool is full. Only `pool_size` (4) requests are able to get a connection, and the remaining requests wait (in their path operation functions).
2. The path operation functions that were able to get a connection return, opening up `pool_size` (4) spots in the thread pool. Because dependencies and requests run in separate threads, the `finally` blocks for these requests' `get_db` dependencies have not run yet, so the connections for these requests have not returned to the SQLAlchemy pool.
3. More requests come in, and like step 1, their `get_db` dependencies run, and we start executing their path operation functions. No connections have returned to the SQLAlchemy pool, so these requests wait. At this point, the entire thread pool is full, and every thread is waiting for a connection.
4. For the requests that finished in step 2, we try to schedule the `finally` blocks for their `get_db` dependencies in a new thread so we can free the connections, but all of the threads are busy, so we end up waiting.
5. None of the threads will ever finish because they are waiting for a connection, and no connections will be released because the thread pool is full, leaving the app in a deadlocked state.

This doesn't really seem like a bug in FastAPI or in SQLAlchemy, but it suggests that we should not use dependency injection like this when using synchronous database libraries. The only workaround I've found for this is to use a context manager to handle the session in the endpoint itself instead of injecting the database session directly.

Another thing I've noticed is that changing `get_db` to be an async function prevents deadlock (as does using the [middleware approach](https://fastapi.tiangolo.com/tutorial/sql-databases/#alternative-db-session-with-middleware)), but only if the endpoint does not have a `response_model`. If it has a `response_model` then the app will still lock up. I believe this is because if `response_model` is defined, then when we run [`serialize_response`](https://github.com/tiangolo/fastapi/blob/master/fastapi/routing.py#L106), `field` will be non-None, and we will attempt to run `field.validate` in a separate thread. If the thread pool is full with requests waiting for connections, we won't be able to serialize the response and won't be able to close the database connection. Maybe we could serialize the response in the same thread as the path operation function; I'm not sure what the benefit of serializing in a separate thread is.

There is similar discussion in https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/104 and many others came to the conclusion that using a context manager is the right approach, but nothing really came of it. If others can validate that my suspicion is correct, then maybe we should change the docs to recommend using a context manager within the endpoint itself until a better solution is available.

### Environment

- OS: macOS Big Sur (11.3)
- FastAPI Version: 0.63.0
- SQLAlchemy Version: 1.4.13
- Python version: 3.9.4

### PR DESCRIPTION
**Pull request by adriangb**
Related to #3205 

Tested this against https://github.com/harsh8398/fastapi-dependency-issue

### CODE REVIEW

**Comment by Kludex** [comment]
If a new `CapacityLimiter` is created every time, then the token can be 1... Can't it?

The inf would make sense for a global limiter... Isn't it the case?

**Comment by adriangb** [comment]
Yeah I guess it can be 1. Or we can make it a global. Either way.

**Comment by tiangolo** [comment]
Niceee! :nerd_face: :rocket:

I tested this with the example code in: https://github.com/tiangolo/fastapi/issues/3205

I used `wrk` and I ran twice:

```console
$ wrk -c 100 -t 100 --timeout 60 "http://127.0.0.1:8000/"
```

## Without the fix

Without the fix, I got first:

```
Running 10s test @ http://127.0.0.1:8000/
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.40s     2.04s    8.05s    63.64%
    Req/Sec     0.00      0.00     0.00    100.00%
  22 requests in 10.09s, 3.05KB read
Requests/sec:      2.18
Transfer/sec:     309.54B
```

And then the second run I got:

```
Running 10s test @ http://127.0.0.1:8000/
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.00us    0.00us   0.00us    -nan%
    Req/Sec     0.00      0.00     0.00      -nan%
  0 requests in 10.08s, 0.00B read
Requests/sec:      0.00
Transfer/sec:       0.00B
```

...this seems to reflect the deadlock. :tada: (I'm celebrating being able to see something broken, it's sometimes hard to see the broken part :sweat_smile: )

After that, I `Ctrl+C` the Uvicorn process, and it hung in there, at:

```
^C
INFO:     Shutting down
INFO:     Waiting for background tasks to complete. (CTRL+C to force quit)
```

After 7 minutes I force-killed the process. So, indeed, deadlock.

## With the fix, outside

With the fix, putting a single global `CapacityLimiter` outside of the function.

First I got:

```
Running 10s test @ http://127.0.0.1:8000/
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.97s     3.07s   10.02s    67.50%
    Req/Sec     0.00      0.00     0.00    100.00%
  40 requests in 10.09s, 5.55KB read
Requests/sec:      3.96
Transfer/sec:     562.78B
```

For the second run I got:

```
Running 10s test @ http://127.0.0.1:8000/
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     6.31s     2.45s    9.64s    73.08%
    Req/Sec     0.00      0.00     0.00    100.00%
  26 requests in 10.09s, 3.61KB read
Requests/sec:      2.58
Transfer/sec:     365.96B
```

Third run:

```
Running 10s test @ http://127.0.0.1:8000/
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     6.90s     2.76s    9.58s    83.33%
    Req/Sec     0.00      0.00     0.00    100.00%
  12 requests in 10.08s, 1.66KB read
Requests/sec:      1.19
Transfer/sec:     169.06B
```

Not sure why it keeps reducing the number of requests. It seems something would be still wrong, but not sure what. :pensive: 

After that, and after I wrote this, I `Ctrl+C` the Uvicorn process, it finished immediately. So it seems it handled the deadlock.

I ran the whole thing again, and I `Ctrl+C` the Uvicorn process immediately after the 3 runs, and then it waited for a bit at:

```
^C
INFO:     Shutting down
INFO:     Waiting for background tasks to complete. (CTRL+C to force quit)
```

But after 50 seconds it terminated normally.

## With the fix, local

Keeping the local `CapacityLimiter` created every time, as in this PR.

The first run I got:

```
Running 10s test @ http://127.0.0.1:8000/
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.71s     2.90s   10.06s    65.00%
    Req/Sec     0.00      0.00     0.00    100.00%
  40 requests in 10.08s, 5.55KB read
Requests/sec:      3.97
Transfer/sec:     563.34B
```

The second run I got:

```
Running 10s test @ http://127.0.0.1:8000/
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.26s     2.50s    8.48s    80.00%
    Req/Sec     0.00      0.00     0.00    100.00%
  5 requests in 10.09s, 710.00B read
Requests/sec:      0.50
Transfer/sec:      70.37B
```

And the third run I got:

```
Running 10s test @ http://127.0.0.1:8000/
  100 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     5.52s     2.99s    9.27s    50.00%
    Req/Sec     0.00      0.00     0.00    100.00%
  4 requests in 10.10s, 568.00B read
Requests/sec:      0.40
Transfer/sec:      56.25B
```

The results are similar to having a global `CapacityLimiter` than having a local one. The 5 or 4 requests are comparable to some of the other tests I ran with the global `CapacityLimiter`. It's in the same ballpark.

Terminating the process also worked as expected instead of hanging there in a deadlock.

For some reason, it's still being able to handle fewer requests every time. Maybe it's just that it's trying to read the file every time or something like that and there's a bottleneck in that, just in the file system. I'm not sure about that.

---

Checking the AnyIO docs I see that:

> Capacity limiters are like semaphores except that a single borrower (the current task by default) can only hold a single token at a time.

Ref: https://anyio.readthedocs.io/en/stable/synchronization.html

Then I'm not sure if it could be problematic if the same thread worker tried to get the limiter again, and if that could block with the other thing running on the same thread that already got the limiter token.

Until we figure this out, I'll leave the local `CapacityLimiter` (as in this PR) to be safe (although in my local tests it didn't seem to affect, but not sure why).

But anyway, it seems that this clearly improves the situation.

I wish there was a way to test this, in pytest. But not sure how to replicate the whole problem and situation in a feasible way (not involving a whole setup for "benchmarks" with `ab`, Locust, or `wrk`).

For now, I'll merge this, but if anyone has any idea about how this could be tested, to have checks in CI making sure the problem doesn't happen again, it would be awesome.

Thanks @adriangb for all the investigation and work! :bow: :nerd_face: :cake:

**Comment by adriangb** [comment]
> I wish there was a way to test this, in pytest. But not sure how to replicate the whole problem and situation in a feasible way (not involving a whole setup for "benchmarks" with ab, Locust, or wrk)

It might be reproducible by talking pure-ASGI to the FastAPI app and launching multiple tasks using a TaskGroup? Might be hard to get the timing right though.

It might be worth trying to set the capacity limit to float("inf") instead of 1? Could the slowdown come from acquiring database connections? There's likely some semaphore there as well.

**Comment by tiangolo** [comment]
Hehe I was writing this and you commented before me :sweat_smile: 

---

Ah, wait, I didn't read @Kludex comment properly. I didn't realize it could be an inf float. That probably makes sense and we can avoid creating a new object every time.

---

I just di that and updated the branch. :rocket:

**Comment by tiangolo** [comment]
Hehehe the tests have spoken... it seems we need to use the local variable after all. Otherwise AnyIO gets confused with what is the async backend. :joy:

**Comment by Kludex** [comment]
wait

**Comment by adriangb** [comment]
> But I'm not sure how to make it fail instead of hang, if it just hangs it's gonna be more difficult to test

I think anyio.fail_on_after(<some reasonable amount of time>) should do the trick right? But if we were to put this in a test it might be good to figure out how to reproduce it without SQLAlchemy.

**Comment by Kludex** [comment]
> Hehehe the tests have spoken... it seems we need to use the local variable after all. Otherwise AnyIO gets confused with what is the async backend. joy

https://github.com/agronholm/anyio/blob/07b49f76597f353185c825e2acd1b1b9fe274727/src/anyio/_backends/_asyncio.py#L2068

https://anyio.readthedocs.io/en/stable/api.html?highlight=runvar#anyio.lowlevel.RunVar

**Comment by tiangolo** [comment]
@adriangb 

> I think anyio.fail_on_after() should do the trick right? But if we were to put this in a test it might be good to figure out how to reproduce it without SQLAlchemy.

Totally agree with that! That would be great. Not sure how but it would be great indeed.

@Kludex 

Thanks for the links and pointers! (also on Discord)

Copying here for completeness, the issue about `CapacityLimiter`s in Starlette: https://github.com/encode/starlette/issues/1724

The snippet to update the default token size of the default `CapacityLimiter` in https://github.com/encode/starlette/issues/1724#issuecomment-1179063924 and for FastAPI in: https://gist.github.com/Kludex/f889f02bb81adf3a8d63176ad4d8bcb1

---

In conclusion, for now I'll merge this with the local capacity limiter. Maybe at some point Starlette or FastAPI can have a way to customize different capacity limiters for different things (not sure, I haven't thought much about it) and then this could be set there.

And about the option of using a `RunVar` (semi pseudo-contextvar) for a global-loop-local capacity limiter, for now I'll leave the local variable as it's simpler and we can be more certain the implementation works well. The `RunVar` can have a cost involved while dealing with these pseudo-contextvars that might offset the cost of creating the local object in the function. And the implementation would certainly be more complex. So I'll rather keep this one, to be a bit more certain, and avoid the risk of introducing other complex errors (contextvars are my nemesis :joy:).

Thanks again you both for all the help! :bow: :cake:

**Comment by nickswiss** [comment]
This has been closed, but I am not really sure on the final solution as far as running syncronous SQLAlchemy with FastAPI. In my case, I am using FastAPI with SQLAlchemy and Oracle, which does not have a trusted async library. 
If it is possible to use SQLAlchemy synchronously, what is the correct approach?

**Comment by tiangolo** [comment]
@nickswiss I'm not sure I understand the question or if there's something you're not being able to do. If you still have questions or problems, it's probably better to ask in a new GitHub issue, the template will guide you to structure the question in a way that will make it easier to help you, with an example I can run, etc.

**Pull request merged**
