### PR TITLE
🌐 Add German translation for `docs/de/docs/how-to/index.md`

### PR DESCRIPTION
**Pull request by nilslindemann**
← `deployment/docker.md` (#10759)
→ `how-to/general.md` (#10770)

[German translation progress](https://github.com/tiangolo/fastapi/discussions/10582)

### CODE REVIEW

**Comment by nilslindemann** [comment]
@tiangolo It seems that `squidfunk/mkdocs-material-insiders` is now `squidfunk/mkdocs-material` – the author has removed the `-insiders` from the name of the [repository](https://github.com/squidfunk/mkdocs-material). Therefore the tests fail:

```
Collecting git+https://****@github.com/squidfunk/mkdocs-material-insiders.git
  Cloning https://****@github.com/squidfunk/mkdocs-material-insiders.git to /tmp/pip-req-build-wc0ck37j
  Running command git clone --filter=blob:none --quiet 'https://****@github.com/squidfunk/mkdocs-material-insiders.git' /tmp/pip-req-build-wc0ck37j
  fatal: could not read Username for 'https://github.com/': No such device or address
```

**Comment by tiangolo** [comment]
📝 Docs preview for commit 4c661ac2b82b170dec2b071fe1bcf6178b1ac2dc at: https://d4539440.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 2cf3065c6b2c025539007db5d58734905717aa95 at: https://5e54e649.fastapitiangolo.pages.dev

**Comment by nilslindemann** [comment]
@tiangolo the coverage test fails (99% < 100%). The function  `__get_pydantic_core_schema__` in `fastapi/openapi/models.py` [has no coverage](https://smokeshow.helpmanual.io/111m2q3063056h2y290d/d_6de190ce15502a91_models_py.html).

**Comment by tiangolo** [comment]
📝 Docs preview for commit 51e309ad81c1a755985af9c8f8b4122bfbaeb642 at: https://68215d3a.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
Awesome @nilslindemann! :rocket: 

As you are the champion of German translations and you have done so many, and with so much attention to detail, I'm gonna go ahead and merge this. :tada: 

If others see things that could be improved later, we can check that in new PRs. :nerd_face:

**Pull request merged**
