### PR TITLE
feat: add Turkish translation for `docs/tr/docs/alternatives.md`

### PR DESCRIPTION
**Pull request by CoderMungan**
Orginal file: [alternatives](https://github.com/tiangolo/fastapi/blob/master/docs/en/docs/alternatives.md)

[Turkish translations discussions](https://github.com/tiangolo/fastapi/discussions/9193)

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 885298d30e93e3c8820661325f09bccfce73c563 at: https://783b5d4f.fastapitiangolo.pages.dev

**Comment by hasansezertasan** [comment]
Before opening a PR, please read the [Development - Contributing - FastAPI](https://fastapi.tiangolo.com/contributing/#translations).

I'm assuming you didn't read it because of this line.

https://github.com/tiangolo/fastapi/blob/36c26677682c4245183912e00fc057c05cc6cf7a/docs/en/docs/contributing.md?plain=1#L265

Also there is already a PR for `docs/tr/docs/alternatives.md` at #10502 

You can also join "FastAPI Türkiye" discord server, there is a group of people specifically focused on translations. You can find it here: [FastAPI Türkiye](https://hasansezertasan.github.io/fastapi-turkiye/)

**Comment by CoderMungan** [comment]
> Before opening a PR, please read the [Development - Contributing - FastAPI](https://fastapi.tiangolo.com/contributing/#translations).
> 
> I'm assuming you didn't read it because of this line.
> 
> https://github.com/tiangolo/fastapi/blob/36c26677682c4245183912e00fc057c05cc6cf7a/docs/en/docs/contributing.md?plain=1#L265
> 
> Also there is already a PR for `docs/tr/docs/alternatives.md` at #10502
> 
> You can also join "FastAPI Türkiye" discord server, there is a group of people specifically focused on translations. You can find it here: [FastAPI Türkiye](https://hasansezertasan.github.io/fastapi-turkiye/)

I joined your discord channel. I hope to get more detailed information from you, thank you! but I have read the entire documentation. I open the pr one by one in different branches.

**Comment by hasansezertasan** [comment]
> I joined your discord channel. I hope to get more detailed information from you, thank you! but I have read the entire documentation. I open the pr one by one in different branches.

You're most welcome! The server weren't active lately but we are planning to regroup this week.

I referenced that line because your pull request contains two files, am I incorrect? The line I referred to in my latest comment says that you should open a translation pull request per page (meaning per markdown files).

Before anyone reviews your pull request, I highly suggest arrange your latest pull requests, which they share same files.

**Comment by CoderMungan** [comment]
> > I joined your discord channel. I hope to get more detailed information from you, thank you! but I have read the entire documentation. I open the pr one by one in different branches.
> 
> You're most welcome! The server weren't active lately but we are planning to regroup this week.
> 
> I referenced that line because your pull request contains two files, am I incorrect? The line I referred to in my latest comment says that you should open a translation pull request per page (meaning per markdown files).
> 
> Before anyone reviews your pull request, I highly suggest arrange your latest pull requests, which they share same files. In this pr title you are referring to alrernatives.md but it still contains help-fastapi.md, which shouldn't. Please fix that...
> 
> Finally, why we should review this version instead of an older pr that does the same thing? #10502 what was the problem with that and if there were a problem, why didn't you leave a review with change requests? Can yoı see what I'm trying to tell?

Good luck for the translate! I am done! Thank you.

**Comment by hasansezertasan** [comment]
Sorry if I offended you by any means (which there is no reason), I was merely trying to help you.

About discord server, as I said we are regrouping this week but we still don't have a schedule. And there is this deal: I'm not waiting on a "voice channel" to welcome each person who joins the server but I do welcome each person who joins the server "when I get the chance".

I prefer not to reply the rest but keep in mind, communication is the essence.

**Pull request closed without merging**
