### PR TITLE
Hasnatsajid patch 1

### PR DESCRIPTION
**Pull request by hasnatsajid**

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 3ad8f1b340a8df49e7f29a026bc11593e7740b4c at: https://93ec97bb.fastapitiangolo.pages.dev

**Comment by nilslindemann** [comment]
(Accidental?) Duplication of #10498

**Comment by hasnatsajid** [comment]
> Contributor

I made 2 changes actually, not at same time.

**Comment by hasnatsajid** [comment]
> (Accidental?) Duplication of #10498

Yes this one is accidental and correct one is the one you mentioned i.e. #10498

**Comment by nilslindemann** [comment]
So, close this one.

**Comment by hasnatsajid** [comment]
Ok my friend :)

**Pull request closed without merging**
