### PR TITLE
Move all mypy configuration to configuration file

### PR DESCRIPTION
**Pull request by hukkin**
- ~~Remove unused `# type: ignore`s~~
- ~~Make mypy complain about unused `# type: ignore`s~~
- Move all mypy configuration to configuration file (a command line flag was used in `scripts/lint.sh`)

### CODE REVIEW

**Comment by hukkinj1** [comment]
Ah, different Python versions require different `# type: ignore`s it seems. We can either:
- Close this PR
- Make Travis only run mypy with one Python version (I suggest the lowest supported version).

**Review by tiangolo — CHANGES_REQUESTED** [review]
The `ignore`s make it work in both Python 3.6 and 3.7+. And that also makes it better not to have `warn_unused_ignores = True`, or it would complain in one ignores for 3.6 and the others for 3.7.

But I think it's true we could have all the `mypy` configs in a single place instead of file and command line. Could you please remove the other changes and just leave the `disallow_untyped_defs = True` in the `mypy.ini`, and remove it from the command?

**Comment by hukkinj1** [comment]
@tiangolo :+1: done

**Comment by tiangolo** [comment]
Perfect, thank you! :rocket: :wrench:

**Pull request merged**
