### PR TITLE
🌐 Add Yoruba translation for `docs/yo/docs/index.md`

### PR DESCRIPTION
**Pull request by AfolabiOlaoluwa**
This is the Yorùbá translation for the documentation index page. 🎉 🚀

This contribution chooses the [ISO 639-1 Language Code for Yorùbá](https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=yo)

Yorùbá Language is spoken by more than 100 million people and relative amount of them are Software Enginners and they speak the Yorùbá Language perfectly well. It is a a pluricentric language, that is primarily spoken in a dialectal area spanning Nigeria, Benin, and Togo with smaller migrated communities in Brazil, Côte d'Ivoire, Sierra Leone, Gambia, Canada, United Kingdom, and the USA.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit cdf55768e3f6f435cd70b3618a0d19e2aaa96ffb at: https://25125510.fastapitiangolo.pages.dev

**Comment by AfolabiOlaoluwa** [comment]
> 📝 Docs preview for commit [cdf5576](https://github.com/tiangolo/fastapi/commit/cdf55768e3f6f435cd70b3618a0d19e2aaa96ffb) at: https://25125510.fastapitiangolo.pages.dev

Everything looks okay https://25125510.fastapitiangolo.pages.dev/yo/

**Comment by AfolabiOlaoluwa** [comment]
@tiangolo Can you please add labels to this MR?

**Comment by tiangolo** [comment]
Awesome! 🚀

**Comment by tiangolo** [comment]
📝 Docs preview for commit 2c8ee1facab77bbe8069983b6d540f0e88cb088a at: https://f1699f41.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit ae8909ab8ea1e1c977061ca255d17855cbe2d758 at: https://38d5ca66.fastapitiangolo.pages.dev

**Review by bosunogunlana — APPROVED** [review]
👍🏾 awesome work, thanks for doing this

**Comment by tiangolo** [comment]
📝 Docs preview for commit 9a0f973df9de9659b69d6d2f4585ca36343aacf9 at: https://98f961a2.fastapitiangolo.pages.dev

**Comment by AfolabiOlaoluwa** [comment]
> 📝 Docs preview for commit [9a0f973](https://github.com/tiangolo/fastapi/commit/9a0f973df9de9659b69d6d2f4585ca36343aacf9) at: https://98f961a2.fastapitiangolo.pages.dev

The link with the latest correction is https://98f961a2.fastapitiangolo.pages.dev/yo/

**Review by theRealNonso — APPROVED** [review]

**Review by theRealNonso — APPROVED** [review]
Very impactful

**Review by mykeels — APPROVED** [review]

**Comment by tiangolo** [comment]
Awesome, thank you @AfolabiOlaoluwa! 🚀 

And thanks for the reviews @mykeels, @bosunogunlana, @theRealNonso 🙇

**Pull request merged**
