### PR TITLE
🌐 Add Hungarian translation for `docs/hu/docs/async.md`

### PR DESCRIPTION
**Pull request by tcsmaster**

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit b1745f1827f098dde6c2dac86448da4c939efa62 at: https://1e7faefc.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
Great! It would be better to split this into multiple PRs, with one PR per file translated, and removing the files that are not translated.

**Comment by tiangolo** [comment]
📝 Docs preview for commit 9e2dbc3bf971f3fea6ec907bb770b871ffde66e7 at: https://e5ce6519.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 496bc78d4fb7d3f0e6d223a0213de15b49904460 at: https://3f51ebab.fastapitiangolo.pages.dev

**Comment by codespearhead** [comment]
@tcsmaster Are you still willing to have this merged? If so, can you act on the above suggestion?

**Comment by tcsmaster** [comment]
No

**Comment by codespearhead** [comment]
Do you mind closing this issue then?

**Comment by tiangolo** [comment]
@codespearhead thanks for your interest here! But please don't ask people to close PRs if they don't know who would approve them. :nerd_face: 

Instead, something that you could help with a lot would be answering questions from others: https://github.com/tiangolo/fastapi/discussions/categories/questions?discussions_q=is%3Aopen+category%3AQuestions+is%3Aunanswered

**Pull request closed without merging**
