### PR TITLE
🌐 Update Polish translation for `docs/pl/docs/index.md`

### PR DESCRIPTION
**Pull request by isulim**

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit dd0609b46b2671031a7c77b6959cc564ed74c33f at: https://945672f0.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 7e93ff0dceab98ceba9c7354235e7b9c2cd04271 at: https://e813c89d.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 980fa711029989af560317b5950b7a9aae7012cc at: https://f591bfb7.fastapitiangolo.pages.dev

**Review by Mordson — APPROVED** [review]

**Comment by alejsdev** [comment]
Hi @isulim, thanks for the interest and thanks for the review @Mordson :rocket: 
It seems this has conflicts with the latest version, would you be able to fix them so we can merge this? :smile_cat:

**Comment by alejsdev** [comment]
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, you can create a new PR.

**Pull request closed without merging**
