### PR TITLE
📝 Add external link to "FastAPI for Flask Users"

### PR DESCRIPTION
**Pull request by amitness**
I have added a link to my article [FastAPI for Flask Users](https://amitness.com/2020/06/fastapi-vs-flask/) in the external links section of documentation.

### CODE REVIEW

**Review by ycd — CHANGES_REQUESTED** [review]
We do not have an alphabetical order. The order is first-come-first-serve, so to be fair, please add this to the end.

**Comment by amitness** [comment]
@ycd I've migrated it to the end of the list. Should adhere to the FCFS rule now.

**Review by Kludex — APPROVED** [review]

**Review by ycd — APPROVED** [review]

**Review by AdrianDeAnda — APPROVED** [review]

**Comment by amitness** [comment]
@ycd I've fixed the merge conflicts. Can you look into it now?

**Review by ycd — APPROVED** [review]

**Comment by ycd** [comment]
Thanks, actually, you don't have to change the order, since your PR is older than the latest one, FYI.

**Comment by amitness** [comment]
@ycd I've no problems with the ordering. Let's merge it the way it is.

**Comment by tiangolo** [comment]
Thanks @amitness ! Great article! :clap: :clap: 

And thanks @ycd for the help. :bow: :cake:

**Pull request merged**
