### PR TITLE
🌐 Add German translation for `docs/de/docs/reference/fastapi.md`

### PR DESCRIPTION
**Pull request by nilslindemann**
← `how-to/configure-swagger-ui.md` (#10804)
→ `reference/parameters.md` (#10814)

[German translation progress](https://github.com/tiangolo/fastapi/discussions/10582)

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 92862fe41f568384b74eda4210d9e93a881810dc at: https://84122ece.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 4bb24c01dba84300e4f918d0478cdd890c77521b at: https://17169b8c.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 383287eecfc2045bfb5e2432adad957a0504b905 at: https://4decb4d8.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit f720bc8b30fb57e67ee41a6a0e2c0d314b4f02e0 at: https://d910794e.fastapitiangolo.pages.dev

**Review by dpinezich — APPROVED** [review]
Looks good 👍

**Comment by alejsdev** [comment]
Thanks @nilslindemann 🥳 ✨ 

And thanks for the review @dpinezich 🔍🧐

**Comment by nilslindemann** [comment]
Klasse!

**Pull request merged**
