### PR TITLE
🌐  Add Portuguese translation for `docs/pt/docs/advanced/additional-status-codes.md`

### PR DESCRIPTION
**Pull request by ceb10n**

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 9941b380d20c07d1c80dd9c1074dcbea1c1d9070 at: https://819b372c.fastapitiangolo.pages.dev

**Review by Joao-Pedro-P-Holanda — APPROVED** [review]
Great Translation, i would just change "faça a importação" on line 15 with just "importe".

Thanks :)

**Comment by ceb10n** [comment]
> Great Translation, i would just change "faça a importação" on line 15 with just "importe".
> 
> Thanks :)

Done ;)

**Comment by tiangolo** [comment]
📝 Docs preview for commit 79a02c6dc2b8e1ce81afcd7ba8beee56631073df at: https://bc4b7165.fastapitiangolo.pages.dev

**Review by marcelomarkus — APPROVED** [review]

**Comment by alejsdev** [comment]
Thanks for the help! @ceb10n @marcelomarkus @Joao-Pedro-P-Holanda :sunglasses: :100:

**Pull request merged**
