### PR TITLE
Fix GZipMiddleware code block linking to TrustedHostMiddleware

### PR DESCRIPTION
**Pull request by arimbr**
In https://fastapi.tiangolo.com/advanced/middleware/#gzipmiddleware

### **BEFORE**

image

### **AFTER**

image

### CODE REVIEW

**Comment by bilencekic** [comment]
is it possible still wrong ? 
should be starlette.middleware.gzip rather than fastapi.middleware.gzip

**Comment by arimbr** [comment]
@bilencekic based on the content in https://github.com/tiangolo/fastapi/blob/master/fastapi/middleware/gzip.py which imports from `starlette.middleware.gzip` it should work right?

@tiangolo Could you have a look at this. I've seen 4 other PR fixing the same issue ^^

**Comment by bilencekic** [comment]
@arimbr  yes correct it is working i am using like that but documentation has changed to
`from fastapi.middleware.trustedhost import TrustedHostMiddleware`
i think GZIP is also embedded to this middleware now.

**Comment by arimbr** [comment]
Right! Thanks, It is just syntactic sugar introduced in https://github.com/tiangolo/fastapi/pull/1064 where this issue was also introduced.

**Comment by tiangolo** [comment]
Great, thank you @arimbr ! :mag: :male_detective: :cake: :rocket: 

And thanks for the discussion here everyone :clap: :cake: :coffee:

**Pull request merged**
