### PR TITLE
✏️ Fix typos in data for tests

### PR DESCRIPTION
**Pull request by ryanrussell**

### CODE REVIEW

**Review by yezz123 — APPROVED** [review]

**Review by hafidzwibowo — APPROVED** [review]

**Review by nurettn — APPROVED** [review]

**Review by MrRawbin — APPROVED** [review]

**Review by arthurarty — APPROVED** [review]

**Review by iudeen — APPROVED** [review]
Good one!

**Review by Ryandaydev — COMMENTED** [review]
The changes look correct, but the branch the changes are in has errors running the tests when I check it out. So I can't give it a clean review.

**Comment by iudeen** [comment]
@Ryandaydev it'd be great if you can list out the errors. I see the GitHub checks have passed for this PR.

**Comment by Ryandaydev** [comment]
When I use gh checkout 4958, it looks the ryanrussell/master branch. In that branch, it looks like the test-cov-html.sh file is an old version an argument that isn't in the main branch version.

So I can't run the test coverage script to get a clean test run.

Here is the error:
`pytest: error: unrecognized arguments: --cov=fastapi --cov=tests --cov=docs_src --cov-report=term-missing:skip-covered --cov-report=xml --cov-report=html`

**Comment by iudeen** [comment]
@Ryandaydev I checked from local, it works fine. 
```
1346 passed in 21.79s
```
Ensure you have installed all the dependencies needed. 

```
pip install -e ."[dev,doc,test]" --upgrade
```

Then run:

```
coverage run -m pytest tests
```

**Comment by Ryandaydev** [comment]
Thanks, the update resolved my issue. No objections now -- I'll mark it as approve.

**Review by Ryandaydev — APPROVED** [review]
Minor change looks good. Tests ran successfully.

**Review by JakeWalker23 — APPROVED** [review]

**Review by Kludex — APPROVED** [review]

**Pull request merged**
