### PR TITLE
FIX: #894

### PR DESCRIPTION
**Pull request by l3str4nge**
My proposition for #894 --> mark model as cloned. 
In case when it's not enough perhaps it will be good base for main solution :)

### CODE REVIEW

**Comment by jmagnusson** [comment]
This PR fixed issue #894 for me. Thanks @mateuszz0000!

Perhaps a unit test would be good here so that the regression is not re-introduced again. (Could be based off of the code example in #894.

@tiangolo Any chance we could get this merged and released if the code looks good to you? I've been stuck at 0.46 for a while now and would love to take advantage of all the niceties in the newer versions!

**Comment by jmagnusson** [comment]
@mateuszz0000 Looks like you need to format `fastapi/utils.py` with black to get the CI job to pass

**Comment by mateuszz0000** [comment]
Looks like it's something wrong in my solution. How about #1164 created by @voegtlel.

**Comment by jmagnusson** [comment]
@mateuszz0000 Gotcha. #1164 works fine as well.

**Comment by tiangolo** [comment]
Thanks for your contribution @mateuszz0000 :rocket: :cake: 

I used the implementation in #1164 , so I'll close this one now.

And thanks for the discussion here everyone! :coffee:

**Comment by jmagnusson** [comment]
@mateuszz0000 What was this something that was wrong with your solution? It still seems to work fine for me.

**Pull request closed without merging**
