### PR TITLE
🌐 Add Chinese translation for `docs/zh/docs/advanced/templates.md`

### PR DESCRIPTION
**Pull request by meowrain**
🌐 Add Chinese translation for `docs/zh/docs/advanced/templates.md`

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit f2c5b249605b0eaefbea9681eaf69808d981d5f3 at: https://d279b679.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 1db3c304bf36b33910518e2df37b5ac5aacfad78 at: https://d7c77329.fastapitiangolo.pages.dev

**Comment by codespearhead** [comment]
Do you happen to know three Chinese developers that you can ask a [PR review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) from? [This](https://github.com/tiangolo/fastapi/pulls?q=is%3Apr+chinese) might help.

**Comment by tiangolo** [comment]
It seems this was handled in another PR, so I'll pass on this one, but thanks for the effort @meowrain! :coffee:

**Pull request closed without merging**
