### PR TITLE
🌐 Add Spanish translation for `docs/es/docs/fastapi-people.md`

### PR DESCRIPTION
**Pull request by pablocm83**
This is the Spanish translation for the people page.

Add Spanish translation for docs/es/docs/fastapi-people.md
- Version >= 0.108.0

### CODE REVIEW

**Comment by JonanOribe** [comment]
Looks good to me (I'm a native Spanish speaker)

**Comment by alejsdev** [comment]
Hi, thanks for the help @pablocm83 🤓 

I noticed that most of the internal links don't work because those files haven't been translated yet. There's a new section in Contributing that includes some tips for translation (https://fastapi.tiangolo.com/contributing/#translation-specific-tips-and-guidelines). I hope this helps. Thanks!

**Comment by tiangolo** [comment]
📝 Docs preview for commit 3eb04260c2dfe6a621dbe163f9697efb157002fa at: https://aad0db50.fastapitiangolo.pages.dev

**Comment by pablocm83** [comment]
@alejsdev internal links ready.

thanks

**Comment by tiangolo** [comment]
📝 Docs preview for commit b4c8ba1c79559a33e1a8025d0e5f7f88f15441f3 at: https://c9476a29.fastapitiangolo.pages.dev

**Pull request closed without merging**
