### PR TITLE
📝 Update `docs_src/path_params_numeric_validations/tutorial006.py`

### PR DESCRIPTION
**Pull request by MuhammadAshiqAmeer**
The size parameter was not appended into the results.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 4254b2cfe5e8589bd396a38c5c5da2e879daa539 at: https://dcbd9b93.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 83684dfb1519c0664e8900607eb5c185d42c28fe at: https://7abfa613.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit e31090dec27ecf0b4b0e9ed43fd6e6d3d9f1fb01 at: https://9d7f0a09.fastapitiangolo.pages.dev

**Review by svlandeg — APPROVED** [review]
Thanks for the PR!

Adding the `size` parameter to the `results` makes sense because then at least the body of the function is doing _something_ with this value. Mostly this part of the tutorial is about using the `gt` and `lt` annotations in `Query`, so it doesn't matter much either way, but this edit doesn't hurt 🙂 

Thanks again!

**Comment by tiangolo** [comment]
Cool, thanks @MuhammadAshiqAmeer! :coffee: 

And thanks @svlandeg :cake:

**Comment by MuhammadAshiqAmeer** [comment]
@svlandeg , @tiangolo  Thanks and looking forward to contribute more : )

**Pull request merged**
