### PR TITLE
📝 Add hide-navi-boxes

### PR DESCRIPTION
**Pull request by nilslindemann**
(I will recreate this in a later PR)

These were recently added to the English docs.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 0fd5ce5c68493237b84ec913c3304a622e34f7aa at: https://bf760a3c.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit f931485b0c83a38aac2a98b704f7a10253ffdda3 at: https://e95e3698.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit b031a4d2e55a305da246b3f0ab4df971160a9d95 at: https://7849e81e.fastapitiangolo.pages.dev

**Comment by nilslindemann** [comment]
I have deleted my work branch on GitHub, as GitHubs linking mechanism is awkward. See the five links above, which should all not be there in my opinion, as these are tangling commits (they actually do not exist anymore in my local clone).

**Pull request closed without merging**
