### PR TITLE
🌐 Add Korean translation for `docs/ko/docs/tutorial/schema-extra-example.md`

### PR DESCRIPTION
**Pull request by SueNaEunYang**
Hello, 
I added a translation of this part of the tutorial.
I would be grateful if you take a look if I had made any mistakes or mistranslations.
Please feel free to tell me if there's something to be improved.
Thank you.

This PR translates `tutorial/schema-extra-example.md` in Korean.
related: #2017

### CODE REVIEW

**Review by tiangolo — CHANGES_REQUESTED** [review]
Awesome! Thank you! :bow: 

There's a new file at `docs/ko/docs/img/tutorial/body-fields/image01.png`

You should be able to use the same example images for the English version, that way it's not necessary to duplicate the files.

The way the `` HTML tag is written already takes advantage of this, so you can just remove that file. :nerd_face:

**Comment by SueNaEunYang** [comment]
@tiangolo 
Hello, thank you for your review.
I removed the image file right away :)

**Comment by 0417taehyun** [comment]
Can you update (fetch) this document to the latest version? Because some of sentences are deprecated.

**Comment by alejsdev** [comment]
Thank you for your contribution @SueNaEunYang 🚀 

However, we have decided to close this pull request as another one (https://github.com/tiangolo/fastapi/pull/11121), which includes more recent updates, has already been merged. We appreciate your effort and encourage you to continue contributing in the future. Please feel free to check out the other open issues and PRs. Thanks! 🤓

**Pull request closed without merging**
