### PR TITLE
🌐 Add Korean translation for `docs/ko/docs/contributing.md`

### PR DESCRIPTION
**Pull request by kimjaeyoonn**
This PR translates contribuing.md in Korean.

I understand it as a request to divide a branch, and divide the Branch and post a PR again.
Thank You, I look forward to your feedback.

related: #2017

### CODE REVIEW

**Review by 0417taehyun — COMMENTED** [review]
I think writing english words less would be better, like `python`, `markdown` and some headers  and tip part are not translated yet. So please check my reviews.

Little bit hard to check the all of the sentences, words, etc. carefully. So, I'm in progress to check and share my opinion, and also those are not the answers. Just free to check mine 🚀

**Comment by kimjaeyoonn** [comment]
@tiangolo  

This PR document has been modified and uploaded again in #4143, so please check it and merge it.

**Comment by DevDae** [comment]
> @tiangolo
> 
> This PR document has been modified and uploaded again in #4143, so please check it and merge it.

I just have reviewed this PR now.
It doesn't have any flaw! 🚀 Please check our reviews 🙏

**Review by kty4119 — APPROVED** [review]

**Comment by tiangolo** [comment]
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

**Pull request closed without merging**
