### PR TITLE
Fix overlapping menu item in the docs

### PR DESCRIPTION
**Pull request by asheux**
- Before the fix
before
- After the fix
after

### CODE REVIEW

**Comment by tiangolo** [comment]
Hmm, this is strange, I can't reproduce the issue, I tried on different sizes but it seems to work correctly.

What browser are you using? Have you tried on an incognito window?

Selection_067

**Comment by asheux** [comment]
I'm using Firefox and the issues is still there in incognito. See attached.
incognito

**Comment by asheux** [comment]
I just tested on Chrome as well, seems ok. 
Tested my changes on both browsers. Perhaps, with the introduction of these changes, it should be fine on both browsers.

**Comment by tiangolo** [comment]
Thanks @asheux ! I wasn't able to reproduce the problem in an incognito window in Firefox, so I think it might be related to something in your environment.

So I'll close this now, but thanks for your effort! :coffee: :cake:

**Pull request closed without merging**
