### PR TITLE
🌐 Add Portuguese translation for `docs/pt/docs/advanced/security/index.md`

### PR DESCRIPTION
**Pull request by ceb10n**

### CODE REVIEW

**Comment by ceb10n** [comment]
I didn't understand why the checks failed. It doesn't seem to be related with the translation itself. @alejsdev do you have an idea why it failed?

It failed at `coverage-combine`:

```shell
Run ls -la coverage
ls: cannot access 'coverage': No such file or directory
Error: Process completed with exit code 2.
```

**Comment by alejsdev** [comment]
It seems it's something related to coverage :thinking: 
We're aware of this and we'll fix it soon. Thanks! @ceb10n

**Review by nazarepiedady — APPROVED** [review]

**Comment by alejsdev** [comment]
Nice, thanks for the contribution! @ceb10n @nazarepiedady :tada:

**Comment by ceb10n** [comment]
btw, I used this PR to write an article about helping with translations. If someone wants to check it out, here's the link: https://dev.to/ceb10n/helping-fastapi-how-to-contribute-to-docs-translations-44a7 😄

**Comment by svlandeg** [comment]
That's a great article! 😍

**Comment by tiangolo** [comment]
Great article! :star_struck:  I just shared it on Twitter and LinkedIn. :nerd_face: :rocket:

**Comment by nazarepiedady** [comment]
> btw, I used this PR to write an article about helping with translations. If someone wants to check it out, here's the link: https://dev.to/ceb10n/helping-fastapi-how-to-contribute-to-docs-translations-44a7 😄 

Excellent brother, you did excellent work spreading the word.

**Pull request merged**
