### PR TITLE
✏️ Fix validation parameter name in docs, from `regex` to `pattern`

### PR DESCRIPTION
**Pull request by pablodorrio**
Currently the document states:

> Validations specific for strings:
> 
> - `min_length`
> - `max_length`
>-  `regex`

But the parameter regex is deprecated so I change `regex` to `pattern`:

> Validations specific for strings:
> 
> - `min_length`
> - `max_length`
>-  `pattern`

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 1b02e5c8ac43738f04d500b8aefc72b6f2de40cf at: https://888ad06d.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 5f2b470a6f776426a5a70cfbc911c872dde755ee at: https://c3aa6f6b.fastapitiangolo.pages.dev

**Review by iudeen — APPROVED** [review]

**Comment by iudeen** [comment]
Just to add more context: this PR aims to correct the documentation to align to the recent changes that Pydantic V2 has gone through.

Ref: https://docs.pydantic.dev/2.0/migration/#changes-to-pydanticfield

**Comment by tiangolo** [comment]
Good catch, thanks @pablodorrio! 🚀

**Pull request merged**
