### PR TITLE
🌐 Add Turkish translation for `docs/tr/docs/resources/index.md`

### PR DESCRIPTION
**Pull request by hasansezertasan**
🌐 Add Turkish translation for `docs/tr/docs/resources/index.md`

[Original File](https://github.com/tiangolo/fastapi/blob/master/docs/en/docs/resources/index.md)

Discussion: #9193

### CODE REVIEW

**Comment by hasansezertasan** [comment]
@alperiox, @OzgunCaglarArslan @SametEmin, @mertssmnoglu, can you please leave a review?

**Comment by tiangolo** [comment]
📝 Docs preview for commit 00422cc4968a87cc4b79c693a37681e7bdf2b960 at: https://464d749f.fastapitiangolo.pages.dev

**Review by OzgunCaglarArslan — APPROVED** [review]

**Comment by hasansezertasan** [comment]
Thank you @OzgunCaglarArslan for the review!

**Review by alperiox — APPROVED** [review]

**Comment by alejsdev** [comment]
Thanks for your contribution! @hasansezertasan 🤓💯 

And thanks for the reviews @OzgunCaglarArslan and @alperiox 🚀✨

**Pull request merged**
