### PR TITLE
Add default parameter for Router path parameter

### PR DESCRIPTION
**Pull request by uriyyo**
Add default parameter to the Router `path` parameter.

Code like this:
```python
@router.get("", response_model=Item)
def route():
    ...
```
Can be rewritten to:
```python
@router.get(response_model=Item)
def route():
    ...
```

In case when call to `router` method doesn't have any arguments than a parenthesis can be skipped:
```python
@router.get
def route():
    ...
```

### CODE REVIEW

**Comment by ssw99** [comment]
Wouldn't it be better if you just give default value to path parameter of router?

**Comment by uriyyo** [comment]
@ssw99 You mean to leave only the default parameter for path and remove the ability to use router functions as decorator without parameters?

**Comment by ssw99** [comment]
What i mean is, rather than passing None as default value to router functions and checking if it is None, we can just pass empty string as default value.

**Comment by uriyyo** [comment]
> What i mean is, rather than passing None as default value to router functions and checking if it is None, we can just pass empty string as default value.

It won't work with root `APIRouter`, because the root router should start with `/`. Correct me if I miss smth.

**Comment by tiangolo** [comment]
Thanks for the interest @uriyyo ! :coffee: 

But I would actually prefer to leave it as is and have it more explicit. I feel it could end up being too magical and could be confusing.

Also, having support for:

```Python
@router.get("", response_model=Item)
def route():
    ...
```

is only to add support for those edge cases, but is actually discouraged. I would prefer not to add more magic to that.

So I'll pass on this one. But thanks for the effort! :cake:

**Pull request closed without merging**
