### PR TITLE
✨ Allow custom middlewares to raise `HTTPException`s and propagate them

### PR DESCRIPTION
**Pull request by ghandic**
When trying to build a custom middleware that checks content size any exceptions raised by the middleware don't get propagated back up. By allowing any HTTPExceptions to be raised as they are we can raise custom exception information into the response

Screenshot 2020-09-11 at 18 20 03

### CODE REVIEW

**Comment by ghandic** [comment]
I've tried to find how to get test coverage for this, but cant find where the tests are for the other exceptions being raised, if someone could point me to that I can add in tests

**Comment by ghandic** [comment]
Squashed my commits into one

**Comment by ghandic** [comment]
@tiangolo this was the main PR I was requesting, the other one I just thought I had found an issue to fix while working on this. Any thoughts on this one?

**Comment by ghandic** [comment]
@tiangolo any updates on getting this merged?

**Review by ghandic — COMMENTED** [review]
This has been pending for 6 months... any update?

**Review by ycd — APPROVED** [review]

**Comment by ghandic** [comment]
Any updates?

**Comment by ghandic** [comment]
@tiangolo is there anything I can do to help this PR over the line?

**Comment by tiangolo** [comment]
Great, thanks @ghandic! :rocket:

**Pull request merged**
