### PR TITLE
consider using `any`

### PR DESCRIPTION
**Pull request by gitworkflows**
These changes improve the function's ability to correctly identify sequence types in various annotations.

### CODE REVIEW

**Comment by tiangolo** [comment]
Hello @gitworkflows, this seems like an automated change. Are you a bot? I would prefer you not to do automated PRs. In particular without explanation about why you suggest the change, etc.

**Comment by jamescrowley321** [comment]
@gitworkflows It looks like you belong to https://github.com/CVELab, and so the assumption is that this should solve some sort of CVE. How does this code make FastApi more secure?

**Comment by davidlougheed** [comment]
@jamescrowley321 I don't think this is a real organization; e.g., the text from their `advisories` repo is copy-pasted and changed from another, real repository: https://github.com/oasis-open/cti-training 

I think this is from a network of bots/some kind of weird social engineering attempt; they've also copy-pasted FastAPI and changed the copyright to another organization elsewhere: https://github.com/readyapi/readyapi which is obviously not a correct fork, because copyright of previous code should be kept by the original FastAPI authors. 

comically, on that page, they've also included the FastAPI testimonials but with the name changed! I've reported this account and repo, and I suggest that their pull requests here are discarded.

**Comment by gitworkflows** [comment]
> Hello @tiangolo,thanks for your feedback. I know it might look like a bot made this change, but I'm a real person who made it manually.
I changed the code to use Any so the function can work with different types of sequences. This makes the code more flexible and helps prevent errors.
If you want to know more about why I made this change, just ask. I'm happy to explain it in more detail. Thanks for reviewing my pull request!"

**Comment by gitworkflows** [comment]
> Hello @gitworkflows, this seems like an automated change. Are you a bot? I would prefer you not to do automated PRs. In particular without explanation about why you suggest the change, etc.

Hello @tiangolo,thanks for your feedback. I know it might look like a bot made this change, but I'm a real person who made it manually.
I changed the code to use Any so the function can work with different types of sequences. This makes the code more flexible and helps prevent errors.
If you want to know more about why I made this change, just ask. I'm happy to explain it in more detail. Thanks for reviewing my pull request!"

**Comment by tiangolo** [comment]
@gitworkflows I would ask you to please restrain from making further PRs in this repo, unless you find an actual bug with an issue reported and a very detailed description of the process and why you would do it.

For now, I will close your PRs without reviewing much unless it is about an actual issue, an actual feature request, with a very detailed description and an explanation for the use case.

**Pull request closed without merging**
