### PR TITLE
🙈 Add .coverage* to `.gitignore`

### PR DESCRIPTION
**Pull request by gitworkflows**

### CODE REVIEW

**Comment by Kludex** [comment]
Is the project generating anything other than `.coverage`?

**Review by svlandeg — COMMENTED** [review]
Hi @gitworkflows, thanks for the PR! 

<s>The change in this PR doesn't seem necessary to me though, so I'm not actually sure we should merge it.</s>

**Comment by killjoy1221** [comment]
`.coverage*` files are being created when running coverage locally. It's because coverage is configured with
https://github.com/fastapi/fastapi/blob/75705617a66300847436e39ba703af1b8d109963/pyproject.toml#L177-L178

The proper way to handle these files is to run `coverage combine` after running the tests.

**Comment by tiangolo** [comment]
Thanks! :cake: :coffee:

**Pull request merged**
