### PR TITLE
create async sql tutorial001 for python3.10

### PR DESCRIPTION
**Pull request by SXHRYU**
replaced `typing.List` with `list`

### CODE REVIEW

**Review by lpdswing — APPROVED** [review]

**Comment by tiangolo** [comment]
📝 Docs preview for commit 29695a7a2420bf639f393d203fa4659fc5074181 at: https://0c071d84.fastapitiangolo.pages.dev

**Comment by rafalkrupinski** [comment]
`import databases`?

Is it possible to use standard `sqlalchemy.ext.asyncio`?

**Comment by alejsdev** [comment]
Hi @SXHRYU, thanks for your interest and patience, we already reviewed your PR but it seems this section (https://fastapi.tiangolo.com/how-to/async-sql-encode-databases/) is deprecated now, so I'll leave the final decision to @tiangolo. 🤔

**Comment by tiangolo** [comment]
Thanks for the interest! :coffee: 

I wanted to re-write the SQL docs with SQLModel, I just finished that here: https://github.com/fastapi/fastapi/pull/12285

The new docs are here: https://fastapi.tiangolo.com/tutorial/sql-databases/

I also plan on adding support and docs for working with async code with SQLModel, and then I'll update the docs here.

Given that, I'll pass on this one, but thanks for the effort! :cake:

**Pull request closed without merging**
