### PR TITLE
Update docs_src/body_fields with more Annotated in one place where it should be

### PR DESCRIPTION
**Pull request by Forelyl**
Tutorial, File: 001_an_py310.py

We can also use Annotated for fields in BaseModel 

I am not going to add this to other python versions, because I haven't checked if everything is working nicely for older versions

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 8bdcf2ea5acdf0c27eebad2a75e4edb57031b5ea at: https://af00241c.fastapitiangolo.pages.dev

**Comment by Forelyl** [comment]
There also should be a change body-fields.md
(it is seen in raw mode, the hl_lines is been changed)

Before:
```Python hl_lines="11-14"
{!> ../../../docs_src/body_fields/tutorial001_an_py310.py!}
```

After
```Python hl_lines="11-16"
{!> ../../../docs_src/body_fields/tutorial001_an_py310.py!}
```

(sorry don't see a way to add this change to current pull request)

**Comment by Forelyl** [comment]
This Annotation could be also added to the lessons:

-  [Declare Request Example Data](https://fastapi.tiangolo.com/tutorial/schema-extra-example/)

**Comment by tiangolo** [comment]
Thanks for the interest! :nerd_face: 

Yeah, I know this would be viable, but it's less obvious when it's done in Pydantic models as they have the custom dataclass-like behavior. They are very similar. And dataclasses don't support `Annotated` (yet). Probably for that reason, Pydantic uses the old syntax in most of their docs. So, for the Pydantic models, I'll leave them as is for now. But thanks for the interest! :coffee:

**Pull request closed without merging**
