### PR TITLE
📝 Replace `email` with `username` in `docs_src/security/tutorial007` code examples

### PR DESCRIPTION
**Pull request by nilslindemann**
Just stumbled over this while translating the chapter.

#10651 is a translation of this.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 1de738dbc0c3070235b468fdfffe22b564e26c87 at: https://6347b79f.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 04bb8d5acad8ee534bf77c287b3c57c2d099585a at: https://047f5a26.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit f8e6dab434910f5a9526d8131e473340423bdd44 at: https://dd832df3.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 6bfed486f41095c616747489a5ccbd714edd2b11 at: https://48dbbb4c.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit daa6056cdd5f2f91103f8951d141125d883c5fa1 at: https://8c03070e.fastapitiangolo.pages.dev

**Review by alejsdev — APPROVED** [review]

**Comment by alejsdev** [comment]
Good catch! Thanks @nilslindemann 🐱

**Pull request merged**
