### PR TITLE
✏️ Update Pydantic links to dotenv support

### PR DESCRIPTION
**Pull request by White-Mask**
🌐 Update the Pydantic documentation link (dotenv-env-support) for:
* docs/em/advanced/settings.md
* docs/zh/advanced/settings.md
* docs/en/advanced/settings.md

Discussion: https://github.com/tiangolo/fastapi/discussions/10508

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 1c451b0cd05862c9218da60548ea156bc4cbfcb6 at: https://ddf09f5a.fastapitiangolo.pages.dev

**Comment by ladmol** [comment]
Everything works correctly in the preview, the link is fixed. Thank you for your cooperation, @White-Mask

**Comment by tiangolo** [comment]
📝 Docs preview for commit 7146ddc0ea12ec27f0a44a150e3eb381645f3419 at: https://e2808fe8.fastapitiangolo.pages.dev

**Comment by White-Mask** [comment]
@tiangolo In the preview, everything is working correctly 👍

**Comment by tiangolo** [comment]
📝 Docs preview for commit 934d0b690b785d96dc194c99f971b677001674f6 at: https://8496d69b.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
Great, thank you @White-Mask! 🚀

**Pull request merged**
