### PR TITLE
python 3.12

### PR DESCRIPTION
**Pull request by raphaelauv**

### CODE REVIEW

**Comment by raphaelauv** [comment]
https://github.com/python-greenlet/greenlet/issues/323

**Comment by tiangolo** [comment]
📝 Docs preview for commit 029f0aec3fc34ebdaeaaad8b5cb57740a7de7c46 at: https://649414541e30800746194c0b--fastapi.netlify.app

**Comment by tiangolo** [comment]
📝 Docs preview for commit a3be4cf22d32cbd927da9ebde43108669a411e31 at: https://649415ae25564107cf165448--fastapi.netlify.app

**Comment by raphaelauv** [comment]
`sqlalchemy` start python 3.12 compatibility from version `2.0.16`

but `databases` is not sqlalchemy 2 compatible -> https://github.com/encode/databases/issues/530

that mean if fastapi add python 3.12 support it must drop `databases` package

**Comment by tiangolo** [comment]
📝 Docs preview for commit 06b06d6b57b8aa12ee9bf534fb585675268a1149 at: https://649418e514ff950a2a9b4e9f--fastapi.netlify.app

**Comment by raphaelauv** [comment]
https://github.com/tiangolo/fastapi/pull/9687

**Comment by tiangolo** [comment]
📝 Docs preview for commit 338c083a5d3745f2b741e271c01de6ea173971d0 at: https://799f420a.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 4be1c1ecf28b530e1afe0f9d3e346fafa44aade3 at: https://14c8e365.fastapitiangolo.pages.dev

**Comment by raphaelauv** [comment]
all fastapi tests work with pydantic v1 and python 3.12

https://github.com/tiangolo/fastapi/actions/runs/6306478779/job/17121687483

**Pull request closed without merging**
