### PR TITLE
🐛 Close FormData (uploaded files) after the request is done

### PR DESCRIPTION
**Pull request by adriangb**

### CODE REVIEW

**Comment by adriangb** [comment]
Looks like failures are unrelated to this change: https://github.com/tiangolo/fastapi/pull/5467

**Comment by adriangb** [comment]
Failures resolved,  @tiangolo I think this is ready for review :)

**Review by yezz123 — APPROVED** [review]

**Review by iudeen — APPROVED** [review]

**Comment by tiangolo** [comment]
Amazing, thank you @adriangb! :bow: 

Do you think you could add a test or two for this?

**Comment by adriangb** [comment]
I think this might difficult to test without touching the internals of something. It does run for every test, so we know that it doesn’t crash at least. I’ll think a bit about how to test this.

**Comment by adriangb** [comment]
So it seems like even Starlette is not testing that `UploadFile.close` gets called. I don't see any way to test this other than doing some monkey patching of stuff like that. @tiangolo would you accept this without a test or is that a no-go?

**Comment by tiangolo** [comment]
I found a way to test it! :tada: I added the commit on top.

Thanks for the contribution! :rocket:

**Comment by adriangb** [comment]
That was genius!

**Comment by tiangolo** [comment]
Haha thank you! 😊🙈😬

**Pull request merged**
