### PR TITLE
📝 Update docs with pip install calls when using extras with brackets, use quotes for compatibility with Zsh

### PR DESCRIPTION
**Pull request by tomwei7**
Square brackets in zsh have special meanings. Copy and run `pip install uvicorn[standard]` in zsh will get error.

### CODE REVIEW

**Comment by Kludex** [comment]
It will not.

**Comment by waynerv** [comment]
I had this problem before and now I finally know how to solve it.zsh uses [square brackets for globbing / pattern matching](http://zsh.sourceforge.net/Guide/zshguide05.html#l137).

I've never seen it (add quotation mark) in any other documentation, but add a notice about this problem should be nice.

**Comment by tomwei7** [comment]
@waynerv [python-language-server](https://github.com/palantir/python-language-server)  add quotation mark on install command `pip install 'python-language-server[yapf]'` in its documentation

**Comment by Kludex** [comment]
Just adding the quotes as @tomarv2 suggested seems fine.

Why I don't have this problem here tho? :sweat_smile:

**Comment by tomwei7** [comment]
run `zsh -f` start zsh without any config that can reproduce the problem. `setopt nonomatch` in zsh will avoid this problem.

**Review by Kludex — APPROVED** [review]
I see... Ok. :)

**Review by waynerv — APPROVED** [review]

**Comment by tiangolo** [comment]
Thanks @tomwei7! :cake: 

I updated it to include all the other calls of `pip install` that were using packages with extras.

**Pull request merged**
