### PR TITLE
🌐 Fix Korean translation for `docs/ko/docs/index.md`

### PR DESCRIPTION
**Pull request by choi-haram**
This modification corrects the spelling of '수박 겉핡기' to '수박 겉 핥기' in the Korean documentation. It enhances clarity and aligns with the standard linguistic practices.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit a63409b7c7f95e28133ef1927b439405d62f60bb at: https://2f083651.fastapitiangolo.pages.dev

**Comment by choi-haram** [comment]
According to 'https://fastapi.tiangolo.com/contributing/', it states that 'The contents within the code block (```) should remain unchanged except for the comments.' Does this mean that the content I committed should also not be modified?

**Comment by kitrio** [comment]
Good

**Review by junah201 — APPROVED** [review]

**Comment by alejsdev** [comment]
Thanks for the contribution! @choi-haram @junah201 🤓☕

**Pull request merged**
