### PR TITLE
♻ Instantiate `HTTPException` only when needed, optimization refactor

### PR DESCRIPTION
**Pull request by pawamoy**
Hello, just noticed this while debugging something.

If we enter the condition `if not authorization or scheme.lower() != "basic"`, the instance of HTTPException happens to be unused.
I moved it lower to avoid instantiating it without using it.

### CODE REVIEW

**Review by mbroton — APPROVED** [review]
LGTM :+1:

**Review by BilalAlpaslan — APPROVED** [review]

**Review by iudeen — APPROVED** [review]
Nice!

**Review by JarroVGIT — APPROVED** [review]
LGTM, nice catch!

**Review by yezz123 — APPROVED** [review]

**Review by stlucasgarcia — APPROVED** [review]

**Review by yezz123 — APPROVED** [review]

**Comment by tiangolo** [comment]
Great, thank you! :rocket: 

And thanks everyone for the reviews. 🤓

**Pull request merged**
