### PR TITLE
✨ Add `SimpleJSONResponse` for decimal JSON encoding

### PR DESCRIPTION
**Pull request by tomy0000000**
As mentioned in [#4998](https://github.com/tiangolo/fastapi/issues/4998#issuecomment-1150242750). I believe `simplejson` is the best option to accomplish high decimal points real number encoding, hence the need of `SimpleJSONResponse`. I followed some of the parameters used in `starlette`'s original `JSONResponse` [here](https://github.com/encode/starlette/blob/master/starlette/responses.py#L195-L201) to make sure the output are the most consistent as possible.

If interested, I'm also willing to draft a page of doc detailing the best practice of handling decimal in FastAPI I've come up so far. Just let me know if that's something you'd like to include.

### CODE REVIEW

**Comment by odiseo0** [comment]
Maybe you can make some tests and write some docs too

**Review by yezz123 — APPROVED** [review]

**Comment by tomy0000000** [comment]
Hi folks,

as suggested, I've written a page detailing on how to make use of `simpleJSONResponse` and also some tips on how to make `Decimal` works with FastAPI.

Feedbacks are welcomed 👍🏻

**Review by odiseo0 — CHANGES_REQUESTED** [review]
`media_type = "application/json"` is not necessary and also you need to write tests

**Review by odiseo0 — APPROVED** [review]
LGTM

**Comment by theRealSuperMario** [comment]
I could really use this ASAP. Any chance this will get merged soon?

**Comment by tomy0000000** [comment]
@tiangolo Would you mind taking a minute to review this? Docs and tests ready, reviewed by others.

**Comment by nishaalnaseer** [comment]
Can i get a link to the doc? I need some help where Decimals need to serialize as JSON numbers with trailing zeroes intact.

**Pull request closed without merging**
