### PR TITLE
🌐 Add Portuguese translation for `docs/pt/docs/reference/openapi`

### PR DESCRIPTION
**Pull request by marcelomarkus**
- Portuguese translation
docs/pt/docs/reference/openapi/docs.md
docs/pt/docs/reference/openapi/index.md
docs/pt/docs/reference/openapi/models.md

### CODE REVIEW

**Review by ceb10n — APPROVED** [review]
❇️

**Review by cassiobotaro — APPROVED** [review]

**Comment by tiangolo** [comment]
Thank you for your contribution! :bow: 

I recently realized that there are some sections where the benefit of translating them has a tradeoff with the content... for example, the content of the reference is injected from the source files, and most of the content in that section ends up being in English either way... and then there's a chance that if the reference is updated including other objects to be injected, the translation would be obsolete. :pensive: 

So I decided not to translate some sections, including the reference. https://fastapi.tiangolo.com/contributing/#dont-translate-these-pages

---

I see this PR includes a translation for `bigger-applications.md`. That one would be great. Is that part of another PR already? Should we close this one or make it only about that file?

Thank you! :cake:

**Comment by alejsdev** [comment]
The one for `bigger-applications` has been just merged :smile: @tiangolo

**Comment by tiangolo** [comment]
Ah, just saw that @alejsdev merged one for `bigger-applications.md` :sunglasses: 

So I'm gonna close this one now. Thank you! :cake: :coffee:

**Pull request closed without merging**
