### PR TITLE
🌐 Add German translation for introduction documents

### PR DESCRIPTION
**Pull request by nilslindemann**
To have the links in the top bar translated.

All-in-one commit, as these are very short documents.

[German translation progress](https://github.com/tiangolo/fastapi/discussions/10582)

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 8b4eeac0883e56ffd13e1e04ad9520c5e80c71ba at: https://5930da0a.fastapitiangolo.pages.dev

**Review by dtleal — APPROVED** [review]

**Comment by tiangolo** [comment]
📝 Docs preview for commit 33d3a030fb5feb476e653a683eb8c61bfcf59831 at: https://0b091869.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit fd993ed5479c5b909fedcc9de630a62e4746b9c2 at: https://dcf7f6de.fastapitiangolo.pages.dev

**Review by dtleal — APPROVED** [review]

**Comment by tiangolo** [comment]
📝 Docs preview for commit 659b1df0d1e89a9b8a3fbcad22da8201be6c12a3 at: https://662df379.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 7d18f39095850395bdd4b51053d97b7faf10388f at: https://c44a88ae.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 3b4f3cc4ac26debfd3c5d9edb18eb01aded8d219 at: https://1a1da600.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 70882ba17a4363a501f6885930e5d3fe4bdd4686 at: https://e1904b34.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 616f822bf8e2047bc2cb95f9a228a227820bcc96 at: https://785c40b9.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 70a55c29fc12f7ee974398105ca6b716f34608a4 at: https://7fc6e522.fastapitiangolo.pages.dev

**Comment by alejsdev** [comment]
Thanks @nilslindemann 🤓 

And thanks for the review @dtleal ✌️

**Comment by nilslindemann** [comment]
Thanks!

**Pull request merged**
