### PR TITLE
Update starlette version and add comprehension in encoders.py

### PR DESCRIPTION
**Pull request by acutaia**
Updated starlette from 0.13.6 to 0.13.7
Cause version 0.13.7 [fixes high memory usage when using BaseHTTPMiddleware middleware classes and streaming responses](https://github.com/encode/starlette/releases/tag/0.13.7)

### CODE REVIEW

**Review by Kludex — APPROVED** [review]

**Comment by acutaia** [comment]
The tests for last commit where successful in my pc, i don't know why they failed here
test

**Comment by Kludex** [comment]
Can you run `black`, please? 
image

**Comment by Kludex** [comment]
starlette version was already merged yesterday/the day before I think

**Comment by acutaia** [comment]
> Can you run `black`, please?
> image

Sorry, i forgot. Done ;)

**Review by ycd — CHANGES_REQUESTED** [review]
In #1987 @tiangolo reverted the deletion of `sqlalchemy_safe`

https://github.com/tiangolo/fastapi/blob/e77ea635777d2494690ba3eb62bd005b9edeefde/fastapi/encoders.py#L71-L94

https://github.com/tiangolo/fastapi/blob/e77ea635777d2494690ba3eb62bd005b9edeefde/fastapi/encoders.py#L101-L113


An update should do good.

**Comment by acutaia** [comment]
@ycd  done  ;)

**Review by ycd — APPROVED** [review]

**Comment by tiangolo** [comment]
Thanks for your effort! :coffee: 

This was handled in another PR, the current Starlette version is `0.14.2`, so I'm closing this one.

**Pull request closed without merging**
