### PR TITLE
⬆️ Upgrade version of Starlette to `>= 0.36.3`

### PR DESCRIPTION
**Pull request by tiangolo**
⬆️ Upgrade version of Starlette to `>= 0.36.3`

### CODE REVIEW

**Comment by tvasenin** [comment]
@tiangolo There was an unintentionally breaking change that affected Starlette from `0.36.0` to `0.37.0`.

Fixed in v0.37.1: https://github.com/encode/starlette/pull/2485

Could you pls bump requiremens to `starlette>=0.31.7` and release FastAPI `v0.109.2`?

**Comment by alimcmaster1** [comment]
I agree - https://github.com/tiangolo/fastapi/pull/11146

@tvasenin - what is the Starlette API deprecation policy. Wondering if we need a max version

**Comment by tvasenin** [comment]
> I agree - #11146
> 
> @tvasenin - what is the Starlette API deprecation policy. Wondering if we need a max version

I'm not aware of Starlette deprecation policy -- though, given the v0.x version scheme, according to SemVer, anything could happen in any release :)

**Comment by tvasenin** [comment]
Newly released `v0.110.0` still has the old dependency -- here's PR #11320 to finally fix this.

**Pull request merged**
