### PR TITLE
📝 Fixed typo in documentation - Body Fields page

### PR DESCRIPTION
**Pull request by ab-dauletkhan**

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 88a7f70e8e7a18e3f832c80cda7361afedf71148 at: https://498ecef4.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit e8efce6c42d869b86d69d5593e4fa8534628d30e at: https://fa3aa86e.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit def1040299318bd640bff55bbd9344f78818e9ab at: https://ed4dd190.fastapitiangolo.pages.dev

**Review by hasansezertasan — APPROVED** [review]
LGTM

**Comment by alejsdev** [comment]
Hi @ab-dauletkhan, it's not a typo error, it's intended to be that way. The original version is more accurate because it correctly describes the purpose of the `description` field. I think it's a misunderstanding with the field parameter `title`, used to customize the generated JSON schema (https://docs.pydantic.dev/latest/concepts/json_schema/#field-level-customization).

We'll close this one but thank you for the interest and effort! :smile_cat:

**Pull request closed without merging**
