### PR TITLE
👷 Update GitHub actions to download and upload artifacts to v4, for docs and coverage

### PR DESCRIPTION
**Pull request by tamird**
See
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 9bd4c9b3a49d7ca8b37a1ac061e1f3b6c5276f6f at: https://4143fdbe.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 4b217c40154746196cce46ec4eb5dfd35498b628 at: https://53f4b89b.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit ac361b65bb4a023b89eee7338c8dc84d37165a68 at: https://03d23a21.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
Great, thank you @tamird! :rocket: :cake: 

I updated it to use the new download artifact instead of the previous external action, as the new one now supports downloading from other workflows. :tada:

**Comment by tamird** [comment]
Neat!

**Pull request merged**
