### PR TITLE
✏️ Documentation tweaks

### PR DESCRIPTION
**Pull request by nilslindemann**
This PR is huge, I am sorry. But I am also happy that it's done.

These are things which I have changed/fixed in locations outside the German docs, while I translated it. The commit comments contain detailed descriptions.

I am pretty sure of all commits, except the last two:

* [Convert external fastapi links to relative local links](https://github.com/tiangolo/fastapi/commit/661a30976aab1bc4daae3677f6f014a6f79a8d76) – not sure if the links in the reference are external for purpose. 
* [Probable improvements](https://github.com/tiangolo/fastapi/commit/049af7eb2513324c251f3ac3c6df7b58a63dd82d) I think these are improvements, but please review carefully.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 049af7eb2513324c251f3ac3c6df7b58a63dd82d at: https://d82e5064.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit ae4e07e9441053501f384508ca7c4046d9e64f0d at: https://64fe80d8.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 7393082181675e0bf3889e56bed36f8299bc9bcc at: https://9dd9cf04.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit f6561524fd88a4486d550368b7eddb9b596cb695 at: https://2b3af993.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 69ae1ff02c5ea363328954be52693a68da551115 at: https://8abed4a5.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 050e2fb3f13adad69ade81675063a86e3c2e7759 at: https://9564556a.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 6767c3c3e29ea4a2d35c64620844cd6cbdc1ea02 at: https://5f9b75cb.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 3d0da80f5773e81e314543add00440af106dd555 at: https://ddccf36f.fastapitiangolo.pages.dev

**Comment by nilslindemann** [comment]
@alejsdev Dammit, I anyhow effed things up in [this commit](https://github.com/tiangolo/fastapi/pull/10985/commits/6767c3c3e29ea4a2d35c64620844cd6cbdc1ea02#diff-101eb49c79208a3498543c29b9170aaabf8ce9c8dbdc16b3eb63f4010c9081ee). There were things removed which exist in the main branch. I am currently not grasping what happened here, so I will close and recreate this PR, and while doing this, I will look how I can make this simpler to review. I hope you did not already invest time in reviewing. If so, sorry.

**Pull request closed without merging**
