### PR TITLE
Enhancement Proposal: Generalized DI system

### PR DESCRIPTION
**Pull request by adriangb**
A high-level proposal for enhancements to the DI system.

### CODE REVIEW

**Comment by adriangb** [comment]
I believe tbe original request in #3620 also be made to work by having a dependency scope that goes out of scope before the request is returned

**Comment by ghandic** [comment]
@adriangb does this PR help this issue too? https://github.com/tiangolo/fastapi/pull/3953

**Comment by adriangb** [comment]
> @adriangb does this PR help this issue too? #3953

I can't tell just from the description of the issue, but if it is about raising exceptions after `yield` in dependencies, then yes, this could potentially help certain use cases

**Comment by adriangb** [comment]
Seems like #3902 and #639 are also related. `di` is currently able to parallelize both sync and async dependencies: https://github.com/adriangb/di/tree/main/benchmarks

**Pull request closed without merging**
