### PR TITLE
🌐 Add Korean translation for `docs/ko/docs/help/index.md`

### PR DESCRIPTION
**Pull request by KaniKim**
- Add Korean translation for docs/ko/docs/help/index.md
- After this, I will add help category Korean translation

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 7ae253f38fad94121dcf1733e830f0a047677da8 at: https://538377d4.fastapitiangolo.pages.dev

**Comment by kitrio** [comment]
Thankyou

**Comment by KaniKim** [comment]
> Thankyou
Hello @kitrio, If you don't mind, can you review my translations?
- https://github.com/tiangolo/fastapi/pull/10976
- https://github.com/tiangolo/fastapi/pull/10983
- https://github.com/tiangolo/fastapi/pull/10989
Thanks

**Review by junah201 — APPROVED** [review]

**Comment by alejsdev** [comment]
Thanks for your contribution @KaniKim 😸 

And thanks for the review @junah201 🚀✨

**Pull request merged**
