### PR TITLE
Fixes the URL for starlette Request reference documentation

### PR DESCRIPTION
**Pull request by vinaypotluri**
Changes Request reference URL from https://www.starlette.io/requests/ to
https://www.starlette.io/requests.html

### CODE REVIEW

**Review by ArcLightSlavik — APPROVED** [review]
`https://www.starlette.io/requests` can also be used, I do kind of prefer it to .html but don't think it matters that much.

**Comment by ArcLightSlavik** [comment]
Might want to hold with this PR since it seems like a website wide issue on Starlette side.

**Comment by tomwojcik** [comment]
Fixed in Starlette

**Comment by ArcLightSlavik** [comment]
@vinaypotluri This was fixed by Starlette, could you close this?

**Comment by vinaypotluri** [comment]
Will be closing this pull request since the issue has been fixed in starlette

**Pull request closed without merging**
