### PR TITLE
Translate index.md in Advanced User Guide  to Japanese.

### PR DESCRIPTION
**Pull request by gomano-shigure**
This PR translates the  index.md  to Japanese.

According to the issue: #1572

Thanks!!

### CODE REVIEW

**Comment by amazyra** [comment]
I'm not familiar with GitHub. how I set a label for this PR?

**Comment by tokusumi** [comment]
only owner (tiangolo) can add labels

**Comment by amazyra** [comment]
thanks for your reply! 
I also have a question about docs on the localhost.
It seems to be not working (return 404).
Is it working on your environment?

**Comment by tokusumi** [comment]
`/ja/` return 404 in my local environment, too, but you may ignore that.
if you edit `mkdocs.yml` as [here](https://fastapi.tiangolo.com/contributing/#existing-language), it shows your translated section.

**Comment by amazyra** [comment]
> `/ja/` return 404 in my local environment, too, but you may ignore that.
> if you edit `mkdocs.yml` as [here](https://fastapi.tiangolo.com/contributing/#existing-language), it shows your translated section.

thanks for your reply!

**Comment by tokusumi** [comment]
please commit `mkdocs.yml`. your docs preview by GitHub action does not appear.

**Review by delhi09 — CHANGES_REQUESTED** [review]
I pointed out some of the meanings of the sentences.

**Comment by tiangolo** [comment]
Thanks for the effort! This was covered by https://github.com/tiangolo/fastapi/pull/5043, so I'm gonna close this one now. :coffee:

**Pull request closed without merging**
