### PR TITLE
🌐 Start translation of the documentation for the Albanian language

### PR DESCRIPTION
**Pull request by vjanz**
I want to contribute to translations for the Albanian language, so let's go 👍

### CODE REVIEW

**Comment by Kludex** [comment]
@vjanz Based on what I've seen, I recommend you to:
- Create a "translation" issue e.g. https://github.com/tiangolo/fastapi/issues/2041
- Divide this PR in two:
    - Language setup
    - `index.md` page
The reasons are:
- Being able to coordinate the translations, so others can contribute.
- To have translations merged, we need approvals from people that speaks the language. If there's a PR with only the setup, it can be merged right away and people can take their time to review the `index.md`. Besides, your PR will not block others to contribute with other pages.

**Comment by ycd** [comment]
@Kludex, i think he did it right :thinking:. Expect from creating a translation issue to coordinate translations :+1:

**Comment by Kludex** [comment]
Did what? 🤔

**Comment by ycd** [comment]
I mean the setup, anything wrong with it?

**Comment by Kludex** [comment]
Oh, I'm sorry. I assumed the index.md was already translated. 😔 Yeah, everything is fine!

**Comment by vjanz** [comment]
Hey @Kludex and @ycd, thank you for starting the conversation here.

To be more clear, I just did the initial setup on this PR as requested on [docs](https://fastapi.tiangolo.com/contributing/), and I continued translating section by section on separate branches, so other people can contribute.

So I am thinking of making a separate PR for each section that I translate if that sounds right?

Cheers!

**Comment by Kludex** [comment]
> To be more clear, I just did the initial setup on this PR as requested on docs, and I continued translating section by section on separate branches, so other people can contribute.

Yeah, it was my bad. I assumed the `index.md` was already translated. 

> So I am thinking of making a separate PR for each section that I translate if that sounds right?

It does! :tada:

**Comment by tiangolo** [comment]
Awesome! Thanks @vjanz ! :rocket: :tada: 

And thanks @Kludex and @ycd for the help here! :bow:

**Pull request merged**
