### PR TITLE
✏ Fix typos in `tests/test_schema_extra_examples.py`

### PR DESCRIPTION
**Pull request by supraaxdd**
While doing a typing test on speedtyper.dev, I got a snippet that had a typo, so decided to drop by and fix it ;)

### CODE REVIEW

**Review by zoliknemet — APPROVED** [review]

**Review by odiseo0 — CHANGES_REQUESTED** [review]
Tests are not passing because in `openapi_schema` still has some of that 'Qeury' mistake, you have to change them for the tests

**Comment by supraaxdd** [comment]
Okay everything is good to go, thanks for letting me know about the other typos I overlooked!

**Review by odiseo0 — APPROVED** [review]
LGTM

**Review by BilalAlpaslan — APPROVED** [review]

**Review by LorhanSohaky — APPROVED** [review]

**Comment by tiangolo** [comment]
Ha! That's fun, thank you @supraaxdd! :cake:  And thanks everyone for the interactions!

**Pull request merged**
