### PR TITLE
Update starlette to `~=0.14`

### PR DESCRIPTION
**Pull request by dhirschfeld**
Just seeing if there is any appetite to:
  1. Update the `starlette` pin
  2. Loosen the exact pinning

### CODE REVIEW

**Comment by Mause** [comment]
This is a duplicate of https://github.com/tiangolo/fastapi/pull/2335

**Comment by dhirschfeld** [comment]
Looks like it's not compatible due to the removal to `UJSONResponse`:
```
fastapi/responses.py:10: error: Module 'starlette.responses' has no attribute 'UJSONResponse'; maybe "JSONResponse" or "Response"?
```
***xref:*** https://github.com/encode/starlette/releases/tag/0.14.1

**Comment by dhirschfeld** [comment]
> This is a duplicate

So, it is - sorry should have searched first!

I still think there's value in relaxing the exact pinning so wanted to check if @tiangolo had changed his position since #1555?

**Comment by tiangolo** [comment]
Thanks for the discussion! 🍰 

And nope, I can't relax the pin yet, there have been constant/recent breaking changes. And in fact, the current pin on Starlette allows Starlette to move more easily without worrying a lot about breaking stuff between versions and having to deal with a lot of backwards compatibility between versions. That problem will probably come later after the first 1.x versions, but for now, it's better to try to structure the code the best way possible before getting into those new problems... 🤓 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.

**Pull request closed without merging**
