### PR TITLE
📝 Add MongoDB recipe to docs

### PR DESCRIPTION
**Pull request by linjer**
I found it fairly simple to integrate MongoDB into my FastAPI application using Motor & Beanie. Added this recipe to the docs  as a convenience to other developers.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit a8d6bc2d9fb1457cb446f27c1772c7e7b0996547 at: https://c3c6da87.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 8ba893f72387695cb2cb46794a45646aa3e3689f at: https://2d1a909f.fastapitiangolo.pages.dev

**Comment by linjer** [comment]
@tiangolo @alejsdev This is a fairly simple addition to the docs. Anything I can do to help get this merged?

**Comment by tiangolo** [comment]
📝 Docs preview for commit 05edb53aa806214379618fa9ec25daa60c438f6f at: https://d83e9257.fastapitiangolo.pages.dev

**Pull request closed without merging**
