### PR TITLE
Fixed order of imports

### PR DESCRIPTION
**Pull request by matthewhegarty**
Running `bash scripts/test-cov-html.sh`
reported errors from the isort checks: 'Imports are incorrectly sorted'
This PR fixes the order of the imports only.

### CODE REVIEW

**Comment by euri10** [comment]
happy to see I'm not the only one!
look at fastapi.tiangolo.com/contributing
and install fastapi with flit, isort errors should disappear if I'm not
mistaken


Le ven. 8 mars 2019 à 9:43 PM, codecov[bot] <notifications@github.com> a
écrit :

**Comment by matthewhegarty** [comment]
Yikes! - thanks for clarifying.  I installed with pipenv and the errors went away.
I'll close the PR because obviously `isort` fixes the imports.

@tiangolo would a Makefile simplify the build process?

**Comment by tiangolo** [comment]
Thank you guys!

There was also a recent change in how `isort` works that made it change them (and report errors).

It just bit me today while doing https://github.com/tiangolo/fastapi/pull/74. I fixed the linting and testing with those changes at: https://github.com/tiangolo/fastapi/pull/75

There's a script that does all the linting and formating at `scripts/lint.sh`. It should do all the formatting and sorting for you in one batch.

Also, if you are in VS Code, you can create a task to run it without leaving the editor, with:

```JavaScript
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "lint",
            "type": "shell",
            "command": "bash scripts/lint.sh",
            "problemMatcher": []
        }
    ]
}
```

A `Makefile` would add another development dependency/tool/language, let's see if we can keep it with simple scripts first.

**Comment by matthewhegarty** [comment]
Thanks for the response.  Taking my first steps with Fastapi but really impressed so far (both with the project goals and documentation). :+1:

**Comment by tiangolo** [comment]
That's great, thanks @matthewhegarty ! :rocket: :smile:

**Pull request closed without merging**
