### PR TITLE
🌐 Add Portuguese translation for `docs/pt/docs/how-to/general.md`

### PR DESCRIPTION
**Pull request by lucasbalieiro**
Hello guys,

this is just the translation to PT  of the doc in docs/pt/docs/how-to/general.md.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit bf05b1569b1cca3499dca40ce7cf7860ab047b8c at: https://a97da75b.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 91a0b990c5ef7573cb36a7972641adf07cd23ba9 at: https://fe16ccf4.fastapitiangolo.pages.dev

**Review by nazarepiedady — APPROVED** [review]
It is good enough to be merged to the main branch.

Thanks for your contribution.

**Review by ceb10n — CHANGES_REQUESTED** [review]
Great translation 🚀

Just found some accents missing and some extra commas

**Comment by lucasbalieiro** [comment]
Many thanks to @nazarepiedady and @ceb10n!

@ceb10n, I've implemented the corrections you suggested in this commit: [commit link](https://github.com/tiangolo/fastapi/pull/11825/commits/81087d0fc6bfdabf232cd81fff437d57ae013f19).

**Review by ceb10n — APPROVED** [review]

**Comment by tiangolo** [comment]
📝 Docs preview for commit 53b21c8c9714f7ed7bf822c506f0de8741e90bed at: https://b20e9ae1.fastapitiangolo.pages.dev

**Comment by alejsdev** [comment]
Thank you all for your help and contribution! :sparkles: @lucasbalieiro @ceb10n @nazarepiedady

**Pull request merged**
