### PR TITLE
🌐 Add Azerbaijani translation for `docs/az/docs/fastapi-people.md`

### PR DESCRIPTION
**Pull request by vusallyv**

### CODE REVIEW

**Comment by vusallyv** [comment]
Fixed learn page folder issue here: [PR](https://github.com/tiangolo/fastapi/pull/11192)

**Review by aykhans — COMMENTED** [review]
"Community" sözünü "cəmiyyət" əvəzinə "icma" olaraq çevirmək daha uyğundur məncə.

**Review by aykhans — APPROVED** [review]

**Comment by tiangolo** [comment]
📝 Docs preview for commit 9e330012744a2aa6549b056c123aad452ea7b654 at: https://bc15c8f5.fastapitiangolo.pages.dev

**Review by aykhans — APPROVED** [review]

**Review by leylaeminova — APPROVED** [review]

**Comment by tiangolo** [comment]
📝 Docs preview for commit 353f3d66e7be0aff76b0c6658dd6904fac2e2c06 at: https://ddd1c4d0.fastapitiangolo.pages.dev

**Comment by alejsdev** [comment]
Thank you for the help! @vusallyv 🚀✨

And thanks for the reviews @aykhans @leylaeminova 🔍️

**Pull request merged**
