### PR TITLE
fix typo :)

### PR DESCRIPTION
**Pull request by tamtam-fitness**

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit de9dc180e0a7d9b434fa341b30075f814883e24d at: https://64c68884ad7dc417b9fde575--fastapi.netlify.app

**Review by FraneCaleta — APPROVED** [review]

**Comment by Kludex** [comment]
I don't think this is a typo. 🤔

**Comment by tamtam-fitness** [comment]
Thx! On second thoughts, I feel that is certainly not wrong.

**Comment by raphaelauv** [comment]
@tamtam-fitness then could you close the PR , thanks

**Comment by tamtam-fitness** [comment]
Understood, thank you for your review .

**Pull request closed without merging**
