### PR TITLE
🌐 Add German translation for `docs/de/docs/advanced/openapi-webhooks.md`

### PR DESCRIPTION
**Pull request by nilslindemann**
← `advanced/openapi-callbacks.md` (#10710)
→ `advanced/wsgi.md` (#10713)

[German translation progress](https://github.com/tiangolo/fastapi/discussions/10582)

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 644cace7f200932367806fc387db471454fe73e3 at: https://28f5b497.fastapitiangolo.pages.dev

**Review by dtleal — APPROVED** [review]

**Comment by tiangolo** [comment]
📝 Docs preview for commit 89c725cfb7d36c51742b03820423aba9cbdcd625 at: https://ab8236a4.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 124dc2cfc747a7db43f81233332a70fa1a5114ff at: https://c1b1f62f.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 18c35637288ce0633d4e7a61878c6c2ee8806421 at: https://ddcfb60e.fastapitiangolo.pages.dev

**Comment by alejsdev** [comment]
Thanks @nilslindemann 🥳 

And thanks for the review @dtleal 🪄

**Comment by nilslindemann** [comment]
Best!

**Pull request merged**
