### PR TITLE
FIX: #894 Check already cloned fields in create_cloned_field to support recursive models

### PR DESCRIPTION
**Pull request by voegtlel**
Include recursion check for create_cloned_field.
Added test for recursive model.

### CODE REVIEW

**Comment by merowinger92** [comment]
might be worth to mention @dmontagu to review this since he has made already some thoughts about solving this

**Comment by jmagnusson** [comment]
This PR solves the example issue in #894 as well as a more complicated private project of mine. LGTM 👍

**Comment by tiangolo** [comment]
Very clever! Thanks for your contribution @voegtlel :cake: :rocket:

**Comment by jmagnusson** [comment]
For a complex app that I'm building I've seen memory usage go up from ~140MB to ~305MB and app start up time increased from ~2.4s to ~9.5s when moving from version `0.46.0` to `0.54.1`.

It looks like most of the additional time is spent in `create_cloned_field` which was changed a lot in this PR.

Has anyone else had similar issues?

**Comment by jmagnusson** [comment]
[PR 1100](https://github.com/tiangolo/fastapi/pull/1100) still works for me, removing the issues mentioned above.

I've cherry-picked his commit on top of the current head in this repo (4e77737a3f7bf2608132ea170e9ff013b5af6732) and that works as well.

**Comment by phy25** [comment]
@jmagnusson I would recommend that you create a new issue, or this might be left unnoticed.

**Comment by tiangolo** [comment]
As @phy25 says, it would probably be better in a new issue.

Anyway, if you want to profile specific functions and timings, you can try https://github.com/sm-Fifteen/asgi-server-timing-middleware

Or the ideas in this thread: https://github.com/tiangolo/fastapi/issues/701

That might help to detect where is the change exactly.

**Pull request merged**
