### PR TITLE
📝 Add External Link: FastAPI application monitoring made easy

### PR DESCRIPTION
**Pull request by itssimon**
I wrote a blog post on a simple solution for monitoring FastAPI applications that I'd like to add to the External Links section in the docs. It discusses a different approach than the existing two linked articles on the topic.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit a5e394531fb062e41844b7f66cb26f870618720b at: https://4a5eeb93.fastapitiangolo.pages.dev

**Comment by itssimon** [comment]
@iudeen Would you mind reviewing this?

**Review by hasansezertasan — APPROVED** [review]
LGTM

**Review by alejsdev — APPROVED** [review]

**Comment by tiangolo** [comment]
Thanks @itssimon!

And thanks for the reviews @hasansezertasan and @alejsdev 🤓 

As I can't commit on top of this branch I created a new PR with its commit and the branch merged here: https://github.com/tiangolo/fastapi/pull/10917

Given that, I'll close this one. Thanks! 🍰

**Pull request closed without merging**
