### PR TITLE
Provide preview for the German translation progress

### PR DESCRIPTION
**Pull request by nilslindemann**
This is a regeneration of #10625, which either git, GitHub, or me effed up. The commits are now sorted by directory, which is simpler when handling merge conflicts, and probably also a better overview. Like the other PR, it is not intended to be merged.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit b0fb3360f00dfb04e7cc5cbede15c25f071d5921 at: https://4fe47d19.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 72d19f818fc484a30c720de6cd8540542c60b4c6 at: https://b291fb99.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit df43b9827f68e7fa8f5b3c770407a298b6490c8f at: https://3698d5a3.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit f2de72c3343d682c9ad93b2a31c7f83005e53dd7 at: https://bf929318.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 29425f06463504bcbedc5d33ff081ec5506c8eaf at: https://58448b9e.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 701d9d6717a30d4f75a91539567830f064dbc543 at: https://cca8f20c.fastapitiangolo.pages.dev

**Comment by nilslindemann** [comment]
Ok, there are now merge conflicts again, and the last time I resolved them via the GitHub GUI, I could afterwards not reorder the commits any more. So I will just wait this time until the related PRs (some to be created) are merged and the conflicts disappear.

**Comment by tiangolo** [comment]
As most of these files are already merged, I'm gonna close this one, just to clean up things. Thank you! :rocket:

**Comment by nilslindemann** [comment]
Thanks, @iangolo, was planning to do that too.

**Pull request closed without merging**
