### PR TITLE
 🌐 Update Portuguese translation for `docs/pt/docs/advanced/security/http-basic-auth.md`

### PR DESCRIPTION
**Pull request by andersonrocha0**

### CODE REVIEW

**Review by ceb10n — APPROVED** [review]
Nice review Anderson 😺

**Comment by andersonrocha0** [comment]
@ceb10n do you know how can I add the lang-pt label?

Thx.

**Review by nazarepiedady — APPROVED** [review]

**Comment by ceb10n** [comment]
> @ceb10n do you know how can I add the lang-pt label?
> 
> Thx.

Only the mantainers can add labels and approve the pr

**Review by cassiobotaro — APPROVED** [review]

**Comment by alejsdev** [comment]
Thanks for your interest in contributing to FastAPI! @andersonrocha0 :pray: 

And thank you all for the reviews @nazarepiedady @ceb10n @cassiobotaro :medal_sports:

**Pull request merged**
