### PR TITLE
🌐 Add Korean translation for `docs/ko/docs/deployment/docker.md`

### PR DESCRIPTION
**Pull request by hynjngyeo**
- Add Korean translation for docs/ko/docs/deployment/docker.md
- Related [FEATURE] Korean translations **[[FEATURE] Korean translations #2017](https://github.com/tiangolo/fastapi/issues/2017)**

### CODE REVIEW

**Comment by joonas-yoon** [comment]
first, thanks for your work!

and I think you'd like to remove the files `.DS_Store`

**Review by PraveenNanda124 — COMMENTED** [review]
Good work

**Review by joonas-yoon — APPROVED** [review]
LGTM

**Comment by tiangolo** [comment]
📝 Docs preview for commit ca726eeac10e57a5b77a11091f4467c8d438844b at: https://649a1bae7ba2251554e3ac0b--fastapi.netlify.app

**Comment by alejsdev** [comment]
Thank you! @nearnear 😃 

And thanks for the reviews @joonas-yoon and @PraveenNanda124 🚀

**Pull request merged**
