### PR TITLE
Found a code omission in the tutorial

### PR DESCRIPTION
**Pull request by yuki1sntSnow**

### CODE REVIEW

**Comment by yuki1sntSnow** [comment]
Found a code omission in the tutorial
Part [Query Parameters and String Validations] of the tutorial omits the [Ellipsis (...)]

**Review by JarroVGIT — CHANGES_REQUESTED** [review]
This was specifically changed in PR 4906 when this feature was introduced. The `...` is not longer required in the Query param, and the omission is by design. 

I would recommend to close this PR.

**Comment by yuki1sntSnow** [comment]
Thank you for providing that information.

**Comment by tiangolo** [comment]
Thanks for the help @JarroVGIT ! 🍰

And thanks for coming back to close the issue @yuki1sntSnow ☕

**Pull request closed without merging**
