### PR TITLE
 ✨ Add custom GenerateJsonSchema

### PR DESCRIPTION
**Pull request by maurerle**
Supersedes #9873 which removes the generation of a AnyOf type None when using `| None` in method signatures, introduced through pydantic v2.

Has tests fixed in contrast to #9873 and is rebased onto latest master

Closes #9709 

Closes discussions:
https://github.com/tiangolo/fastapi/discussions/10836
https://github.com/tiangolo/fastapi/discussions/10481

### CODE REVIEW

**Comment by estebanx64** [comment]
Hi @Kludex and @maurerle 👋

Thank you for your interest and time in helping us fix this misbehavior.

Before we can continue reviewing this PR, Can you help us fix the test to cover the missing line which is an exception here
`fastapi/_compat.py line 120`
image

**Comment by maurerle** [comment]
Can we reopen this please @alejsdev ? The comment above somehow slipped through my inbox.

**Comment by maurerle** [comment]
So @estebanx64 you would like to have an additional tests which calls `get_definitions` twice with the same `GenerateJsonSchema` instance to check that an error was thrown.

As there is currently no unit test to test openapi functions, where should this go?

**Comment by Kludex** [comment]
It doesn't look like I can reopen it.
Screenshot 2024-10-02 at 14 27 55

If you can't yourself, then feel free to create a new one.

**Pull request closed without merging**
