### PR TITLE
✏️ Update highlighted line in `docs/en/docs/tutorial/bigger-applications.md`

### PR DESCRIPTION
**Pull request by papb**

### CODE REVIEW

**Comment by Ryandaydev** [comment]
@papb If I am reading the tutorial correctly, the existing doco incorrectly highlights row 4.

I think instead of this change (which highlights lines 4 & 5), I think it should be changed to highlight row 5.

**Review by Ryandaydev — CHANGES_REQUESTED** [review]
@papb If I am reading the tutorial correctly, the existing doco incorrectly highlights row 4.

I think instead of this change (which highlights lines 4 & 5), I think it should be changed to highlight row 5.

**Comment by papb** [comment]
@Ryandaydev Thank you, you're right. After re-reading I decided to also change another block to highlight one extra line, can you take a look?

**Review by iudeen — APPROVED** [review]
Looks good. Nice catch!

**Review by Ryandaydev — APPROVED** [review]
Requested changes have been applied.

**Comment by alejsdev** [comment]
Good catch. Thanks @papb 🙂 

And thanks for the review @iudeen and @Ryandaydev ✌️

**Pull request merged**
