### PR TITLE
🌐 Add Portuguese translation for `docs/pt/docs/how-to/testing-database.md`

### PR DESCRIPTION
**Pull request by GuilhermeRameh**

### CODE REVIEW

**Review by nazarepiedady — APPROVED** [review]

**Comment by nazarepiedady** [comment]
@ceb10n, could you do the kindness of reviewing this pull request?

**Comment by nazarepiedady** [comment]
@cassiobotaro, could you also review this pull request?

**Comment by nazarepiedady** [comment]
@cassiobotaro, could you also review this pull request?

**Review by ceb10n — APPROVED** [review]
🚀

**Comment by alejsdev** [comment]
Thanks for the contribution! @GuilhermeRameh :nerd_face: 

And thanks for the reviews @ceb10n @nazarepiedady :mag:

**Pull request merged**
