### PR TITLE
multiple aliases on fields (fixes #1889)

### LINKED ISSUE #1889: Multiple aliases for query parameters
### First check

* [x] I added a very descriptive title to this issue.
* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the FastAPI documentation, with the integrated search.
* [x] I already searched in Google "How to X in FastAPI" and didn't find any information.
* [x] I already read and followed all the tutorial in the docs and didn't find an answer.
* [x] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
* [x] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
* [x] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).
* [x] After submitting this, I commit to:
    * Read open issues with questions until I find 2 issues where I can help someone and add a comment to help there.
    * Or, I already hit the "watch" button in this repository to receive notifications and I commit to help at least 2 people that ask questions in the future.
    * Implement a Pull Request for a confirmed bug.

### Example

I would like to be able to do this:

```Python
from fastapi import FastAPI, Query

app = FastAPI()


@app.get("/")
def get(query: Optional[str] = Query(None, alias=['q', 'query']):
    return query
```

### Description

Currently to give a query parameter multiple aliases, you need to declare multiple query parameters.

### The solution you would like

Being able to give a list of aliases to the `alias` arg of the `Query` class.

```Python
Query(alias=['q', 'query'])
```
Of course backwards compatibility won'y break, as  `alias` arg would be of type `Optional[Union[str, Iterable[str]]]`.
You would still be able to do this:

```Python
Query(alias='q')
```

### Describe alternatives you've considered

@Kludex mentioned creating a new argument `aliases`

```Python
Query(aliases=['q', 'query'])
```

### PR DESCRIPTION
**Pull request by NoahCardoza**
When completed, this PR will allow fields to be defined in this way as per https://github.com/tiangolo/fastapi/issues/1889:

```py
from typing import Optional
from pydantic import Required
from fastapi import FastAPI, Query

app = FastAPI()


@app.get("/")
def get(
        question: str = Query(Required, aliases=('q', 'question')),
        answer: Optional[int] = Query(None, aliases=('a', 'answer'))
    ):
    return {
        'question': question,
        'answer': answer,
    }


app.setup()
```

TODO:
- [x] Make backwards compatible with base pydantic models
- [x] Refactor the typing to make more sense. 
- [ ] Figure out how to communicate that a required value was not received for a field with multiple aliases.
- [ ] Update documentation.
- [ ] Add testing for MultiAliasableModelField class.

### CODE REVIEW

**Comment by Kludex** [comment]
I think this should first be handled by Pydantic side.

**Comment by NoahCardoza** [comment]
@Kludex Do you mean that Pydantic should natively support this? As I understood it Pydantic wasn't planning to support this but it seems like it would be a very useful feature for people trying to port their APIs.

**Comment by tomgrin10** [comment]
> I think this should first be handled by Pydantic side.

@Kludex I don't see that happening any time soon, not until a major update (seems like a breaking change tbh).
So instead of waiting for the messiah, many of us would like this feature today.

**Comment by Kludex** [comment]
I didn't know/forget about those information. Sorry 🥺

**Comment by NoahCardoza** [comment]
It's all good @Kludex! Thanks for the support @tomgrin10! Sorry for the lag, I've been pretty bust the last few days, but I'm hoping to make progress on this today.

Side note:
Does anyone have any idea how errors should be reported on aliasable fields?

**Comment by Kludex** [comment]
@NoahCardoza I'm not sure if I get your question, but most of the exceptions are raised with  `ValueError`:
```bash
(base) ➜  fastapi git:(master) grep -r 'ValueError'                  
encoders.py:            raise ValueError(errors)
datastructures.py:            raise ValueError(f"Expected UploadFile, received: {type(v)}")
```
or just using assert (this is probably what you want):
```bash
(base) ➜  fastapi git:(master) grep -r 'assert'    
dependencies/utils.py:            assert __version__
dependencies/utils.py:                assert parse_options_header
dependencies/utils.py:    assert callable(
dependencies/utils.py:            assert is_scalar_field(
dependencies/utils.py:            assert isinstance(
dependencies/utils.py:        assert (
dependencies/utils.py:        assert isinstance(
responses.py:        assert orjson is not None, "orjson must be installed to use ORJSONResponse"
routing.py:    assert dependant.call is not None, "dependant.call must be a function"
routing.py:    assert dependant.call is not None, "dependant.call must be a function"
routing.py:        assert dependant.call is not None, "dependant.call must be a function"
routing.py:            assert (
routing.py:            assert isinstance(response, dict), "An additional response must be a dict"
routing.py:                assert (
routing.py:        assert callable(endpoint), "An endpoint must be a callable"
routing.py:            assert prefix.startswith("/"), "A path prefix must start with '/'"
routing.py:            assert not prefix.endswith(
applications.py:            assert self.title, "A title must be provided for OpenAPI, e.g.: 'My API'"
applications.py:            assert self.version, "A version must be provided for OpenAPI, e.g.: '2.1.0'"
openapi/models.py:    assert email_validator  # make autoflake ignore the unused import
openapi/utils.py:    assert isinstance(body_field, ModelField)
openapi/utils.py:    assert route.methods is not None, "Methods must be a list"
openapi/utils.py:    assert route.response_class, "A response class is needed to generate OpenAPI"
openapi/utils.py:                    assert isinstance(
openapi/utils.py:                assert isinstance(
```

**Comment by NoahCardoza** [comment]
@Kludex Take a look at this commit/comment: https://github.com/tiangolo/fastapi/pull/2235/commits/b18d1cbc72f35e9acfb9d40569dce3c71e03457f.

The question is how to communicate that a required value was not received for a field with multiple aliases.

Sorry, my initial question was very vague 😬

**Comment by tiangolo** [comment]
Thanks for the idea! This will be part of Pydantic v2, and will be inherited by FastAPI instead of having custom logic for it here.

But that will have to be after Pydantic v2 is released.

As this will have to change based on that, I'll pass on this one, but thanks for the effort and contribution! :cake:

**Pull request closed without merging**
