### PR TITLE
🔨 Update `scripts/format.sh`

### PR DESCRIPTION
**Pull request by grok-pro**
warning: `ruff <path>` is deprecated. Use `ruff check <path>` instead.

### CODE REVIEW

**Comment by codespearhead** [comment]
For reference: [ruff <path> was deprecated in favor of ruff check <path>](https://github.com/astral-sh/ruff/pull/10169).

**Review by codespearhead — APPROVED** [review]

**Comment by codespearhead** [comment]
Do you happen to know two other FastAPI users that you can ask a [PR review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) from?

**Comment by Jaza** [comment]
Looks good to me. Confirmed that the ruff docs recommend `ruff check <path>` now.

**Review by Kludex — APPROVED** [review]

**Review by hasansezertasan — APPROVED** [review]
LGTM

**Review by alejsdev — APPROVED** [review]

**Comment by alejsdev** [comment]
Hi @grok-pro, thanks for your interest! but this was already covered in another PR :sweat_smile: 
so we'll close this one but thanks for the help 🚀

**Pull request closed without merging**
