### PR TITLE
🌐 Add Portuguese translation for `docs/pt/docs/advanced/using-request-directly.md`

### PR DESCRIPTION
**Pull request by ceb10n**

### CODE REVIEW

**Comment by SamuelBFavarin** [comment]
Thanks @ceb10n, the translation looks good to me!

**Review by nazarepiedady — APPROVED** [review]
It looks very good for me. Let's go ahead with the translation.

**Comment by nazarepiedady** [comment]
> Thanks @ceb10n, the translation looks good to me! 

@SamuelBFavarin, could you approve the changes to advance the translation?

**Review by SamuelBFavarin — APPROVED** [review]

**Review by lucasbalieiro — APPROVED** [review]

**Review by cassiobotaro — APPROVED** [review]

**Comment by alejsdev** [comment]
Thank you! @ceb10n :sparkles: 
And thanks for the reviews @SamuelBFavarin @cassiobotaro @nazarepiedady @lucasbalieiro :rocket:

**Pull request merged**
