### PR TITLE
🌐 Add German translation for `docs/de/docs/advanced/generate-clients.md`

### PR DESCRIPTION
**Pull request by nilslindemann**
Despite `advanced/testing-database.md`, the advanced tutorial is translated to German! 🎉

← `advanced/wsgi.md` (#10713)
→ `deployment/index.md` (#10733)

[German translation progress](https://github.com/tiangolo/fastapi/discussions/10582)

### CODE REVIEW

**Review by dtleal — APPROVED** [review]

**Comment by tiangolo** [comment]
📝 Docs preview for commit 028538e21f96f4e9c4c35a6fa44af071a0b482c9 at: https://d2e4902b.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 652e4f2b356dcae9dfb0f5ae4de0232c76535801 at: https://33df288f.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 4a2d3c953069647264ab61c88fca33208522c940 at: https://0c898c29.fastapitiangolo.pages.dev

**Comment by dtleal** [comment]
:🚀

**Comment by dtleal** [comment]
:🚀

**Review by dtleal — APPROVED** [review]

**Comment by alejsdev** [comment]
Danke @nilslindemann 🤓 

And thanks for the review @dtleal 💯

**Pull request merged**
