### PR TITLE
Added the ability to transfer Pydantic model to FormData

### PR DESCRIPTION
**Pull request by vobinics**
Fixed error 422 when creating Pydantic model from FormData. [Example temporal workaround on StackOverflow](https://stackoverflow.com/questions/60127234/fastapi-form-data-with-pydantic-model)

### CODE REVIEW

**Comment by Fkawala** [comment]
Hey, I'd be interest to have this merged, is there anything blocking this to be merged ? Thank you !

**Comment by iudeen** [comment]
I tried 
```

from fastapi import FastAPI, Form, Depends, UploadFile
from pydantic import BaseModel

app = FastAPI()


class SimpleModel(BaseModel):
    no: int = Form(...)
    nm: str = Form(...)
    f: UploadFile = Form(...)


@app.post("/form")
async def form_post(form_data: SimpleModel = Depends()):
    fp = await form_data.f.read()
    print(fp)
```

It works with current (0.86) version. Is this PR still needed?

**Comment by mkmkmkmkmkmkmkmkmkmkmk** [comment]
1. My front-end code sends the request code like this
image
2. The backend code looks like this：
image
3. console.log(fd.getAll("file"))输出如下：
image
4.Why does the 422 error occur when accessing this interface '/v1/uploadFiles/'? How should I receive this fd request data on the backend? How should I modify it？
image

**Comment by tiangolo** [comment]
Thanks! :coffee: 

This was covered in https://github.com/fastapi/fastapi/pull/12129, it is available in FastAPI 0.113.0 :tada: 

The new docs: https://fastapi.tiangolo.com/tutorial/request-form-models/

Given that, I'll close this one, but thanks for the effort! :cake:

**Pull request closed without merging**
