### PR TITLE
📝 Update Gunicorn guide to use uvicorn-worker library

### PR DESCRIPTION
**Pull request by siavashyj**
# Update FastAPI Server Workers Documentation

## Description
This PR updates the FastAPI Server Workers documentation to reflect the changes in Uvicorn worker implementation. The `uvicorn.workers.UvicornWorker` has been [deprecated as of Uvicorn version 0.30.0](https://github.com/encode/uvicorn/releases/tag/0.30.0), and we're now recommending the use of the `uvicorn-worker` package.

## Changes
- Updated installation instructions to include the `uvicorn-worker` package
- Changed references from `uvicorn.workers.UvicornWorker` to `uvicorn_worker.UvicornWorker`
- Updated the explanation of the `--worker-class` option to reflect the new import

## Rationale
These changes are necessary to keep our documentation up-to-date with the latest best practices for deploying FastAPI applications with Gunicorn and Uvicorn workers.

## Testing
- [x] Verified that the installation instructions work with the latest versions of the packages
- [x] Tested the Gunicorn command with the new worker class
- [x] Ensured that the document flow and overall structure remain intact

## Additional Notes
Users upgrading from an older version may need to update their deployment scripts to use the new `uvicorn_worker.UvicornWorker` class. We may want to consider adding a migration guide or note in the documentation to help with this transition.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 98c1c8da9d47c1d61c98f0451c1f347715cedc04 at: https://af3405bf.fastapitiangolo.pages.dev

**Review by ceb10n — APPROVED** [review]

**Comment by tiangolo** [comment]
📝 Docs preview for commit 5b057cedc70511cc7caa0447021ec08917ddc4f1 at: https://9afd07f2.fastapitiangolo.pages.dev

**Comment by siavashyj** [comment]
Ready to merge 🟢

**Comment by Kludex** [comment]
My recommendation is to remove Gunicorn from the documentation.

**Comment by siavashyj** [comment]
> My recommendation is to remove Gunicorn from the documentation.

I've had some not-so-great experiences running native Uvicorn workers on productions instances due to: 1-potential memory leaks on long running instances, 2-slightly lower performance, 3-and higher tendency to timeout (502) under load compared to Gunicorn-Uvicorn workers. 

I think keeping it as an option is still a good thing to have, especially for long running production instances.
What do you think @Kludex?

**Comment by KissPeter** [comment]
> > My recommendation is to remove Gunicorn from the documentation.
> 
> I've had some not-so-great experiences running native Uvicorn workers on production instances due to: 1-potential memory leaks on long running instances, 2-slightly lower performance, 3-and higher tendency to timeout (502) under load compared to Gunicorn-Uvicorn workers.
> 
> I think keeping it as an option is still a good thing to have, especially for long running production instances. What do you think @Kludex?

I can proof it with measurements:
https://kisspeter.github.io/fastapi-performance-optimization/workers_and_threads#gunicorn-vs-uvicorn

**Comment by Kludex** [comment]
When did you do that?

Also... There's no need to prove anything here.

**Comment by estebanx64** [comment]
Hi @siavashyj

Thanks for your time and for helping us handle this topic. 🙇

We have planned to change these docs soon and we'll be reviewing it! 🤓

**Comment by tiangolo** [comment]
Thanks for the interest @siavashyj!

I prefer to recommend the new Uvicorn with `--workers`, it's fewer moving parts, simpler code, and fewer chances of having errors and problems. :nerd_face: 

I updated the docs here: https://github.com/fastapi/fastapi/pull/12069, that should cover this.

I'll now close this one, but thanks for the effort! :coffee:

**Pull request closed without merging**
