### PR TITLE
🌐 Add Portuguese translation for `docs/pt/docs/reference/exceptions.md`

### PR DESCRIPTION
**Pull request by lucasbalieiro**

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 99aa3cc41d3cffb1064769e185c3c934f711c80c at: https://d9a22980.fastapitiangolo.pages.dev

**Review by nazarepiedady — APPROVED** [review]
It is good to be merged to the main branch.

Thanks for your contribution.

**Review by Joao-Pedro-P-Holanda — APPROVED** [review]
Great job :)

**Comment by alejsdev** [comment]
Awesome :sunglasses: 
Thanks to everyone for the contributions! @lucasbalieiro @nazarepiedady @Joao-Pedro-P-Holanda :rocket: :100:

**Pull request merged**
