### PR TITLE
🔨 Specify `email-validator` dependency with dash

### PR DESCRIPTION
**Pull request by jirikuncar**
The package name is [`email-validator`](https://pypi.org/project/email-validator/).

---

This is more of a consistency improvement. I noticed after updating to the latest release that transitive dependencies have been renamed.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 6e867de9ab4304b0a622a0cd967af9945af35d93 at: https://8841bcea.fastapitiangolo.pages.dev

**Comment by jirikuncar** [comment]
It seems that after deeper investigation, the metadata for the `email-validator` package defines the name as `email_validator` - https://github.com/JoshData/python-email-validator/blob/main/setup.cfg#L2. I will move the question there instead. Feel free to close or ignore this PR.

**Review by Kludex — APPROVED** [review]

**Review by svlandeg — APPROVED** [review]
It makes sense to me to change the references in the documentation to `email-validator`, especially considering [this edit](https://github.com/JoshData/python-email-validator/commit/dbcf07cc5c8066c14b6dc58d2dbb4a1e582eeefd).

As a note, this PR also changes the `pyproject.toml` but I think that should be OK as well. For what it's worth, Pydantic also uses `email-validator` in their [project.toml](https://github.com/pydantic/pydantic/blob/main/pyproject.toml#L60).

It looks like some tests are failing after running the CI after merging in the latest `master`. These failing tests seem unrelated to me, but I'll keep this in draft and may come back to rerun the tests again next week (in case this is just a Github issue).

[UPDATE]: investigating the CI issue separately [here](https://github.com/fastapi/fastapi/discussions/12011).

[UPDATE 2]: The CI issues are now fixed to this PR should be ready to merge (after a final check by Tiangolo)

**Comment by tiangolo** [comment]
Thanks @jirikuncar! And thanks @svlandeg for the investigation and review :bow:

**Pull request merged**
