### PR TITLE
✏️ Fix typo in `fastapi/routing.py` 

### PR DESCRIPTION
**Pull request by sepsh**

### CODE REVIEW

**Comment by sepsh** [comment]
@Kludex

**Review by Kludex — APPROVED** [review]

**Review by alejsdev — APPROVED** [review]

**Comment by alejsdev** [comment]
Thanks for your help! @sepsh 😄 

For future references: This is a fix for https://github.com/tiangolo/fastapi/discussions/10493

**Review by hasansezertasan — APPROVED** [review]

**Comment by tiangolo** [comment]
Nice catch @sepsh! 🔍 

Thanks for the reviews @Kludex, @hasansezertasan, @alejsdev ☕ 🍪 👋

**Comment by sepsh** [comment]
Thanks to your awesome work @Kludex @alejsdev @alejsdev @hasansezertasan. I'm glad I could help. 🤗✌️

**Pull request merged**
