### PR TITLE
Add skip_defaults support for path operations (for #242)

### PR DESCRIPTION
**Pull request by wshayes**
Running into trouble getting skip_defaults passed correctly. I’m not understanding the full flow of the logic from the route decorators to the response serialization.

This is a Starlette class which has include_in_schema but does not have skip_defaults - how do we handle this? Do we need to?

    # From routing.py - line 331
    elif isinstance(route, routing.Route):
        self.add_route(
            prefix + route.path,
            route.endpoint,
            methods=route.methods,
            include_in_schema=route.include_in_schema,
            name=route.name,
        )

Haven't done any websocket work - not sure if websocket route needs to be handled for this (probably does)

I would appreciate pointers/help to finish this PR.

### CODE REVIEW

**Comment by tiangolo** [comment]
Thanks @wshayes ! I'll check it soon.

**Comment by tiangolo** [comment]
Thank you @wshayes !

I updated it a bit, added docs, tests, etc.

I renamed the parameter to `response_model_skip_defaults` to be more explicit and intuitive.

Although I think it's too long, I think we can start with a "too long" completely explicit version and then update it to a shorter version, like `response_skip_defaults` or `model_skip_defaults`.

The updated docs are here: https://fastapi.tiangolo.com/tutorial/response-model/#response-model-encoding-parameters

It will be included in the next release.

Thanks! :tada: :rocket: :cake:

**Comment by wshayes** [comment]
Thank you - sorry I couldn't complete it on my own. Very nice job with the documentation. I'll study the changes you made so I can understand the flow better.

**Comment by tiangolo** [comment]
Thanks for starting it @wshayes !

**Pull request merged**
