### PR TITLE
♻ Simplify internal RegEx in `fastapi/utils.py`

### PR DESCRIPTION
**Pull request by pylounge**
Replace regex for simple

### CODE REVIEW

**Review by JarroVGIT — APPROVED** [review]
Agree, `\W` is the equivalent of `[^a-zA-Z0-9_]` and is more elegant.

**Comment by lucaswiman** [comment]
> Agree, `\W` is the equivalent of `[^a-zA-Z0-9_]` and is more elegant.

No, that's not true. It's equivalent to `[^\w]`, which is a wider range of characters that just those. For example:

```python
>>> import re
>>> re.match(r'\W', 'ü')
>>> re.match(r'\w', 'ü')
<re.Match object; span=(0, 1), match='ü'>
```

This change may lead to better support for languages with non-ASCII characters, but it's not precisely equivalent to the old code.

**Comment by JarroVGIT** [comment]
> > Agree, `\W` is the equivalent of `[^a-zA-Z0-9_]` and is more elegant.
> 
> No, that's not true. It's equivalent to `[^\w]`, which is a wider range of characters that just those. For example:
> 
> ```python
> >>> import re
> >>> re.match(r'\W', 'ü')
> >>> re.match(r'\w', 'ü')
> <re.Match object; span=(0, 1), match='ü'>
> ```
> 
> This change may lead to better support for languages with non-ASCII characters, but it's not precisely equivalent to the old code.

I stand corrected. I took my information from regex101.com, and you are completely right. 

If this changes the behaviour, then I would expect a test case that would illustrate the exact intended behaviour.

**Comment by tiangolo** [comment]
Great, thanks @pylounge! :cake:

**Pull request merged**
