### PR TITLE
upgrade starlette dependency to 0.13.4

### PR DESCRIPTION
**Pull request by rushton**
This  upgrade is mostly to address the issue with StreamingResponse not killing the request when the client unexpectedly disconnects from the stream.

### CODE REVIEW

**Comment by mumumumu** [comment]
This is also needed to support the `SameSite` flag when setting cookies (mentioned in https://github.com/tiangolo/fastapi/issues/1099 and https://github.com/tiangolo/fastapi/issues/480).

**Comment by victoraugustolls** [comment]
@tiangolo is this ok? Really looking forward to use newest starlette version for the fixes.

**Comment by ziglef** [comment]
If this is ok, I'm also looking forward to use the newest starlette version (mostly for samesite cookies)

**Comment by euri10** [comment]
> If this is ok, I'm also looking forward to use the newest starlette version (mostly for samesite cookies)

same !

**Comment by tiangolo** [comment]
Great! Thank you @rushton ! :rocket: 

This will be available in FastAPI version `0.57.0`, (to be released in a couple of hours).

**Pull request merged**
