### PR TITLE
🌐 Initialize Indonesian translations

### PR DESCRIPTION
**Pull request by pace-noge**

### CODE REVIEW

**Comment by tiangolo** [comment]
Awesome, thank you @pace-noge! :rocket: :tada:

**Comment by jongbatax** [comment]
@pace-noge  how progress translation??

**Comment by pace-noge** [comment]
@jongbatax 
Currently i didn't have enough free time for translating. I have urgent work to do at office. Sorry for slow progress.

**Comment by jongbatax** [comment]
We can do it.....

Pada tanggal Sen, 19 Jul 2021 18.27, Nasaruddin ***@***.***>
menulis:

**Pull request merged**
