### PR TITLE
Update deta.md

### PR DESCRIPTION
**Pull request by mycaule**

### CODE REVIEW

**Comment by tiangolo** [comment]
It seems this is actually not necessary, so I'll pass on that. But thanks for your interest! ☕

**Comment by mycaule** [comment]
It IS necessary, the command doesn't work without specifying `--python`

**Comment by mycaule** [comment]
When I tried to deploy using Python 3.10 and deta 1.1.0 it didn't work without the --python

**Comment by iudeen** [comment]
Weird. It works just fine without the flag.

**Pull request closed without merging**
