### PR TITLE
📝 Add VS Code tutorial link

### PR DESCRIPTION
**Pull request by nilslindemann**
[This one](https://code.visualstudio.com/docs/python/tutorial-fastapi). It was recently published.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit ee79d07e18bd6675a7293b8f5f137f1d096c8a03 at: https://0945752f.fastapitiangolo.pages.dev

**Review by peidrao — APPROVED** [review]
✅

**Review by BilalAlpaslan — APPROVED** [review]

**Comment by tiangolo** [comment]
📝 Docs preview for commit 2a48df74e8aec6ce18eedabe8813e160bac12e8d at: https://fce11dfd.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit e0e11e535b4d9c9917a163eb1a08cfb193a1f972 at: https://d30ce5ef.fastapitiangolo.pages.dev

**Review by hasansezertasan — APPROVED** [review]

**Comment by tiangolo** [comment]
📝 Docs preview for commit 9dd82214ff77780173c2ceab9c23d616a1b3a824 at: https://0edd4d4f.fastapitiangolo.pages.dev

**Review by alejsdev — APPROVED** [review]

**Comment by tiangolo** [comment]
Niceee, thanks @nilslindemann! 🚀 

And thank you for the reviews @hasansezertasan, @peidrao, @BilalAlpaslan, @alejsdev 🍰 ☕

**Comment by tiangolo** [comment]
📝 Docs preview for commit 8c7fd9ed6a797152d7dce2972e2c5a18c43a601a at: https://763920c0.fastapitiangolo.pages.dev

**Pull request merged**
