### PR TITLE
Create a WebSocketAPIRoute class to support #166

### PR DESCRIPTION
**Pull request by jekirl**
Initial work at adding dependencies to websocket routes (see #166 ). The way I added it in is probably less than ideal, but figured I would open the PR for now. Still to be done is adding in tests for other dependencies such as Security, Query, Cookie, etc...

### CODE REVIEW

**Comment by tiangolo** [comment]
Nice! I'll review it soon.

**Comment by jekirl** [comment]
I have a few more things I could add to the PR that we are using internally. i.e. pydantic validated message types for websocket input/output. But I am not sure if others would find that functionality useful.

**Comment by tiangolo** [comment]
Sounds very interesting. I think we could have some optional mechanism to do it (not enforcing it on all cases).

How does it look like? I mean, the code a developer writes using your extensions.

**Comment by jekirl** [comment]
I will try to put together a sample project soon™ ...

**Comment by jekirl** [comment]
Circling back on this, been in our backlog. Semi tricky to separate out the functionality, but haven't forgotten about it!

**Comment by tiangolo** [comment]
Cool! I just refactored this PR a bit, added docs, updated tests and merged.

I also started https://github.com/encode/starlette/pull/527. Once (and if) it is accepted, it will allow us to `raise` inside WebSocket endpoints, sub-dependencies, and handle errors more cleanly.

This is just released in version `0.24.0`, the new docs are here: https://fastapi.tiangolo.com/tutorial/websockets/

**Pull request merged**
