### PR TITLE
🌐 Fix markdown error in Korean translation for ```docs/ko/docs/deployement/*.md```

### PR DESCRIPTION
**Pull request by sodaMelon**
I corrected minor Markdown syntax errors and fixed bold formatting as per the original text. 

also modified some typo. 

(most problem appeared by markdown, because of korean postposition grammer. anyway maybe it will be better)

### CODE REVIEW

**Comment by sodaMelon** [comment]
hi could you check my PR for fast-api-docs?
Most docs are broken, so very hard to read
@hard-coders @jujumilk3

**Comment by jujumilk3** [comment]
Oh my, it seems the markdown parser has changed. The document is completely messed up. Thank you for fixing it. But in this way, a space is added after every bold text, which feels quite awkward in Korean documents. I’d like to check others' opinions as well.

**Comment by sodaMelon** [comment]
> Oh my, it seems the markdown parser has changed. The document is completely messed up. Thank you for fixing it. But in this way, a space is added after every bold text, which feels quite awkward in Korean documents. I’d like to check others' opinions as well.

Thanks

related to : 
https://github.com/fastapi/fastapi/pull/12148
https://github.com/fastapi/fastapi/pull/12142
https://github.com/fastapi/fastapi/pull/12141
https://github.com/fastapi/fastapi/pull/12136

**Comment by andychucs** [comment]
> Oh my, it seems the markdown parser has changed. The document is completely messed up. Thank you for fixing it. But in this way, a space is added after every bold text, which feels quite awkward in Korean documents. I’d like to check others' opinions as well.

It is caused by `pymdown-extensions`. See also: https://github.com/fastapi/fastapi/pull/12161

**Review by junah201 — APPROVED** [review]

**Comment by alejsdev** [comment]
Hi @sodaMelon

This was handled in PR #12509, it should be fixed now. so I'm going to close this one but thanks for the interest and effort! :raised_hands:

**Pull request closed without merging**
