### PR TITLE
🎨 Fix typing annotation for semi-internal `FastAPI.add_api_route()`

### LINKED ISSUE #10236: Inconsistent add_api_route types
### Discussed in https://github.com/tiangolo/fastapi/discussions/10235

<div type='discussions-op-text'>

<sup>Originally posted by **sidekick-eimantas** September 12, 2023</sup>
### First Check

- [X] I added a very descriptive title here.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/pydantic/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
### Direct mounting of routes
import pathlib

from fastapi import FastAPI, APIRouter
import uvicorn
import pydantic

class HelloRequest(pydantic.BaseModel):
    id: str


class HelloResponse(pydantic.BaseModel):
    hello: str


class Hello:
    def __init__(self, name: str) -> None:
        self.name = name

    async def handle(self, request: HelloRequest) -> HelloResponse:
        return HelloResponse(hello=self.name)

app = FastAPI()
hello_handler = Hello(name="test")
app.add_api_route("/hello", hello_handler.handle, methods=["POST"])






### Mounting of paths via Router
import pathlib

from fastapi import FastAPI, APIRouter
import uvicorn
import pydantic

class HelloRequest(pydantic.BaseModel):
    id: str


class HelloResponse(pydantic.BaseModel):
    hello: str


class Hello:
    def __init__(self, name: str) -> None:
        self.name = name

    async def handle(self, request: HelloRequest) -> HelloResponse:
        return HelloResponse(hello=self.name)


class RootRouter:
    def __init__(self, name: str):
        self.router = APIRouter()
        hello_handler = Hello(name=name)
        self.router.add_api_route("/hello", hello_handler.handle, methods=["POST"])


app = FastAPI()
root_router = RootRouter(name="test")
app.include_router(root_router.router)
```

### Description

First example produces a mypy error:
```
error: Argument 2 to "add_api_route" of "FastAPI" has incompatible type "Callable[[HelloRequest], Coroutine[Any, Any, HelloResponse]]"; expected "Callable[..., Coroutine[Any, Any, Response]]"  [arg-type]
```

Second example does not.

The types of `endpoint` parameter in `FastAPI.add_api_route` and `APIRouter.add_api_route` are inconsistent.

### Operating System

macOS

### Operating System Details

_No response_

### FastAPI Version

0.103.1

### Pydantic Version

2.3.0

### Python Version

3.10.7

### Additional Context

_No response_</div>

### PR DESCRIPTION
**Pull request by ordinary-jamie**
Closes #10236

Make typing of endpoint parameter consistent with downstream calls and other utilities.

Justification for picking `Callable[..., Any]` over original:

- `FastAPI.add_api_route` makes a direct call to `APIRouter.add_api_route` anyways 
- `fastapi.dependencies.utils.get_typed_return_annotation` has signature `def get_typed_return_annotation(call: Callable[..., Any]) -> Any:`
- A lot of other functions with similar parameters use the same typing (e.g. `FastAPI.add_api_websocket_route`)
- The api router instantiates `route_class: Type[APIRoute]` of which `fastapi.routing.APIRoute` subclasses [`starlette.routing.Route` which also types `endpoint` with `Callable[..., typing.Any]`](https://github.com/encode/starlette/blob/master/starlette/routing.py#L211-L215)

### CODE REVIEW

**Review by iudeen — APPROVED** [review]
I like the justification.

**Comment by danielfcollier** [comment]
As far as I've tested, this is missing the test coverage for issue #10236. Checked this modification with the tests and modification made on PR #10250 and this modification would be breaking the tests cases.

**Comment by ordinary-jamie** [comment]
Thanks @danielfcollier, can you send a link to the CI build / enumerate the tests that failed?

**Comment by danielfcollier** [comment]
Hi @ordinary-jamie , I've run locally. But, I've just put on this PR #10258 to show you what tests would be required to add coverage for Issue #10236.

There is still a more complex problem with generators, but I've left the tests for the generators case commented.

**Comment by merlinz01** [comment]
@danielfcollier @Kludex Could we have this merged please?

**Comment by tiangolo** [comment]
Awesome, thank you! :rocket: :cake:

**Pull request merged**
