### PR TITLE
⬆ Upgrade Starlette from 0.19.1 to 0.20.4

### PR DESCRIPTION
**Pull request by SogoKato**
## Summary

* Upgrade starlette from 0.19.1 to 0.20.4
  * 0.20.2 includes a fix for regression on route paths with colons [starlette#1675](https://github.com/encode/starlette/pull/1675), I added a test case for [custom method](https://cloud.google.com/apis/design/custom_methods).

### CODE REVIEW

**Comment by iudeen** [comment]
In order to bump starlette version, FastAPI has to drop support for Python 3.6. 

Currently FastAPI supports python 3.6.

**Comment by SogoKato** [comment]
> In order to bump starlette version, FastAPI has to drop support for Python 3.6.
> 
> Currently FastAPI supports python 3.6.

When do you expect to drop support for python 3.6?  
It is said that "This is probably the last release (or one of the last releases) to support Python 3.6." in the latest release notes.

**Comment by iudeen** [comment]
It's up to the maintainers of the project. I don't have an answer for when it'd be done🙂

**Comment by SogoKato** [comment]
Now https://github.com/tiangolo/fastapi/releases/tag/0.85.0 is released, I close this p-r.

**Comment by tiangolo** [comment]
Thanks for coming back to close the PR @SogoKato ! ☕

**Pull request closed without merging**
