### PR TITLE
📝 Update docs and translations, update references to UJSON, used by FastAPI, not Starlette

### PR DESCRIPTION
**Pull request by Kludex**
This points to Kludex-patch-1.

### CODE REVIEW

**Review by hasansezertasan — APPROVED** [review]

**Comment by tiangolo** [comment]
📝 Docs preview for commit 26ce3c89557d2d34aefb0c87c03500d040148bdb at: https://4b4b90a7.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
Thanks! I updated the translations as well. :nerd_face:

**Comment by tiangolo** [comment]
📝 Docs preview for commit 25772f52dd7c771ccc90ed602655c347969300d7 at: https://8e5fa1ef.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
I just realized that this PR doesn't go to `master`, but goes from `Kludex-patch-2` to `Kludex-patch-1` :sweat_smile: 

I remade the changes here https://github.com/tiangolo/fastapi/pull/11464

I'll merge that one, so I'll close this one. Thanks! :coffee:

**Pull request closed without merging**
