### PR TITLE
🐛 Fix support for path parameters in WebSockets

### PR DESCRIPTION
**Pull request by davidbrochart**
Because a path can look like `/files/{file_path:path}`, we need to strip the type (e.g. `:path`) of the parameter.

### CODE REVIEW

**Review by adam-tokarski — COMMENTED** [review]
Care to add some tests for that?

**Comment by davidbrochart** [comment]
> Care to add some tests for that?

Sure, let me know what you think.

**Review by adam-tokarski — APPROVED** [review]
Generally LGTM, but personally I'd 
* add more tests for not so happy paths, e.g. `"/path/{param::}"` or `"/path:smth/{param}"`
* introduce kind of [parametrized](https://pypi.org/project/parameterized/) (if available here), but it would not change too much

**Comment by davidbrochart** [comment]
> * add more tests for not so happy paths, e.g. `"/path/{param::}"` or `"/path:smth/{param}"`

Done.

> * introduce kind of [parametrized](https://pypi.org/project/parameterized/) (if available here), but it would not change too much

`parametrized` is not used in FastAPI yet, and it seems a bit overkill to me, so I didn't use it.

**Comment by ghandic** [comment]
The only person that can merge is @tiangolo he'll take a look at it soon

**Comment by davidbrochart** [comment]
@tiangolo do you think this can go in? We are currently [monkey-patching the change](https://github.com/jupyter-server/jupyverse/blob/b03b1423ecc31e674d2299a8bf97f6f65443ccf0/plugins/yjs/fps_yjs/routes.py#L18-L23) in Jupyter.

**Review by BilalAlpaslan — APPROVED** [review]

**Review by SylvainCorlay — APPROVED** [review]

**Comment by davidbrochart** [comment]
The Jupyter server still needs to [monkey-patch FastAPI](https://github.com/jupyter-server/jupyverse/blob/b03b1423ecc31e674d2299a8bf97f6f65443ccf0/plugins/yjs/fps_yjs/routes.py#L18-L23), is there any chance this change could go in?

**Comment by Kludex** [comment]
What's this for?

**Comment by Kludex** [comment]
I'll check later, but if you can answer "why this is not needed on the HTTP methods?" would be helpful.

**Comment by Kludex** [comment]
Also, just to set the expectations... I don't have merge rights. 👀

**Comment by davidbrochart** [comment]
> Also, just to set the expectations... I don't have merge rights. eyes

No worries, it's already great to have your feedback.

> I'll check later, but if you can answer "why this is not needed on the HTTP methods?" would be helpful.

Your question made me revisit the issue, and it turns out that there is a better fix.
The `APIWebSocketRoute` was not treated the same way as the `APIRoute`, as far as their dependant `path` is concerned. Passing `self.path_format` for the former, as it is done for the latter, fixes the issue in a much nicer way.

**Comment by Kludex** [comment]
Now it makes more sense. 👍 

A test checking that query and path params can be passed as expected might be a good idea. 👀

**Comment by davidbrochart** [comment]
> A test checking that query and path params can be passed as expected might be a good idea.

:+1: 
Without the fix, the test fails as expected:
```
tests/test_ws_router.py::test_router_with_params FAILED                                                                                       [100%]

===================================================================== FAILURES ======================================================================
______________________________________________________________ test_router_with_params ______________________________________________________________

    def test_router_with_params():
        client = TestClient(app)
>       with client.websocket_connect("/router/path/to/file?queryparam=a_query_param") as websocket:

tests/test_ws_router.py:120: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../mambaforge/envs/fastapi/lib/python3.10/site-packages/starlette/testclient.py:316: in __enter__
    self._raise_on_close(message)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <starlette.testclient.WebSocketTestSession object at 0x7fba1ed72ef0>, message = {'code': 1008, 'reason': '', 'type': 'websocket.close'}

    def _raise_on_close(self, message: Message) -> None:
        if message["type"] == "websocket.close":
>           raise WebSocketDisconnect(
                message.get("code", 1000), message.get("reason", "")
            )
E           starlette.websockets.WebSocketDisconnect: (1008, '')

../../../mambaforge/envs/fastapi/lib/python3.10/site-packages/starlette/testclient.py:357: WebSocketDisconnect
```

**Comment by Kludex** [comment]
This makes sense. 👍

**Comment by tiangolo** [comment]
Awesome, thank you @davidbrochart! :nerd_face: 

It's so exciting you are using FastAPI in some part of Jupyter!

Also thanks everyone for the help here! :rocket: 

This will be available in the next release, in some hours (the current is `0.81.0`). :tada:

**Pull request merged**
