### PR TITLE
Update tutorial001.py

### PR DESCRIPTION
**Pull request by gsganden**
Replace default `[]` with `set()` for set field. Same as https://github.com/tiangolo/fastapi/pull/2646/files but for a different file.

### CODE REVIEW

**Comment by gsganden** [comment]
I did some `grep`ping and caught a few more cases.

**Review by ycd — CHANGES_REQUESTED** [review]
This line conflicts #2646.

**Comment by gsganden** [comment]
Sorry, I'm not following what's happening. I think this PR makes the same change as #2646 and also makes the same change in a few other places. Would you like me to take out the one change that matches #2646?

**Comment by tiangolo** [comment]
Thanks for your contribution @gsganden! :bow: 

And thanks @ycd for the help! :cake: 

It seems this was also covered in another PR, so I'm gonna close this one. But thanks for the effort! :coffee:

**Pull request closed without merging**
