### PR TITLE
wrench: Use casefold for caseless comparison of schemes

### PR DESCRIPTION
**Pull request by Abdur-rahmaanJ**
[str.casefold()](https://docs.python.org/3/library/stdtypes.html?highlight=casefold#str.casefold) in the docs.

### CODE REVIEW

**Review by yezz123 — APPROVED** [review]
LGTM! 🎉

**Review by ycd — APPROVED** [review]

**Comment by harunyasar** [comment]
@Abdur-rahmaanJ I can't quite sure that what you were fixing here. Could you briefly explain why we need this change?  I am thinking that `str.lower()` will always work here perfectly because there shouldn't be any case of that we are supposed to support caseless matching for possible `Authorization` headers.

**Comment by Abdur-rahmaanJ** [comment]
Well, `.casefold` is recommended for caseless matching. That's what we are doing with .lower which works but is not recommended by the docs. `.lower` is for converting to lowercase.

**Comment by harunyasar** [comment]
@Abdur-rahmaanJ I can see where you are coming from but it doesn't add a value to replace `lower()` with `casefold()` because there won't be any case that we need to have a caseless matching for `Authorization` header schemes.

**Comment by Abdur-rahmaanJ** [comment]
Thanks for your comments, i don't think i have more to add.

**Review by TheOnlyWayUp — APPROVED** [review]

**Comment by tiangolo** [comment]
Thanks for the interest @Abdur-rahmaanJ! :coffee: 

As in this case the strings are plain ASCII, it wouldn't make much of a difference, so I'll just leave it as it is and I'll close this PR.

But thanks for the effort! :cake:

**Comment by Abdur-rahmaanJ** [comment]
@tiangolo ASCII for now ^^/ btw thanks for cleaning the PRs

**Pull request closed without merging**
