### PR TITLE
🌐 Fix Korean translation for `docs/ko/docs/tutorial/index.md`

### PR DESCRIPTION
**Pull request by ghost**
Added missing translation for "benefits" in `docs/ko/docs/tutorial/index.md`

This is the same PR I submitted a few days ago.

I accidentally deleted my forked repository, so I am resubmitting it. (Previous PR has been closed. 😢)

### CODE REVIEW

**Review by junah201 — APPROVED** [review]
LGTM

**Comment by junah201** [comment]
The PR he submitted a few days age is https://github.com/fastapi/fastapi/pull/12257

**Review by pengooseDev — APPROVED** [review]
Nice Catch. :) More clear to read.

**Comment by kkotipy** [comment]
@alejsdev

Could you please replace the `lang-pt` label with the `lang-ko` label?

I would greatly appreciate your help with this. Thank you!

**Comment by alejsdev** [comment]
Ups, my mistake, fixed! @kkotipy

**Comment by alejsdev** [comment]
Thank you! @kkotipy :nerd_face: :mag:

**Comment by alejsdev** [comment]
Thank you all for your contribution! @kkotipy @junah201 @pengooseDev :rocket:

**Pull request merged**
