### PR TITLE
✏️ Fix typo in `docs/en/docs/tutorial/dependencies/dependencies-with-yield.md`

### PR DESCRIPTION
**Pull request by s111d**

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit a8709780639e2078bb797ffb8d5872bd7f100cac at: https://04e9c583.fastapitiangolo.pages.dev

**Review by hasansezertasan — APPROVED** [review]
I have checked the entire documentation, there is not another "ot" typo.

**Review by alejsdev — APPROVED** [review]

**Review by JavierSanchezCastro — APPROVED** [review]

**Comment by tiangolo** [comment]
Good catch, thanks! @s111d 🔍 

And thanks for the reviews @hasansezertasan, @JavierSanchezCastro, @alejsdev 🙇

**Comment by tiangolo** [comment]
This was handled in https://github.com/tiangolo/fastapi/pull/10834, so I'll go ahead and close this one. Thanks! ☕

**Pull request closed without merging**
