### PR TITLE
Add cn translation for serveral sections of advanced user guide.

### PR DESCRIPTION
**Pull request by woostundy**
including:

index.md
path-operation-advanced-configuration.md
additional-status-codes.md
custom-response.md
response-directly.md

And more will be added later.

### CODE REVIEW

**Comment by dahuisong** [comment]
16qwwLpSDngpgkf3cBZbRPW39h9x3dvdMk

**Comment by dahuisong** [comment]
175JEbptSwRBh2h8QX4NEj7xCcvSdJNVMJ

**Comment by dahuisong** [comment]
> including:
> 
> index.md
> path-operation-advanced-configuration.md
> additional-status-codes.md
> custom-response.md
> response-directly.md
> 
> And more will be added later.

**Comment by tiangolo** [comment]
That's great! :tada:

Could you separate each file in a different PR?

If each file is in a different PR, it will be easier for others to review an entire PR and/or add comments to specific sections.

**Comment by waynerv** [comment]
The embarrassing thing is these 5 articles have already been translated by @RunningIkkyu . you should follow the contribution guide and check PR list to avoid duplicate work.

**Comment by woostundy** [comment]
> The embarrassing thing is these 5 articles have already been translated by @RunningIkkyu . you should follow the contribution guide and check PR list to avoid duplicate work.

It's my fault that I forgot to check.
But I find there are three sections translated in PR list: #1447 #1451 #1452 if I haven't miss others. 
So should I create new PRs for `index.md` and `custom-response.md` ?

**Comment by RunningIkkyu** [comment]
#1445  #1451 #1447 #1452 #1459 @woostundy Please review these files.

**Comment by waynerv** [comment]
Filtering PR list by label `lang-zh` and you will see all the Chinese translations.

**Comment by tiangolo** [comment]
As these translations have been added in other PRs I'm gonna close this one. Thanks! ☕

**Pull request closed without merging**
