### PR TITLE
updating sql-docs

### PR DESCRIPTION
**Pull request by xnpltn**
1. Change "item.dict()" to "item.model_dump()" . Because dict() method is deprecated and primitive. It is better practice to use updated version. 
2. Removed hard coded status codes and used "status" object.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit b55817cf81354b1b6066ac30de9cd42f11f3e0d5 at: https://b9f484d9.fastapitiangolo.pages.dev

**Comment by Xnpltn** [comment]
@tiangolo @Kludex @tokusumi can you review these changes?

**Comment by xnpltn** [comment]
@tiangolo @Kludex  can you review those changes?

**Review by nilslindemann — APPROVED** [review]
This is good in the context of `sql-databases.md`. However, there are many more appearances of `.dict` in the docs. #10052 could do that, as that PR´s title implies "whole docs" :-)

**Comment by tiangolo** [comment]
Thanks @xnpltn! ☕ 

And thanks for the help here @nilslindemann! 🙇 

The problem is that FastAPI is still compatible with Pydantic v1, and the examples are currently compatible with both Pydantic v1 and v2, updating them to use `.model_dump()` makes them no longer compatible with Pydantic v1.

To alleviate the problem a bit, I added notes to the docs suggesting people to use `.model_dump()`, while keeping the examples compatible with Pydantic v1 here: https://github.com/tiangolo/fastapi/pull/10929

Given that, I'll pass on this, but thanks for the effort! 🍰

**Pull request closed without merging**
