### PR TITLE
🌐 Update German translation for `docs/de/docs/tutorial/index.md`

### PR DESCRIPTION
**Pull request by nilslindemann**
Closed in favor of #9502 by fhabers21.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 792e8d5dbf2d3d8b383c2e674d67ca06bf59b675 at: https://cc9c4695.fastapitiangolo.pages.dev

**Comment by GeorchW** [comment]
I think this has been done before, too: https://github.com/tiangolo/fastapi/pull/9502
This is true for multiple of your PRs. Could you check which of the PRs (both yours and the existing ones) should maybe be merged and which should be closed?

**Comment by nilslindemann** [comment]
@GeorchW "See the commit description" ;-)
#9502 can be closed, this one is based on it.

For an explanation why I recreated some PRs, see [here](https://github.com/tiangolo/fastapi/pull/10290#issuecomment-1727557863).

**Comment by nilslindemann** [comment]
@GeorchW @tiangolo 

To be precise,

#10283 is based on #3631
#10284 is independent
#10285 is based on #3048
#10287 is based on #3048
#10288 is based on #9502
#10289 is based on #9530
#10290 is independent
#10293 is independent
#10295 is independent

#3631, #3048, #9502 and #9530 can be closed. My PRs contain them (I have the original documents from these PRs in my [workbranch](https://github.com/nilslindemann/fastapi/tree/deutsche-uebersetzung-arbeitsbranch)), add translations, fix errors, and sync to the current English docs.

#10281 by @DevSpace88 and #10290 by me is an accidental clash. See [here](https://github.com/tiangolo/fastapi/pull/10290#issuecomment-1727557863). Others may decide which is better. It is ok if you close mine, because it was later. I now check the [List of PRs](https://github.com/tiangolo/fastapi/pulls) before every new translation. I also post [here](https://github.com/tiangolo/fastapi/discussions/9203?sort=old#discussioncomment-7057889) on which translation I am currently working.

My following PRs (since #10290) will not cause this problem anymore, because there exists no translation for these documents. I go through the documents in the order they are listed in the [docs ](https://fastapi.tiangolo.com/).

**Comment by tiangolo** [comment]
📝 Docs preview for commit 6a7c88f4e669d5840bf03210b797e6b94f1f151a at: https://967ccac3.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 9cee7c8408de9d60b8fa59d222dcc37ece1607a2 at: https://9075d2f7.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 698749f0424894080f7351a731e5df6632c867f5 at: https://21ac2245.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 13f55256f8e485d664becb722c84a456a9ae478b at: https://27e1fece.fastapitiangolo.pages.dev

**Comment by fhabers21** [comment]
#9530 already has one approval, so if you tell me what I should change, and afterwards you review it, we could get it merged.

#9502 has not been reviewed yet, but I could close it (though I don't really understand what's wrong with it).

**Comment by tiangolo** [comment]
📝 Docs preview for commit bc85132eb84e627475a4114d3846af3c3e925f49 at: https://2a7afc89.fastapitiangolo.pages.dev

**Comment by nilslindemann** [comment]
Hello @fhabers21,

I do not know anymore why I recreated your PRs. If you do not mind, I will close my PRs and point to yours.

Give me a moment, I need to update a few of my translations with better wordings, inspired by your translations.

Greetings, Nils

**Pull request closed without merging**
