### PR TITLE
🌐 Add Korean translation for `docs/ko/docs/deployment/server-workers.md`

### PR DESCRIPTION
**Pull request by jujumilk3**
Translates docs/ko/docs/deployment/server-workers.md and add deploy menu in Korean.
related: https://github.com/tiangolo/fastapi/issues/2017

### CODE REVIEW

**Review by hard-coders — COMMENTED** [review]
As I mentioned at https://github.com/tiangolo/fastapi/discussions/3167#discussioncomment-3187582,
"구니콘" is more proper than "규니콘"

**Review by hard-coders — APPROVED** [review]
LGTM 👍

**Comment by tiangolo** [comment]
📝 Docs preview for commit 3baea96900ad290a272b31ff6d56694ebb785ac5 at: https://649a1d12cc19e515a6cacf72--fastapi.netlify.app

**Comment by alejsdev** [comment]
Thank you! @jujumilk3 😄 

And thanks for the review @hard-coders 🔍

**Pull request merged**
