### PR TITLE
📝 Update `import` of `declarative_base` function to new location

### PR DESCRIPTION
**Pull request by jmnguye**
declarative_base functions have been move

The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
    Base = declarative_base()

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 4def93e1727643609e9008ee9f381e15082e11bd at: https://4f7a467a.fastapitiangolo.pages.dev

**Comment by jmnguye** [comment]
sorry, but it's the first time that i made a PR, i think you want me to check that the doc is now correct at https://4f7a467a.fastapitiangolo.pages.dev/tutorial/sql-databases/ but it's not, the import is still the old one

**Comment by harunyasar** [comment]
@jmnguye I've noticed that you've only updated a single line, but it appears there are multiple lines that need to be changed. Would you mind updating all the old `declarative_base` imports in the relevant documents?

**Comment by tiangolo** [comment]
📝 Docs preview for commit 8d26a3279aeb8fcbbdfad27f18af5aff38ef9a02 at: https://88716ee5.fastapitiangolo.pages.dev

**Comment by jmnguye** [comment]
Sorry i haven't noticed, it should be fine now

**Review by mstenta — APPROVED** [review]

**Comment by jmnguye** [comment]
It has been approved, but I wonder, do i need to do something, to have it merged?

**Comment by afsharsharifi** [comment]
Just Change
`from sqlalchemy.ext.declarative import declarative_base`
To
`from sqlalchemy.orm import declarative_base`

**Review by svlandeg — APPROVED** [review]
Thanks for the PR @jmnguye! This edit looks correct to me - `declarative_base` has indeed been moved.

**Pull request closed without merging**
