### PR TITLE
🌐 Add Portuguese translation for `docs/pt/docs/reference/index.md`

### PR DESCRIPTION
**Pull request by lucasbalieiro**

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 762c5c41a76517888054b881fa2f5b2291ed4ff8 at: https://2ce7329a.fastapitiangolo.pages.dev

**Review by nazarepiedady — APPROVED** [review]
It is great to be applied to the main branch. It is a well-done work.

Thanks for your valuable contribution.

**Review by ceb10n — APPROVED** [review]
Great translation ✨

**Comment by alejsdev** [comment]
Wuju! One more ready, cool. Thanks! :partying_face: @lucasbalieiro @nazarepiedady @ceb10n

**Pull request merged**
