### PR TITLE
🌐 Add Portuguese translation for `docs/pt/docs/how-to/separate-openapi-schemas.md`

### PR DESCRIPTION
**Pull request by ilacftemp**

### CODE REVIEW

**Review by nazarepiedady — APPROVED** [review]

**Review by cassiobotaro — APPROVED** [review]

**Comment by ilacftemp** [comment]
I tried making another pull request from my fork branch, but i accidentally commited it in this same pull request. Is there a way to separate the commits into the two pull requests?

**Comment by nazarepiedady** [comment]
> I tried making another pull request from my fork branch, but i accidentally commited it in this same pull request. Is there a way to separate the commits into the two pull requests?

@ilacftemp, pull requests are made by using branches, so if you want to separate two commits into two pull requests you must put each one commits into a branch then to do the pull request using each branch separately.

I hope have to be clear or understandable. 😊

**Comment by ilacftemp** [comment]
Thanks @nazarepiedady !! That helped me correct this and change that other commit to a pull request :)

**Comment by alejsdev** [comment]
Thanks for your contribution! @ilacftemp :nerd_face: 

And thanks for the help @nazarepiedady @cassiobotaro :v:

**Pull request merged**
