### PR TITLE
🌐 Add Chinese translation for `docs/zh/docs/how-to/index.md`

### PR DESCRIPTION
**Pull request by KAZAMA-DREAM**
🌐 Add Chinese translation for `docs/zh/docs/how-to/index.md`

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 5231a80e72e036fb31d8cbb9de495d3cbe3ab7d8 at: https://2ac05a96.fastapitiangolo.pages.dev

**Comment by waketzheng** [comment]
@KAZAMA-DREAM 大兄弟，这个已经过期了，要不你再提交新的一版？

**Comment by svlandeg** [comment]
This page has been translated by another PR https://github.com/fastapi/fastapi/pull/11443, so I think we can close this one.

Thanks @KAZAMA-DREAM for the efforts here though, we definitely appreciate any contribution in writing and reviewing Chinese PRs! 🙏

**Review by svlandeg — COMMENTED** [review]
This page has been translated by another PR https://github.com/fastapi/fastapi/pull/11443, so I think we can close this one.

Thanks @KAZAMA-DREAM for the efforts here though, we definitely appreciate any contribution in writing and reviewing Chinese PRs! 🙏

**Pull request closed without merging**
