### PR TITLE
🌐 Add German translation for `docs/de/docs/how-to/separate-openapi-schemas.md`

### PR DESCRIPTION
**Pull request by nilslindemann**
← `how-to/extending-openapi.md` (#10794)
→ `how-to/custom-docs-ui-assets.md` (#10803)

[German translation progress](https://github.com/tiangolo/fastapi/discussions/10582)

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit be031b6592c491f37186fc52ef648311787d3fd6 at: https://5cab561e.fastapitiangolo.pages.dev

**Comment by nilslindemann** [comment]
Sorry about the force push, I amended the commit in the wrong branch, and the "undo" button in GitHub Desktop is not what it seems to be.

**Comment by tiangolo** [comment]
📝 Docs preview for commit 85d481c55d76ba023974563a85bf0a8803e00cbc at: https://b2551932.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit fc558d15c4c96ccfabb79e168e341e3e38792e55 at: https://6b91f430.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
Awesome @nilslindemann! :rocket: 

As you are the champion of German translations and you have done so many, and with so much attention to detail, I'm gonna go ahead and merge this. :tada: 

If others see things that could be improved later, we can check that in new PRs. :nerd_face:

**Pull request merged**
