### PR TITLE
🌐 Add German translation for `docs/de/docs/advanced/events.md`

### PR DESCRIPTION
**Pull request by nilslindemann**
← `advanced/websockets.md` (#10687)
→ `advanced/testing-websockets.md` (#10703)

[German translation progress](https://github.com/tiangolo/fastapi/discussions/10582)

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 0850e8b5909405e79f35bf8b1bf645a8424263f6 at: https://5a6f17b0.fastapitiangolo.pages.dev

**Comment by jacob-indigo** [comment]
Just a heads up. I put up a PR adding a waning related to backwards compatibility to the english version of this doc page: https://github.com/tiangolo/fastapi/pull/10734

**Comment by nilslindemann** [comment]
Thanks for the awareness, @jacob-indigo. GitHub shows me in my [forks master branch](https://github.com/nilslindemann/fastapi) when there are updates in tiangolos master branch. I check this regularly, and I will see and sync it, when tiangolo merges your PR.

**Comment by tiangolo** [comment]
📝 Docs preview for commit 96684c85da41dcbc56223a5097a55aaf43d22740 at: https://5becc854.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 4c51a8985f8e950446a480c770658805fadf3451 at: https://98c3c8bb.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 5c1b709907c4121d96cc23d2640b6391658c2f45 at: https://b92965a1.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit b9e5770b7afd4c7b89f666842f9d89487cc1eb26 at: https://0de0058e.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 743d546f671142d16360a61a952650f5fdd61680 at: https://2c1a78fc.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
Awesome @nilslindemann! :rocket: 

As you are the champion of German translations and you have done so many, and with so much attention to detail, I'm gonna go ahead and merge this. :tada: 

If others see things that could be improved later, we can check that in new PRs. :nerd_face:

**Pull request merged**
