### PR TITLE
Add Open API prefix route - correct docs behind reverse proxy

### PR DESCRIPTION
**Pull request by kabirkhan**
I run a lot of services in Kubernetes using [Ambassador](https://www.getambassador.io/) as my API Gateway. Ambassador allows you to configure a route prefix for each one of your services and then it handles ingress and routing to the initial service. This PR enables me to configure the same prefix I use with Ambassador in the Swagger UI API docs.

Example:
```python
prefix='/service1'

app = FastAPI(
    openapi_prefix=prefix
)
@app.get('/something') => SwaggerRoute (GET - /service1/something)
```

NOTE: This is not the same as using the include_router method and adding a prefix.
This is meant only to rewrite the route paths in the Swagger UI.

BTW: Awesome Project! Thanks so much for your work on this, I'm using fastapi a ton these days.

### CODE REVIEW

**Comment by kabirkhan** [comment]
Fix for https://github.com/tiangolo/fastapi/issues/15

**Comment by kabirkhan** [comment]
@tiangolo would you mind taking a look at this? 
I'm happy to add documentation once you review the approach.
I'd love to use the official pypi package rather than my own Github version for a production service at work.
Thanks

**Comment by tiangolo** [comment]
Great job @kabirkhan ! Thanks a lot. :tada: :taco: 

I added tests and docs on top of your work.

> for a production service at work

Are you using it at MS? That's very cool!

**Comment by tiangolo** [comment]
I just released `0.4.0` including this PR. You should be able to use it now. :rocket: 

Also, the relevant docs are here: https://fastapi.tiangolo.com/tutorial/sub-applications-proxy/

**Comment by kabirkhan** [comment]
@tiangolo yep I'm actually planning to use it for all of my team's ML services at Microsoft. Some of them are getting integrated into the core Windows product and some Office products.

Great job with the documentation too!

**Comment by tiangolo** [comment]
That's awesome! :taco: :cake: :rocket: 

May I quote it (that you at MS are using FastAPI)?

**Comment by kabirkhan** [comment]
Yeah, go for it!

**Comment by sm-Fifteen** [comment]
I know this is an old issue/PR, but shouldn't `root_path` be used instead of adding a custom parameter to the application? `root_path` is already the intended mechanism for routing under a mounted subapplication and what Uvicorn and the ASGI spec in general uses to tell the root application what its URL prefix is (it is ignored when routing, but must be taken into account when reconstructing URLs). FastAPI [currently does not acknowledge `root_path` in its API documentation](https://github.com/tiangolo/fastapi/blob/90236c813550030040474a7714428cf1fcc4f582/fastapi/openapi/utils.py#L283-L291), only  `openapi_prefix`, which means the routes specified by the API doc and the ones that are actually understood by the application will not match unless the value of `root_path` is also passed as `openapi_prefix` when creating the FastAPI application.

**Comment by luckydonald** [comment]
Huh, sounds about right. @sm-Fifteen you may open a new issue for that.

**Comment by tiangolo** [comment]
Yeap @sm-Fifteen, I just merged https://github.com/tiangolo/fastapi/pull/1199 addressing `root_path` :rocket:

**Comment by jkoech** [comment]
@tiangolo seems the link to the [prefix route docs](https://fastapi.tiangolo.com/tutorial/sub-applications-proxy/) is broken. Perhaps did the docs move?

> I just released `0.4.0` including this PR. You should be able to use it now. 🚀
> 
> Also, the relevant docs are here: https://fastapi.tiangolo.com/tutorial/sub-applications-proxy/

**Pull request merged**
