### PR TITLE
✏️ Fix link in `fastapi-cli.md`

### PR DESCRIPTION
**Pull request by svlandeg**
As reported on [Twitter](https://twitter.com/lucabaggi_/status/1786271218758242771): the link gave a 404 as the `index.md` page doesn't exist.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 78b74c88f673286a8c0c98fe52479f90afc3f0e8 at: https://e57e68dc.fastapitiangolo.pages.dev

**Comment by svlandeg** [comment]
Link looks like it's fixed: https://e57e68dc.fastapitiangolo.pages.dev/fastapi-cli/

**Comment by tiangolo** [comment]
Thank you! :cake: 

I tweaked it a bit to remove the `../` and point to the `index.md` so that MkDocs can detect it as an internal file and warn when it points to a different place (I should include those checks in the tests :thinking: ).

**Comment by tiangolo** [comment]
📝 Docs preview for commit e038e493200841b597a6002ce8f43a662a64da1e at: https://5d1fa315.fastapitiangolo.pages.dev

**Pull request merged**
