### PR TITLE
🌐 Update Polish translation for `docs/pl/docs/features.md`

### PR DESCRIPTION
**Pull request by isulim**

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 3b31ff0be694b9c477843a29e3c49de1fe9512a3 at: https://baf342b4.fastapitiangolo.pages.dev

**Review by rafsaf — APPROVED** [review]
Overall mostly good improvements, there are some parts where I'm not sure of why the current version is worse, but won't hurt to change it (just some different, but also valid syntax), I'm not some Polish language teacher after all.

:)

**Comment by tiangolo** [comment]
Thanks @isulim! ☕ 

And thanks for the review @rafsaf 🤓 

It seems this has conflicts with the latest version, would you be able to fix them?

**Comment by tiangolo** [comment]
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

**Pull request closed without merging**
