### PR TITLE
🌐 Update Chinese translation for `docs/zh/docs/reference/*`

### PR DESCRIPTION
**Pull request by binaryYuki**
Apologise for any inconvenient

This is the fixed version of #11597

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit b9c5310c04aedc2e0e62d4740dc629b39f275d93 at: https://6fb13866.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 06e46318201e8261a3d483ecc651f4988cb1eb6e at: https://f0aa103a.fastapitiangolo.pages.dev

**Review by Aruelius — APPROVED** [review]

**Comment by tiangolo** [comment]
📝 Docs preview for commit 7d31bea4f4b180466d95ff78ad2bdcd3d44f80e2 at: https://724b70b7.fastapitiangolo.pages.dev

**Review by wdh99 — CHANGES_REQUESTED** [review]
后台任务这一节，“您可以直接从 fastapi 中导入该参数：”表述不准确, “该参数”需要去掉, 因为导入的是一个类。
HTTPConnection 类一节，“您可以从 fastapi.requests 中导入该参数：”表述不准确, “该参数”需要去掉。
Response 类一节，“您可以将路径操作函数或依赖关系中的参数声明为 Response 类型，然后为响应设置数据，如标题或 cookie。” headers中文一般翻译作“请求头”，也可以直接保留headers不翻译；cookie少了一个s。

**Comment by binaryYuki** [comment]
感谢 @wdh99 的指正
已修改

**Comment by tiangolo** [comment]
📝 Docs preview for commit 57ac41608cef36c3b8e55172eae799928b63707c at: https://a8087cec.fastapitiangolo.pages.dev

**Review by wdh99 — APPROVED** [review]

**Comment by tiangolo** [comment]
📝 Docs preview for commit c21dbb1e1f400b457323bf26b69c22e502afd9c0 at: https://a0336d6c.fastapitiangolo.pages.dev

**Comment by binaryYuki** [comment]
Hi @alejsdev,

Hope everything goes well.

Would you like to review this pr if possible?

**Review by nick-cjyx9 — APPROVED** [review]

**Comment by binaryYuki** [comment]
抱歉各位 之前 merge 了改动 所以可能需要麻烦各位重新审核一下 谢谢～

**Comment by tiangolo** [comment]
Thank you! But as the reference includes the content of the docstrings from the internal code, translating it would mean that only some bits would really be translated, the rest would be included in English. But it would still require synchronizing it when there are updates in the original. So I prefer not having translations of the reference, only the rest of the docs.

Given that, I'll pass on this one, but thanks for the effort! :cake:

**Pull request closed without merging**
