### PR TITLE
Normalise IntEnums to ints for route status codes

### LINKED ISSUE #1349: [FEATURE] Support HTTPStatus
### Is your feature request related to a problem

We typically use [HTTPStatus](https://docs.python.org/3/library/http.html#http.HTTPStatus) in our code. When used as a value for `status_code` in path functions this results in the string literal in the documentation and when "trying" the response is shown as undocumented because it doesn't match the actual response code

### The solution you would like

I want to use HTTPStatus enum values and have it work exactly like the `starlette.status` pseudo enum values

### PR DESCRIPTION
**Pull request by retnikt**
Fixes/related to #1349

### CODE REVIEW

**Comment by retnikt** [comment]
@tiangolo do you have any guidance on where to test this? (as in, which `tests/test_*.py` file)

**Comment by Kludex** [comment]
Probably on: `test_custom_route_class.py`
As is the only test that imports the `routing` module.

**Comment by retnikt** [comment]
@Kludex I decided to put it in `tests/test_application.py` because that's where the OpenAPI schema seems to be tested.

**Comment by tiangolo** [comment]
Great job @retnikt ! :bow: :nerd_face: :tada: 

Thanks @Kludex for the help! :coffee:

**Pull request merged**
