### PR TITLE
🌐 Update Chinese translation for `docs/zh/docs/tutorial/dependencies/dependencies-with-yield.md`

### PR DESCRIPTION
**Pull request by xuvjso**
https://github.com/fastapi/fastapi/pull/10831 ensures that the code following `yield` executes after the response is create but before it is sent to the client. The statement in https://github.com/fastapi/fastapi/issues/3620#issuecomment-888081460 was outdated, it is now safe to commit the session after `yield` as the code is guaranteed to execute after the response is created but before it is sent.
```python
def get_db() -> Session:
    session = SessionLocal()
    try:
        yield session
        session.commit()
    except:
        session.rollback()
        raise
    finally:
        session.close()
```

### CODE REVIEW

**Comment by estebanx64** [comment]
Thanks for your time and interest in helping us! 🙇

We are going to review these little changes 🤓

**Comment by xuvjso** [comment]
I noticed that the chinese version of the "dependencies with yield" section of the documentation is outdated, so I provided an updated translation to prevent users from being misled by outdated information and to align with the latest English documentation.

**Review by Aruelius — APPROVED** [review]

**Comment by alejsdev** [comment]
Hi @xuvjso 
Thanks for your interest in contributing to FastAPI :bowing_woman: 
To avoid problems with the labels. Could you better separate the EN from the ZH docs in another PR? Thanks in advance! :pray:

**Comment by alejsdev** [comment]
Great! Thanks for your contribution :partying_face: @xuvjso 
And thanks for the review @Aruelius :100:

**Comment by xuvjso** [comment]
> Great! Thanks for your contribution 🥳 @xuvjso And thanks for the review 💯 @Aruelius

It's my pleasure. 😊

**Pull request merged**
