### PR TITLE
📝 Fix types in examples under `docs_src/extra_data_types`

### PR DESCRIPTION
**Pull request by nilslindemann**
Before, the type checker would complain when [adding/subtracting these values](https://github.com/tiangolo/fastapi/blob/1c25e2d8dc99331290e99e17814ec4d83adce725/docs_src/extra_data_types/tutorial001_py310.py#L17-L18), as they can be None.

I made the parameters `start_datetime`, `end_datetime`, and `process_after` non-optional. Then I moved the remaining keyword parameter `repeat_at` to the end.

The code block highlights in the docs do not need to be updated, no new lines are added or removed.

The related five tests are updated accordingly: `pytest tests/test_tutorial/test_extra_data_types -k=test_openapi_schema` succeeds.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit da837b9bd0a5176b22a5308806483d59bc56b565 at: https://52deab3a.fastapitiangolo.pages.dev

**Comment by nilslindemann** [comment]
Sorry about the failing tests. I guess the response now has a different JSON body.

* I could need help how to access the JSON body. Tried to print it out in `tests/test_tutorial/test_extra_data_types/test_tutorial001_an_py310.py` but for reasons I do not know this will not get printed to the console.
* I could need help how to just run the tests under `tests/test_tutorial/test_extra_data_types`.

**Comment by tiangolo** [comment]
📝 Docs preview for commit e1e9f4432910b44d7587793f30d63a6f150548a8 at: https://0d69f37b.fastapitiangolo.pages.dev

**Comment by nilslindemann** [comment]
I do not understand why the Pydantic v1 Tests fail

**Comment by tiangolo** [comment]
📝 Docs preview for commit 4d4838af5c1c1002d1e6d4eb6a624bc0773b0c2e at: https://a4be5950.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 1a7ecfbd44c1f7a9240952731038d11880d0e540 at: https://3b605061.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 1c96bf2c6241edf2ba96378cbec4038c37c16c84 at: https://52ce1208.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 68f436f2b2b324ddb48e3a58e480f3c56a004db7 at: https://4c3c0b74.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit e0779a175ae2a67e66c300e1eb08a3c88febc87f at: https://a2fc4c0a.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 65378abcc051fed4040d352652928b9c163ba431 at: https://7be3a19f.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit bb2d84f7204eb50846535c64a3ffc6e3d83c2f00 at: https://1bd40871.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
Great, thank you @nilslindemann! :rocket: 

I updated the tests a bit to remove some `IsDict` that are no longer necessary after your update. :nerd_face:

**Comment by nilslindemann** [comment]
Thanks @tiangolo !

**Pull request merged**
