### PR TITLE
Pass in redirect_slashes

### PR DESCRIPTION
**Pull request by lieryan**
Currently, `redirect_slashes` option that is used to turn off automatic redirection of trailing slash, which is available from Starlette but doesn't work in FastAPI.

### CODE REVIEW

**Review by yezz123 — COMMENTED** [review]
for what this needs to be true, I guess that could be better if the user have the responsibility on what he want to pass.

> trailing slashes are purely conventional, and Google does not care whether you use them; as long as you're consistent.

**Review by BilalAlpaslan — APPROVED** [review]

**Comment by lieryan** [comment]
@yezz123 generally, for websites it is often sensible to automatically redirect slashes and non-slash URL as identical since users might have copied or typed the URLs by hand and forgot the last slash; but API URLs are generally handled by machines, so that usability consideration doesn't apply. Moreoever, having two different endpoints for your API can silently cause issues if the API client used the wrong URL, and caching, ETag, etc becomes problematic. So, generally for APIs, I would always recommend just turning off slash redirect, so that API clients breaks hard and gets fixed rather than just silently doing the wrong thing.

**Comment by JarroVGIT** [comment]
Interesting, I am curious to know how @tiangolo envisioned this working. It seems that even if you create your own `APIRouter` with the setting to false, it would be overridden by the setting in the main `APIRouter` when you call `include_router()`. That is strange. I would be in favour of this PR.

**Review by JarroVGIT — APPROVED** [review]
This is however a duplicate of #3432 (and that PR did provide additional tests).

**Comment by tiangolo** [comment]
Thanks everyone for the discussion here! ☕ 

And thanks @JarroVGIT for the pointer to the other PR. 🤓 

Is this is already solved in that PR, I'll go ahead and close this one.

**Pull request closed without merging**
