### PR TITLE
translated docs/tutorial/static-files.md for Korean community.

### PR DESCRIPTION
**Pull request by JungWooGeon**
Add Korean translation for docs/tutorial/static-files.md

### CODE REVIEW

**Comment by joonas-yoon** [comment]
is this duplicate of #2957?

**Comment by JungWooGeon** [comment]
> is this duplicate of #2957?

No. I check #2957 and will close this PR.
Thanks for the review.

**Comment by joonas-yoon** [comment]
Many thanks for your great works and happy to meet you.

I am sorry to hear you this was closed. I won't this happends again, so I wrote the checklist - https://github.com/tiangolo/fastapi/discussions/3167#discussioncomment-3335089 - and the korean translated page in nightly version (check it in comment)

**Comment by tiangolo** [comment]
Thanks for the help and interactions here! 😁🍰☕

**Pull request closed without merging**
