### PR TITLE
🌐 Add Portuguese translation for `docs/pt/docs/how-to/index.md`

### PR DESCRIPTION
**Pull request by vhsenna**
Added portuguese translation for `docs/pt/docs/how-to/index.md`

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 3dc1490cc5b7dd40db461c73b8ab37720de17555 at: https://18bf256a.fastapitiangolo.pages.dev

**Comment by ceb10n** [comment]
Good translation @vhsenna 

looks ok to me

**Review by ceb10n — APPROVED** [review]
Look good to me ;) Thank you

**Comment by alejsdev** [comment]
Thanks for the help! :partying_face: :100:  @vhsenna @ceb10n

**Pull request merged**
