### PR TITLE
Update models.py

### PR DESCRIPTION
**Pull request by tsv19su**
tweaked a little

### CODE REVIEW

**Comment by JarroVGIT** [comment]
Could you perhaps merge all these changes together? 

https://github.com/tiangolo/fastapi/pull/5016
https://github.com/tiangolo/fastapi/pull/5013
https://github.com/tiangolo/fastapi/pull/5012
https://github.com/tiangolo/fastapi/pull/5011
https://github.com/tiangolo/fastapi/pull/5010
https://github.com/tiangolo/fastapi/pull/5009
https://github.com/tiangolo/fastapi/pull/5008

They are all style based, so if accepted they can be accepted in one go. 

On the PR's itself: they are against PEP-8 in terms of indentation. See [here](https://peps.python.org/pep-0008/#indentation) for more information.

Example of correct indentation:
```python
def long_function_name(
        var_one, var_two, var_three,
        var_four):
    print(var_one)
```

Often in your cases, you outline everything to the first param, which you keep on the same line as the function call, for example (from applications.py):

```python
            self.openapi_schema = get_openapi(title=self.title, 
                                               version=self.version, 
                                               openapi_version=self.openapi_version, 
                                               description=self.description, 
                                               terms_of_service=self.terms_of_service, 
                                               contact=self.contact, 
                                               license_info=self.license_info, 
                                               routes=self.routes, 
                                               tags=self.openapi_tags, 
                                               servers=self.servers, )
```

In this case, PEP-8 compliant style would be:
```python
            self.openapi_schema = get_openapi(
                 title=self.title,
                 version=self.version,
                 openapi_version=self.openapi_version,
                 description=self.description,
                 terms_of_service=self.terms_of_service,
                 contact=self.contact,
                 license_info=self.license_info,
                 routes=self.routes,
                 tags=self.openapi_tags,
                 servers=self.servers,
             )
```
which, it already is. Would vote against all these PR's as not PEP-8 compliant as the rest of the source code.

**Review by JarroVGIT — CHANGES_REQUESTED** [review]
Recommend to retract, as it is not PEP-8 compliant. See https://github.com/tiangolo/fastapi/pull/5016#issuecomment-1152278151 as well.

**Comment by tsv19su254052** [comment]
have no objection

**Comment by tiangolo** [comment]
Thanks for the interest! FastAPI uses Black for formatting, and pre-commit to enforce it. In fact, it fixes the format and commits on top of PRs in CI, that's why you see a commit on top of yours and why it seems the PR has no changes.

As format is already handled, I'll close this PR now. But thanks for the interest! :coffee:

**Pull request closed without merging**
