### PR TITLE
🌐 Add Korean translation for `docs/ko/docs/tutorial/security/simple-oauth2.md`

### PR DESCRIPTION
**Pull request by KdHyeon0661**
- Add Korean translation for docs/ko/docs/tutorial/security/simple-oauth2.md
- Related [FEATURE] Korean translations https://github.com/tiangolo/fastapi/issues/2017

### CODE REVIEW

**Review by PraveenNanda124 — COMMENTED** [review]
Good work

**Comment by tiangolo** [comment]
📝 Docs preview for commit 0dc9d2b6587b656196b0341293fce731e5bed76f at: https://649a1c18443f2f149e86527b--fastapi.netlify.app

**Comment by tiangolo** [comment]
Thank you! I'm still waiting for others to review this to be able to merge it, meanwhile, maybe you could help me review some of the other Korean translations, that way if they are approved by each other, I could merge them. :nerd_face: 

https://github.com/tiangolo/fastapi/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Alang-ko+label%3Aawaiting-review

**Review by junah201 — APPROVED** [review]

**Comment by alejsdev** [comment]
Thanks for the help! :partying_face: :tada: @KdHyeon0661 @PraveenNanda124 @junah201

**Pull request merged**
