### PR TITLE
🌐 Add Chinese translation for `docs/zh/docs/how-to/general.md`

### PR DESCRIPTION
**Pull request by KAZAMA-DREAM**
🌐 Add Chinese translation for `docs/zh/docs/how-to/general.md`

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit be17fe0077fc1af5203f86cbe2092333a5882726 at: https://5501fe1f.fastapitiangolo.pages.dev

**Comment by KAZAMA-DREAM** [comment]
hello,this label is wrong，should be lang-zh

**Comment by tiangolo** [comment]
Thank you @KAZAMA-DREAM!

**Comment by codespearhead** [comment]
@KAZAMA-DREAM Do you have the bandwidth to act on the suggested changes?

**Comment by tiangolo** [comment]
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

**Pull request closed without merging**
