### PR TITLE
🌐 Add Russian translation for `docs/ru/docs/about/index.md`

### PR DESCRIPTION
**Pull request by s111d**

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 936fc2b36c198336cafb957762cc56a73f329c14 at: https://8a3f234b.fastapitiangolo.pages.dev

**Comment by codespearhead** [comment]
Do you happen to know three Russian developers you can ask a [PR review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) from? [This](https://github.com/tiangolo/fastapi/pulls?q=is%3Apr+is%3Aopen+Russian) might help.

**Comment by s111d** [comment]
> Do you happen to know three Russian developers you can ask a [PR review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) from? [This](https://github.com/tiangolo/fastapi/pulls?q=is%3Apr+is%3Aopen+Russian) might help.

Yes, exactly what I was going to do. Just a tiny bit busy right now.

**Review by eVery1337 — APPROVED** [review]

**Comment by alejsdev** [comment]
Thanks for the help! @s111d @eVery1337 :rocket: :sparkles:

**Pull request merged**
