### PR TITLE
docs: update markdown formatting in zh-hant learn

### PR DESCRIPTION
**Pull request by jiawei-hong**
## Summary

I noticed that the `zh-hant` learn block is weird, Now it looks like the below image

Screenshot 2024-10-11 at 11 45 05

I made some changes so that it looks great

### CODE REVIEW

**Review by yychanlee — APPROVED** [review]

**Review by mattwang44 — APPROVED** [review]

**Comment by codingjenny** [comment]
@alejsdev please review this PR, it's just a little markdown error like the image below. Thank you!

Before:
截圖 2024-10-20 下午4 25 18

After:
截圖 2024-10-20 下午4 22 35

**Comment by mattwang44** [comment]
Please note that spaces should not be placed between Chinese characters, and I consider this PR to be a workaround.

A space should not be required for such Markdown syntax (e.g. GitHub markdown renders <code>\*\*bold\*\*and\*italic\*and\*\*bold\*\*</code> as **bold**and*italic*and**bold**), so there may be an issue with MkDocs' Markdown renderer.

If you search the index page of the FastAPI doc (`https://fastapi.tiangolo.com/zh-hant/`) on the [Wayback Machine](https://web.archive.org/), you'll find that the page was rendered correctly in older snapshots. The last snapshot that rendered well was taken on July 31st, 2024 ([link](https://web.archive.org/web/20240731061243/https://fastapi.tiangolo.com/zh-hant/#_2)). However, it appears corrupted in the next snapshot taken on August 6th, 2024 ([link](https://web.archive.org/web/20240806104830/https://fastapi.tiangolo.com/zh-hant/#_2)).

- Snapshot of the index page on July 31st:
    image
- Snapshot of the index page on August 6th:
    image

**Comment by jiawei-hong** [comment]
Hi @mattwang44 @codingjenny 

I agree that there can be no white space in Chinese. A short-term solution is to use the <strong> tag.

I will start looking for the root cause in the next few days. Should I open an issue to track this issue?

**Comment by mattwang44** [comment]
@jiawei-hong 

Could you check if this issue occurs when using MkDocs alone? If so, it might be more appropriate to open the issue in the MkDocs repository rather than FastAPI's.

**Comment by jiawei-hong** [comment]
@mattwang44 I just made a completely new mkdocs to test

I think it's some problem with fastapi

You can see my screenshot below

Screenshot 2024-10-21 at 7 11 02 AM

**Comment by jiawei-hong** [comment]
@mattwang44 I think the root cause is that the `pymdownx.betterem` plugin may have problems during processing.

I chose first to override the `mkdocs.yml` `pymdownx.betterem` `smart_enable` to `underscore`(default value)  parameter inherited from zh-hant `mkdocs.yml`

Reference: [pymdown-extensions-betterem-plugin](https://facelessuser.github.io/pymdown-extensions/extensions/betterem/)

**Comment by codingjenny** [comment]
> @mattwang44 I think the root cause is that the `pymdownx.betterem` plugin may have problems during processing.
> 
> I chose first to override the `mkdocs.yml` `pymdownx.betterem` `smart_enable` to `underscore`(default value) parameter inherited from zh-hant `mkdocs.yml`
> 
> Reference: [pymdown-extensions-betterem-plugin](https://facelessuser.github.io/pymdown-extensions/extensions/betterem/)

I agree that there shouldn't be any white space in Chinese either. This seems more reasonable, and I think this method for handling the asterisk is fine!

**Comment by mattwang44** [comment]
@jiawei-hong 

For clarity, and since Jenny and I may not be the most suitable reviewers for these changes, could you please open a new issue (including a clear description of the problem, your findings, and a reference to this discussion) and submit a separate PR for the changes in `docs/zh-hant/mkdocs.yml`?

**Comment by codingjenny** [comment]
> @jiawei-hong
> 
> For clarity, and since Jenny and I may not be the most suitable reviewers for these changes, could you please open a new issue (including a clear description of the problem, your findings, and a reference to this discussion) and submit a separate PR for the changes in `docs/zh-hant/mkdocs.yml`?

Agree. This is the best approach. I'm sorry about that. I spoke too hastily when I said there were no issues.

**Comment by jiawei-hong** [comment]
@mattwang44 Thanks for your reply, I have opened a [new discussion](https://github.com/fastapi/fastapi/discussions/12500) and [new PR](https://github.com/fastapi/fastapi/pull/12499) to specifically fix this issue 😆

I'll close this PR, We'll discuss in the new PR and new discussion

**Pull request closed without merging**
