### PR TITLE
🌐 Add Chinese translation for `docs/zh/docs/deployment/docker.md`

### PR DESCRIPTION
**Pull request by jaystone776**
as title

### CODE REVIEW

**Review by aqcool — COMMENTED** [review]
ok

**Review by aqcool — APPROVED** [review]
ok

**Comment by tiangolo** [comment]
📝 Docs preview for commit d816763a34e8a0447872af55b91844bcef2abb33 at: https://6499e35e0fb1cf0375ab3fba--fastapi.netlify.app

**Comment by tiangolo** [comment]
Thank you! It seems this was re-done/updated here: https://github.com/tiangolo/fastapi/pull/10296

So I'll pass on this one. ☕

**Pull request closed without merging**
