### PR TITLE
⬆️ Upgrade configuration for Ruff 0.2.1

### PR DESCRIPTION
**Pull request by MichaReiser**
I'm a ruff maintainer and I noticed that you aren't using the most recent ruff version yet. I went ahead and upgraded Ruff to 0.2.1 and updated the configuration.

* The formatting changes are a bugfix where ruff didn't add a trailing comma after type annotations. 
* I updated the configuration to use the now recommended `ruff.lint` options to configure the linter
* I updated the `lint.sh` file to use `ruff check` instead of `ruff` because we probably will deprecate the former at some point in the future.

### CODE REVIEW

**Comment by MichaReiser** [comment]
Whoops, the changes to the `requirements.txt` file are missing. You can see that I'm a Python packaging noob. Let me fix this up real quick.

**Review by dtleal — APPROVED** [review]
good stuf here

**Comment by Kludex** [comment]
- @MichaReiser @charliermarsh Eh... https://github.com/tiangolo/fastapi/pull/11075 😬

**Comment by MichaReiser** [comment]
oops sorry. That was my mistake.

**Pull request closed without merging**
