### PR TITLE
⬆Increase supported version of aiofiles to suppress warnings

### PR DESCRIPTION
**Pull request by SnkSynthesis**
With Python 3.8 the usage of this `@asyncio.coroutine` in aiofiles 0.5.0 raises warnings since the `@asyncio.coroutine` has been [deprecated](https://docs.python.org/3/library/asyncio-task.html#asyncio.coroutine) since Python 3.8. This PR suppresses those warnings by increasing the aiofiles version to 0.7.0.

The [lines](https://github.com/Tinche/aiofiles/blob/9a2141e6c51013995ed8b72b121e4e0a27af77b5/aiofiles/os.py#L7-L10) (`aiofiles/os.py`) of aiofiles in version 0.5.0 (Notice the `@asyncio.coroutine`):
```python
def wrap(func):
    @asyncio.coroutine
    @wraps(func)
    def run(*args, loop=None, executor=None, **kwargs):
```

The [lines](https://github.com/Tinche/aiofiles/blob/master/src/aiofiles/os.py#L7-L9) (`aiofiles/os.py`) of aiofiles in version 0.7.0 (Notice the `async def`):
```python
def wrap(func):
    @wraps(func)
    async def run(*args, loop=None, executor=None, **kwargs):
```

### CODE REVIEW

**Review by raphaelauv — APPROVED** [review]

**Review by juntatalor — APPROVED** [review]

**Review by jetpacktuxedo — APPROVED** [review]

**Review by reillysiemens — APPROVED** [review]

**Comment by wavenator** [comment]
Is there a reason why this PR is not merged yet? If any more work is needed, I'd be happy to jump in.

**Review by ycd — APPROVED** [review]

**Comment by wavenator** [comment]
In the meantime version 0.7.0 has been released. I recommend upgrading againt.

**Comment by SnkSynthesis** [comment]
@wavenator The version of `aiofiles` has been increased to `0.7.0`. Thank you for the recommendation.

**Comment by hongqn** [comment]
All reviewers have approved this pullreq.  What's blocking the workflows?

**Comment by SnkSynthesis** [comment]
@hongqn, A maintainer (@tiangolo) needs to approve workflows and/or merge the pull request.

**Comment by zevisert** [comment]
I came looking to open this PR today, good to see some activity. I can pitch in the changelog from aiofiles, from [here](https://github.com/Tinche/aiofiles/#history). 

https://github.com/Tinche/aiofiles/blob/aea353ebdd2771f2e4ae934077eceb12daaa3481/README.rst#L174-L189

**Comment by SnkSynthesis** [comment]
Thanks @zevisert!

**Comment by tiangolo** [comment]
Thanks for your contribution @SnkSynthesis! :cake: 

And thanks for the discussion everyone, in particular @zevisert for all the investigation and report. :detective: 

I updated the range required to also include `0.5.0` as it still works, there's no need to force everyone to upgrade to the most recent one (and to avoid any possible conflicts with other packages depending on `aiofiles`).

On the other hand, just as a note, I'll soon upgrade to the latest Starlette, based on `anyio`, which provides the same functionality, so `aiofiles` will no longer be needed. :tada: 

I'm making a release with these changes first just in case that's useful in the transition for anyone.

**Comment by SnkSynthesis** [comment]
Thanks @tiangolo 😄!

**Pull request merged**
