### PR TITLE
🐛 Fix `jsonable_encoder` using `include` and `exclude` parameters for non-Pydantic objects

### LINKED ISSUE #2594: `jsonable_encoder` function not working as expected with different type of variables
### First check

* [X] I added a very descriptive title to this issue.
* [X] I used the GitHub search to find a similar issue and didn't find it.
* [X] I searched the FastAPI documentation, with the integrated search.
* [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
* [X] I already read and followed all the tutorial in the docs and didn't find an answer.
* [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
* [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
* [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).
* [X] After submitting this, I commit to one of:
    * Read open issues with questions until I find 2 issues where I can help someone and add a comment to help there.
    * I already hit the "watch" button in this repository to receive notifications and I commit to help at least 2 people that ask questions in the future.
    * Implement a Pull Request for a confirmed bug.

### Example

Here's a self-contained, [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example) with my use case:

#### Example 1 (BaseModel)

```python
import pytest
from attr import dataclass
from fastapi.encoders import jsonable_encoder
from pydantic.main import BaseModel

class MyBaseModel(BaseModel):
    foo: int
    bar: int


@pytest.mark.parametrize(
    "obj, include, exclude, expected",
    [
        (MyBaseModel(foo=1, bar=2), None, None, {"foo": 1, "bar": 2}),  # Passed
        (MyBaseModel(foo=1, bar=2), {}, {}, {}),  # Passed
        (MyBaseModel(foo=1, bar=2), {"foo"}, {}, {"foo": 1}),  # Passed
        (MyBaseModel(foo=1, bar=2), {}, {"foo"}, {}),  # Passed
        (MyBaseModel(foo=1, bar=2), {"foo"}, None, {"foo": 1}),  # Passed
        (MyBaseModel(foo=1, bar=2), None, {"foo"}, {"bar": 2}),  # Passed
    ],
)
def test_jsonable_encoder_include_exclude_base_model(obj, include, exclude, expected):
    assert jsonable_encoder(obj, include=include, exclude=exclude) == expected
```

#### Example 2 (Python dictionary)
```python
import pytest
from fastapi.encoders import jsonable_encoder


@pytest.mark.parametrize(
    "obj, include, exclude, expected",
    [
        ({"foo": 1, "bar": 2}, None, None, {"foo": 1, "bar": 2}),  # Passed
        ({"foo": 1, "bar": 2}, {}, {}, {}),  # Failed
        ({"foo": 1, "bar": 2}, {"foo"}, {}, {"foo": 1}),  # Failed
        ({"foo": 1, "bar": 2}, {}, {"foo"}, {}),  # Failed
        ({"foo": 1, "bar": 2}, {"foo"}, None, {"foo": 1}),  # Failed
        ({"foo": 1, "bar": 2}, None, {"foo"}, {"bar": 2}),  # Passed
    ],
)
def test_jsonable_encoder_include_exclude_dict(obj, include, exclude, expected):
    assert jsonable_encoder(obj, include=include, exclude=exclude) == expected
```

#### Example 3 (Python object with dataclass)

```python
@dataclass
class MyModel:
    foo: int
    bar: int


@pytest.mark.parametrize(
    "obj, include, exclude, expected",
    [
        (MyModel(foo=1, bar=2), None, None, {"foo": 1, "bar": 2}),  # Passed
        (MyModel(foo=1, bar=2), {}, {}, {}),  # Failed
        (MyModel(foo=1, bar=2), {"foo"}, {}, {"foo": 1}),  # Failed
        (MyModel(foo=1, bar=2), {}, {"foo"}, {}),  # Failed
        (MyModel(foo=1, bar=2), {"foo"}, None, {"foo": 1}),  # Failed
        (MyModel(foo=1, bar=2), None, {"foo"}, {"bar": 2}),  # Failed
    ],
)
def test_jsonable_encoder_include_exclude_obj(obj, include, exclude, expected):
    assert jsonable_encoder(obj, include=include, exclude=exclude) == expected
```

### Description

I was trying to understand how the `include` and `exclude` parameters worked. I looked in the documentation ([here](https://fastapi.tiangolo.com/tutorial/encoder/)) and the the test suite ([here](https://github.com/tiangolo/fastapi/blob/fdb6c9ccc504f90afd0fbcec53f3ea0bfebc261a/tests/test_jsonable_encoder.py), latest commit of this file in master branch) and I did not find anything related to `include` and `exclude` in both places.

I did see that these 2 parameters came from Pydantic (from the [dict function](https://github.com/samuelcolvin/pydantic/blob/43308d1b24c5d1163c44b8fa786d1b27e000c64e/pydantic/main.py#L440)) and it is being used in the [_calculate_keys method](https://github.com/samuelcolvin/pydantic/blob/43308d1b24c5d1163c44b8fa786d1b27e000c64e/pydantic/main.py#L817).

The first thing I did was to check the `jsonable_encoder` using a BaseModel object, which uses the dict function from Pydantic (Example 1), so I created a set of test with a BaseModel instance. All those tests are passing. Then I created the same tests with a Python dictionary (Example 2) and a Python object (Example 3).

I expect that the same tests with a different type of variable would work the same. In the case of Example 3, it is failing the most because it is missing the `include` and `exclude` parameters at the end of the function ([here](https://github.com/tiangolo/fastapi/blob/fdb6c9ccc504f90afd0fbcec53f3ea0bfebc261a/fastapi/encoders.py#L142)).

### Environment

* OS: Linux
* Python: 3.8.5
* FastAPI Version: 0.63.0

To know the FastAPI version use:

```bash
python -c "import fastapi; print(fastapi.__version__)"
```

* Python version:

To know the Python version use:

```bash
python --version
```

### Additional context

To reproduce the Example snippets, you will also need `pytest` installed (6.2.1 in my case)
I am happy to help by creating a PR for this bug once it is confirmed.

<details>
  <summary>All examples together</summary>
  
  ```python
import pytest
from attr import dataclass
from fastapi.encoders import jsonable_encoder
from pydantic.main import BaseModel


class MyBaseModel(BaseModel):
    foo: int
    bar: int


@dataclass
class MyModel:
    foo: int
    bar: int


@pytest.mark.parametrize(
    "obj, include, exclude, expected",
    [
        (MyBaseModel(foo=1, bar=2), None, None, {"foo": 1, "bar": 2}),  # Passed
        (MyBaseModel(foo=1, bar=2), {}, {}, {}),  # Passed
        (MyBaseModel(foo=1, bar=2), {"foo"}, {}, {"foo": 1}),  # Passed
        (MyBaseModel(foo=1, bar=2), {}, {"foo"}, {}),  # Passed
        (MyBaseModel(foo=1, bar=2), {"foo"}, None, {"foo": 1}),  # Passed
        (MyBaseModel(foo=1, bar=2), None, {"foo"}, {"bar": 2}),  # Passed
        ({"foo": 1, "bar": 2}, None, None, {"foo": 1, "bar": 2}),  # Passed
        ({"foo": 1, "bar": 2}, {}, {}, {}),  # Failed
        ({"foo": 1, "bar": 2}, {"foo"}, {}, {"foo": 1}),  # Failed
        ({"foo": 1, "bar": 2}, {}, {"foo"}, {}),  # Failed
        ({"foo": 1, "bar": 2}, {"foo"}, None, {"foo": 1}),  # Failed
        ({"foo": 1, "bar": 2}, None, {"foo"}, {"bar": 2}),  # Passed
        (MyModel(foo=1, bar=2), None, None, {"foo": 1, "bar": 2}),  # Passed
        (MyModel(foo=1, bar=2), {}, {}, {}),  # Failed
        (MyModel(foo=1, bar=2), {"foo"}, {}, {"foo": 1}),  # Failed
        (MyModel(foo=1, bar=2), {}, {"foo"}, {}),  # Failed
        (MyModel(foo=1, bar=2), {"foo"}, None, {"foo": 1}),  # Failed
        (MyModel(foo=1, bar=2), None, {"foo"}, {"bar": 2}),  # Failed
    ],
)
def test_jsonable_encoder_include_exclude(obj, include, exclude, expected):
    assert jsonable_encoder(obj, include=include, exclude=exclude) == expected
  ```
</details>

### PR DESCRIPTION
**Pull request by xaviml**
This fixes #2594. I added more few cases with include and exclude parameters, which were missing. Now the parameters are consistent with the way that it works with Pydantic.

When I first added the new tests in `test_jsonable_encoder.py` (without changing the codebase), these were the errors I got:
```
================================= test session starts =================================
platform linux -- Python 3.8.5, pytest-5.4.3, py-1.10.0, pluggy-0.13.1
rootdir: /home/xaviml/work/fastapi
plugins: cov-2.10.0, asyncio-0.14.0
collected 15 items                                                                    

tests/test_jsonable_encoder.py FFF............                                  [100%]

====================================== FAILURES =======================================
__________________________________ test_encode_dict ___________________________________

    def test_encode_dict():
        pet = {"name": "Firulais", "owner": {"name": "Foo"}}
        assert jsonable_encoder(pet) == {"name": "Firulais", "owner": {"name": "Foo"}}
>       assert jsonable_encoder(pet, include={"name"}) == {"name": "Firulais"}
E       AssertionError: assert {'name': 'Fir...name': 'Foo'}} == {'name': 'Firulais'}
E         Omitting 1 identical items, use -vv to show
E         Left contains 1 more item:
E         {'owner': {'name': 'Foo'}}
E         Use -v to get the full diff

tests/test_jsonable_encoder.py:99: AssertionError
__________________________________ test_encode_class __________________________________

    def test_encode_class():
        person = Person(name="Foo")
        pet = Pet(owner=person, name="Firulais")
        assert jsonable_encoder(pet) == {"name": "Firulais", "owner": {"name": "Foo"}}
>       assert jsonable_encoder(pet, include={"name"}) == {"name": "Firulais"}
E       AssertionError: assert {'name': 'Fir...name': 'Foo'}} == {'name': 'Firulais'}
E         Omitting 1 identical items, use -vv to show
E         Left contains 1 more item:
E         {'owner': {'name': 'Foo'}}
E         Use -v to get the full diff

tests/test_jsonable_encoder.py:112: AssertionError
________________________________ test_encode_dictable _________________________________

    def test_encode_dictable():
        person = DictablePerson(name="Foo")
        pet = DictablePet(owner=person, name="Firulais")
        assert jsonable_encoder(pet) == {"name": "Firulais", "owner": {"name": "Foo"}}
>       assert jsonable_encoder(pet, include={"name"}) == {"name": "Firulais"}
E       AssertionError: assert {'name': 'Fir...name': 'Foo'}} == {'name': 'Firulais'}
E         Omitting 1 identical items, use -vv to show
E         Left contains 1 more item:
E         {'owner': {'name': 'Foo'}}
E         Use -v to get the full diff

tests/test_jsonable_encoder.py:125: AssertionError
================================== warnings summary ===================================
env/lib/python3.8/site-packages/aiofiles/os.py:10
env/lib/python3.8/site-packages/aiofiles/os.py:10
env/lib/python3.8/site-packages/aiofiles/os.py:10
env/lib/python3.8/site-packages/aiofiles/os.py:10
env/lib/python3.8/site-packages/aiofiles/os.py:10
env/lib/python3.8/site-packages/aiofiles/os.py:10
  /home/xaviml/work/fastapi/env/lib/python3.8/site-packages/aiofiles/os.py:10: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def run(*args, loop=None, executor=None, **kwargs):

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=============================== short test summary info ===============================
FAILED tests/test_jsonable_encoder.py::test_encode_dict - AssertionError: assert {'n...
FAILED tests/test_jsonable_encoder.py::test_encode_class - AssertionError: assert {'...
FAILED tests/test_jsonable_encoder.py::test_encode_dictable - AssertionError: assert...
====================== 3 failed, 12 passed, 6 warnings in 0.51s =======================
```

You can see that even I added the same tests to `test_encode_model_with_default`, they all passed. This is because the include and exclude done by Pydantic was done correctly. Therefore, what this PR adds is:
- More test cases to `include` and `exclude` parameters from the `jsonable_encoder` function
- Consistent functionality with different types of objects (BaseModel, dict, and Object)

### CODE REVIEW

**Comment by xaviml** [comment]
Hi @falkben,

Thank you for your reply. You are indeed correct it is a recursive function, however, when passing to children, the include and exclude is not passed (this was like this already). Not sure what is desired or not, but I am seeking consistency, so I went ahead and try how it works when passing a BaseModel object:

```python
class Model1(BaseModel):
    foo: str
    bar: str
    blabla: str


class Model2(BaseModel):
    foo: str
    bar: str
    model1: Model1

def test_jsonable_encoder_nested():
    model1 = Model1(foo="foo1", bar="bar1", blabla="blabla1")
    model2 = Model2(foo="foo1", bar="bar1", model1=model1)
    jsonable_encoder(model2, include={"foo"})
    # returns: {'foo': 'foo1'}
    jsonable_encoder(model2, exclude={"foo"})
    # {'bar': 'bar1', 'model1': {'bar': 'bar1', 'blabla': 'blabla1', 'foo': 'foo1'}}
```
Then if we try with a dict:
```python
def test_jsonable_encoder_nested_dict():
    model = {'bar': 'bar1', 'foo': 'foo1', 'model1': {'bar': 'bar1', 'blabla': 'blabla1', 'foo': 'foo1'}}
    jsonable_encoder(model, include={"foo"})
    # {'foo': 'foo1'}
    jsonable_encoder(model, exclude={"foo"})
    # {'bar': 'bar1', 'model1': {'bar': 'bar1', 'blabla': 'blabla1', 'foo': 'foo1'}}
```

You can see that it behaves the same way as Pydantic, which is not including and excluding for children objects.

I guess this will need to be added to the test suite, so we can define how the function is expected to work for future reference. Do you agree?

Regards,
Xavi M.

**Comment by xaviml** [comment]
Sorry I did not answer your question about nested include and exclude. This PR does not add the functionality that Pydantic has with nested includes and excludes as defined in [here](https://pydantic-docs.helpmanual.io/usage/exporting_models/#advanced-include-and-exclude). In my opinion, this would be part of a new feature if we are interested in adding it, so should be treated in another PR. This PR fixes a bug that the `jsonable_encoder` function has.

**Comment by xaviml** [comment]
Hi there,

Just for the awareness, this bug impacts the code from [full-stack-fastapi-postgresql](https://github.com/tiangolo/full-stack-fastapi-postgresql), which is a widely used template project for FastAPI. The problem comes when there is a circular dependency in the ORM (e.g. SQLAlchemy), then the `jsonable_encoder` would fall into a `RecursionError: maximum recursion depth exceeded in comparison` error. For this reason, I changed this [line](https://github.com/tiangolo/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/backend/app/app/crud/base.py#L49) to:

```python
obj_data = jsonable_encoder(db_obj, include=set(obj_in.__fields__.keys()))
```

Finally, after this change in my code is when I realized this bug, which made me realized that `includes` does not work when passing an ORM object instead of a Pydantic one.

I am not worried because I checked out the jsonable_encoder function to my private repository, but I am just concerned that someone else might be facing the same problem.

Regards,
Xavi M.

**Comment by xaviml** [comment]
PR was rebased and fixed to be compatible with include and exclude dictionaries, which was added in this PR and merged: https://github.com/tiangolo/fastapi/pull/2016

**Comment by tiangolo** [comment]
Great, thank you @xaviml! :rocket: 

Thanks for the detailed explanation and tests. And thanks @falkben for the input! :cake:

**Pull request merged**
