### PR TITLE
🌐 Add Korean translation for `docs/ko/docs/tutorial/index.md`

### PR DESCRIPTION
**Pull request by ghost**
Added the missing translation for "benefits" in docs/ko/docs/tutorial/index.md

### CODE REVIEW

**Comment by kkotipy** [comment]
I need to add the `lang-ko` label, but I'm not sure how to do it. 😂

**Comment by sodaMelon** [comment]
LGTM 👍
Thanks for the correction.
It's a simple one, so it'll probably be reflected soon.

**Comment by sodaMelon** [comment]
maybe it's better
🌐 Fix Korean translation for docs/ko/docs/tutorial/index.md
than current subject.

**Review by sodaMelon — APPROVED** [review]

**Review by hard-coders — APPROVED** [review]
LGTM

**Review by junah201 — APPROVED** [review]

**Pull request closed without merging**
