### PR TITLE
✏️ Fix typo in `docs/en/docs/alternatives.md`

### PR DESCRIPTION
**Pull request by s111d**
Pluralize

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 6cae29af87ce3b07d6397a9ebb1e5cffa8091b8e at: https://f13a4dfa.fastapitiangolo.pages.dev

**Comment by s111d** [comment]
Also: I'm not sure if its worth attention, but should'n the bullet here be just like "Info" bullets below and not "Note": https://fastapi.tiangolo.com/alternatives/#django-rest-framework
I'm asking because from what I see, creators of something usually go under "Info" section.

**Comment by hasansezertasan** [comment]
> Also: I'm not sure if its worth attention, but should'n the bullet here be just like "Info" bullets below and not "Note": https://fastapi.tiangolo.com/alternatives/#django-rest-framework I'm asking because from what I see, creators of something usually go under "Info" section. See here, for example: https://fastapi.tiangolo.com/alternatives/#webargs

I feel you, I think you should make those changes and commit but the documentation looks a bit (quite a bit) personal. So IDK if we have a say in this matter.

**Review by mirovisionepitech — APPROVED** [review]

**Review by alejsdev — APPROVED** [review]

**Comment by tiangolo** [comment]
📝 Docs preview for commit 8f9d8fac80d86fe6793905fd4914d48d260b7e25 at: https://7130e85e.fastapitiangolo.pages.dev

**Comment by alejsdev** [comment]
Good catch! Thanks @s111d 🐱

> Another thing, same file: "Angular two" – maybe just plainly "Angular 2"? Number of version is usually not spelled.

 I agreed with this one and made that change as well.

Thanks for your help too @mirovisionepitech and @hasansezertasan ☕

**Pull request merged**
