### PR TITLE
🌐 Add Chinese translation for `docs/zh/docs/advanced/events.md`

### PR DESCRIPTION
**Pull request by jaystone776**
As title

### CODE REVIEW

**Review by zy7y — APPROVED** [review]

**Comment by Jedore** [comment]
@jaystone776 Do you still take care of these translation PRs? I'm going to contribute. If now you you're offline or busy , I would create new PR because of some changes about you PR.

**Comment by Jedore** [comment]
@jaystone776 Do you still take care of these translation PRs? I'm going to contribute. If now you you're offline or busy , I would create new PR because of some changes about you PR.

**Comment by tiangolo** [comment]
📝 Docs preview for commit f984afd2fcdeda2417b5c2ab3dcf1f8f451bfd83 at: https://649a0cb17ce5230bcd50e352--fastapi.netlify.app

**Comment by alejsdev** [comment]
Thanks! @jaystone776 🐱 

And thanks for the help @zy7y 🔍

**Pull request merged**
