### PR TITLE
✨ Add support for Python 3.12

### PR DESCRIPTION
**Pull request by Jamim**
Hello @tiangolo,

Thank you for this awesome framework! 🙇🏻‍♂️

I believe that it would be great to have an explicit Python 3.12 support, so I'd like to suggest changes that:
  * enable testing for Python 3.12 on CI
  * update `classifiers` at `pyproject.toml`
  * fix deprecation warning for tutorials

Best regards!

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 6a803e92afcf3d21258f4862b4b1b955862f1ca8 at: https://fdeed641.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 9cf9b37d37e9ae8e1c37ed835990cf2f9b19922f at: https://b363ac74.fastapitiangolo.pages.dev

**Review by yezz123 — APPROVED** [review]
Amazing PR! We should have this ASAP In FastAPI 🚀

**Review by stlucasgarcia — APPROVED** [review]

**Comment by tiangolo** [comment]
📝 Docs preview for commit 4706a5aa7085306b72e44ea0200c70ff6e883a36 at: https://349a3a21.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit bdfb1e6c1955a2007d725333108588f7c6732163 at: https://3b25437a.fastapitiangolo.pages.dev

**Review by kiendang — COMMENTED** [review]
My 2 cents: looks like FastAPI does not use `utcnow` in its library code (only in `docs_src/security`, not `fastapi`) so it should not provide a compat function for it. The fix should be in the tutorials, not `fastapi/_compat.py`

**Comment by tiangolo** [comment]
📝 Docs preview for commit db118d7821c802998671a303b8ca270472790ad5 at: https://4c865de2.fastapitiangolo.pages.dev

**Comment by Jamim** [comment]
Thank you for the review, @kiendang! 🙇🏻‍♂️

I've came to a conclusion that you are completely right, so I've updated the PR to get rid of unnecessary compatibility function. Even better, I've realized there is a better universal solution with `datetime.now(timezone.utc)` that works for all supported Python versions.

**Review by kiendang — APPROVED** [review]
🙌 Hopefully this got merged soon.

**Comment by Kludex** [comment]
- https://github.com/tiangolo/fastapi/pull/9687
- https://github.com/tiangolo/fastapi/pull/5918

**Comment by Jamim** [comment]
Hello @tiangolo,

Sorry for bothering you, but it would be really great if you find a few minutes for this PR.
It has already been refined based on community feedback and has received 3 approvals.

_Thanks in advance and Happy New Year!_ 🎄

**Review by alejsdev — APPROVED** [review]

**Comment by tiangolo** [comment]
Nice, thank you @Jamim! 🚀 🍰 

And thanks for the reviews @kiendang, @yezz123, @lsglucas, @alejsdev 🙇

**Comment by tiangolo** [comment]
📝 Docs preview for commit 034ded222c116203adb9ccf583354ed3482ac10f at: https://56304ca1.fastapitiangolo.pages.dev

**Pull request merged**
