### PR TITLE
✏️ Fix typo for dependencies docs in script example tutorial006

### PR DESCRIPTION
**Pull request by Roshan310**
verify_token() function is missing the 'return x_token' value. The function is missing a return statement after the 'if' statement. Now, I've added the return statement and am proposing this change.

### CODE REVIEW

**Comment by Roshan310** [comment]
the file where I've made the change is located here: docs_src/dependencies/tutorial006_an_py39.py

**Comment by estebanx64** [comment]
Thanks for your time helping us! 🙇

We'll be merging this little fix in the docs scripts soon! 🤓

**Comment by estebanx64** [comment]
Thanks for helping us fix this. 🙇

We'll be reviewing it and merging it soon. 🤓

**Comment by estebanx64** [comment]
Hi @Roshan310.

The return here is not mandatory as the context in the docs says you can or cannot return a value. It means you can use dependencies to validate some logic and it isn't mandatory to return something.

I'll be closing this PR since it is not necessary any changes.

Thank you again for taking care of the details in the documentation. 🙇

**Pull request closed without merging**
