### PR TITLE
Allow passing ui parameters to redoc html

### PR DESCRIPTION
**Pull request by adriantre**
With these changes it is easier to change the appearance of redoc without the need of overriding all of the method `get_redoc_html`. This was already possible for swagger, so I took inspiration from that implementation.

Available options:
https://github.com/Redocly/redoc/blob/main/docs/config.md#theme-settings

```python
redoc_options = {
    "theme": {
        "typography": {"code": {"wrap": True}},
        "sidebar": {"backgroundColor": "rgb(29, 29, 29)", "textColor": "#FFF"},
        "logo": {"gutter": "25px"},
        "rightPanel": {"width": "35%"},
    },
    "hide-download-button": None
}

get_redoc_html(
    openapi_url=app.openapi_url,
    title=app.title,
    redoc_ui_parameters=redoc_options
)
```

### CODE REVIEW

**Review by hasansezertasan — COMMENTED** [review]
.

**Review by hasansezertasan — CHANGES_REQUESTED** [review]
Can you please rebase your pull request? There are now API Reference documentation with `Doc` annotations, please also add those...

**Comment by adriantre** [comment]
Thank you @hasansezertasan 

When building the docs I get

```python
WARNING:mkdocs.plugins.mkdocs_autorefs.plugin:mkdocs_autorefs: reference/openapi/docs.md: Could not find cross-reference target '[fastapi.openapi.docs.redoc_ui_default_parameters]'
```

This makes the cross-reference link in the docs not render properly (fig 1). I don't see what I have done different compared to swagger (fig 2). Any ideas?

image
image

**Comment by tiangolo** [comment]
Thanks @adriantre!

I would prefer to keep mainly the documentation to tell people how to modify the UI with their needs as in here: https://fastapi.tiangolo.com/how-to/custom-docs-ui-assets/#self-hosting-javascript-and-css-for-docs

I prefer not to add many more configs, in particular to ReDoc that I would not consider the main UI (Swagger UI is the main one).

I'm also considering trimming a bit these things and simplify the way that automatic OpenAPI UIs are provided, probably removing the default ReDoc and making it opt-in. But that will come later.

For now, I'll pass on this one, but thanks for the interest! ☕

**Comment by WilliamDEdwards** [comment]
> I would prefer to keep mainly the documentation to tell people how to modify the UI with their needs as in here: https://fastapi.tiangolo.com/how-to/custom-docs-ui-assets/#self-hosting-javascript-and-css-for-docs

Would just like to let you know that, from a user perspective, this PR is much more viable. Also, I'm not sure how the documentation helps users customise ReDoc, as JS/CSS should not be modified even when self-hosted.

**Comment by hasansezertasan** [comment]
Hey @adriantre, I created a package called [openapipages](https://github.com/hasansezertasan/openapipages) and included your changes in it. Can you check it out and let me know what you think?

**Comment by adriantre** [comment]
Cool, looks good! 🙌

**Comment by maliayas** [comment]
@hasansezertasan Awesome!

**Pull request closed without merging**
