### PR TITLE
Add introduction to casbin middlewarele

### PR DESCRIPTION
**Pull request by Xhy-5000**

### CODE REVIEW

**Comment by iudeen** [comment]
Really interesting. 

However do we really need to add this to documentation? IMHO, This can be better if you can write a detailed Blog and then link it https://fastapi.tiangolo.com/external-links/

**Review by iudeen — COMMENTED** [review]
Really interesting.
However do we really need to add this to documentation? IMHO, This can be better if you can write a detailed Blog and then link it https://fastapi.tiangolo.com/external-links/

**Comment by Xhy-5000** [comment]
Do you mean that I should write a brief introduction in the doc and a detailed one in the Blog?

**Comment by iudeen** [comment]
No, what I meant was you write complete blog. Add just the link to it in External Links section of the Docs.

**Comment by Xhy-5000** [comment]
Fine I'll do that.

**Comment by Xhy-5000** [comment]
> No, what I meant was you write complete blog. Add just the link to it in External Links section of the Docs.

could you please review this pr? https://github.com/tiangolo/fastapi/pull/5712

**Pull request closed without merging**
