### PR TITLE
✨ Add support for `lifespan` async context managers (superseding `startup` and `shutdown` events)

### LINKED ISSUE #2943: Support starlette "lifespan" context for application
### First check

* [x] I added a very descriptive title to this issue.
* [x] I used the GitHub search to find a similar issue and didn't find it.
* [x] I searched the FastAPI documentation, with the integrated search.
* [x] I already searched in Google "How to X in FastAPI" and didn't find any information.
* [x] I already read and followed all the tutorial in the docs and didn't find an answer.
* [x] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
* [x] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
* [x] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).
* [x] After submitting this, I commit to:
    * Read open issues with questions until I find 2 issues where I can help someone and add a comment to help there.
    * Or, I already hit the "watch" button in this repository to receive notifications and I commit to help at least 2 people that ask questions in the future.
    * Implement a Pull Request for a confirmed bug.

### Description

Starlette added support for the lifespan context function in 0.13.5.  It's not well documented, but the code does [suggest](https://github.com/encode/starlette/blob/ed73b97c9b8f4aa527eed88032c04ce9fe109a3c/starlette/applications.py#L51):
```python
        # The lifespan context function is a newer style that replaces
        # on_startup / on_shutdown handlers. Use one or the other, not both.
```

For my purposes, it's much more convenient to use a (async)contextmanager for the startup and shutdown events of my application.  It would be nice to have the option

### The solution you would like

I'd like an easier way, and one that's officially supported, to use the lifespan context function.

```Python
from fastapi import FastAPI

async def lifespan(app):
    print("startup")
    async with SomeResource():
        yield
    print("shutdown")

app = FastAPI(lifespan=lifespan)
```

or

```Python
from fastapi import FastAPI

app = FastAPI()

@app.lifespan
async def lifespan(app):
    print("startup")
    async with SomeResource():
        yield
    print("shutdown")
```

### Describe alternatives you've considered

I can already accomplish this simply by doing:
```python
from fastapi import FastAPI

async def lifespan(app):
    print("startup")
    async with SomeResource():
        yield
    print("shutdown")

app = FastAPI()
app.router.lifespan_context = lifespan
```
however this is not officially supported and would likely break if accidentally using `app.on_event` in addition.

One could also do nasty stuff with `__aenter__` and `__aexit__`:
```python
from fastapi import FastAPI

app = FastAPI()

@app.on_event("startup")
async def startup()
    print("startup")
    app.state.resource = SomeResource()
    await app.state.resource.__aenter__()

@app.on_event("shutdown")
async def startup()
    print("shutdown")
    await app.state.resource.__aexit__(None, None, None)
```
but that seems quite ugly to me.

### Environment

* OS: Linux
* FastAPI Version: 0.63.0
* Python version: 3.8.5

### PR DESCRIPTION
**Pull request by uSpike**
This adds support for the `lifespan` argument to the application and router, which was added in starlette.

I tidied up some of the event tests as well to promote reuse.

Fixes #2943

### CODE REVIEW

**Comment by nesb1** [comment]
Hi, we really need this fix, can i help with PR? There is a conflict

**Comment by meshantz** [comment]
I rebased, dealt with the commit conflicts and updated a test in #4147

**Comment by Kludex** [comment]
@meshantz There's no need for that. If @uSpike is not able to rebase, @tiangolo will eventually see this PR and rebase himself. :kissing:

**Comment by meshantz** [comment]
One of the tests that was added was failing due to a starlette update. Saw that nothing had happened in the last 15 days, and was hoping to lend a hand.

**Comment by uSpike** [comment]
Hi, sorry I've been out of the loop for a bit.  I've rebased and cherry-picked @meshantz commti f5f1bfc950facb182800484bda0e61a125c364b0 into this PR.

**Comment by uSpike** [comment]
I've fixed typing, formatting, and updated the docs to communicate that `lifespan` should be an `AsyncContextManager`.  Should be ready for review now.

**Comment by mortbauer** [comment]
@tiangolo this seems like a straight forward PR, please have a look if you can, would be great!!

**Review by BilalAlpaslan — APPROVED** [review]

**Review by yezz123 — APPROVED** [review]

**Comment by tiangolo** [comment]
Thank you @uSpike! :bow: :cake: 

I updated the docs to include more info and make this the recommended way from now on.

I also took the updates in https://github.com/tiangolo/fastapi/pull/5503, thanks @JonathanPlasse ! :coffee: 

And I added tests for the new example in the docs.

This will be available in FastAPI `0.93.0`, released in the next few hours. :tada: 

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.

**Pull request merged**
