### PR TITLE
🌐 Fix incorrect `pymdown-extensions` option used in CJK characters documentation

### PR DESCRIPTION
**Pull request by andychucs**
The smart_enable option makes the docs not supported to be displayed when using bold and italics which are in Chinese, Japanese, and Korean.

We basically don’t use whitespace between words in Chinese and Japanese.

It causes a lot of problems with Markdown convert. So it should not be set as `all` just keep default is correct for now.

Check the difference here with search '**' in web documents.

Chinese:

after: https://42bebad1.fastapitiangolo.pages.dev/zh/#sponsors
截屏2024-09-08 10 24 28

before: https://fastapi.tiangolo.com/zh/#sponsors
截屏2024-09-08 10 17 11

Japanese:

after: https://42bebad1.fastapitiangolo.pages.dev/ja/#sponsors
截屏2024-09-08 10 24 59

before: https://fastapi.tiangolo.com/ja/#sponsors
截屏2024-09-08 10 23 32

Korean case like this one: https://github.com/fastapi/fastapi/pull/12142

### CODE REVIEW

**Review by svlandeg — APPROVED** [review]
Thanks for identifying and fixing this issue, @andychucs! This seems like the best way to approach this issue to me.

**Comment by sodaMelon** [comment]
Thanks for the work. if this pr get merged, I'll close #12148 #12142 #12141 #12136

**Review by hard-coders — APPROVED** [review]

**Comment by sodaMelon** [comment]
hi @svlandeg when will it merge? 
If this issue is not resolved, it will be difficult to contribute for docs by CN/KO/JP.

**Comment by svlandeg** [comment]
Hi @sodaMelon,

We've currently got this in our internal queue for Tiangolo to perform a final review. Thanks for your patience!

**Review by hard-coders — APPROVED** [review]

**Review by sodaMelon — APPROVED** [review]

**Comment by alejsdev** [comment]
Hi @andychucs
This was handled in PR #12509, it should be fixed now. so I'm going to close this one but thanks for the interest and effort! :raised_hands:

**Pull request closed without merging**
