### PR TITLE
Pin swagger-ui-dist version number

### PR DESCRIPTION
**Pull request by ArcLightSlavik**
Temporary fix for https://github.com/tiangolo/fastapi/issues/2632, where on every request you send you get a 
```
INFO:     127.0.0.1:59513 - "GET /%5Bobject%20Module%5D HTTP/1.1" 404 Not Found
```

This was tested using a patch workaround described here: https://github.com/tiangolo/fastapi/issues/1762#issuecomment-662162612
Screenshot 2021-01-14 at 23 45 34

### CODE REVIEW

**Review by Kludex — APPROVED** [review]

**Review by ycd — APPROVED** [review]

**Comment by killjoy1221** [comment]
I think it would be a better idea to have these URLs configurable. It would let the resources to be hosted so people who can't connect to jsfiddle or googleapis at all because of firewalls to access it. Though maybe that's a target for another PR.

**Comment by ArcLightSlavik** [comment]
@killjoy1221 You can do this right now:
```
from fastapi import applications
from fastapi.openapi.docs import get_swagger_ui_html


def swagger_monkey_patch(*args, **kwargs):
    """
    Wrap the function which is generating the HTML for the /docs endpoint and 
    overwrite the default values for the swagger js and css.
    """
    return get_swagger_ui_html(
        *args, **kwargs,
        swagger_js_url="https://cdn.jsdelivr.net/npm/swagger-ui-dist@3.29/swagger-ui-bundle.js",
        swagger_css_url="https://cdn.jsdelivr.net/npm/swagger-ui-dist@3.29/swagger-ui.css")


# Actual monkey patch
applications.get_swagger_ui_html = swagger_monkey_patch


# Your normal code ...
app = FastAPI()
```

But I assume something more pretty would be required if someone would want to do this. (to me it looks good enough)

**Comment by ArcLightSlavik** [comment]
This was fixed by swagger-ui https://github.com/swagger-api/swagger-ui/issues/6850.

**Comment by tiangolo** [comment]
Thanks for the discussion here everyone! :coffee: 

And thanks for reporting back and closing the issue @ArcLightSlavik  👍

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.

**Comment by waketzheng** [comment]
> I think it would be a better idea to have these URLs configurable. It would let the resources to be hosted so people who can't connect to jsfiddle or googleapis at all because of firewalls to access it. Though maybe that's a target for another PR.

@killjoy1221 I publish a plugin to make it easy to change cdn host or change swagger-ui version:
```py
from fastapi import FastAPI
from fastapi_cdn_host import monkey_patch_for_docs_ui # pip install fastapi_cdn_host

app = FastAPI()
monkey_patch_for_docs_ui(app, ("https://cdn.jsdelivr.net/npm", ("/swagger-ui-dist@3.29/", "/redoc@next/bundles/")))
```

**Pull request closed without merging**
