### PR TITLE
🌐 Add Korean translation for `/docs/ko/docs/tutorial/schema-extra-example.md`

### PR DESCRIPTION
**Pull request by KaniKim**
- Add Korean translation for `/docs/ko/docs/tutorial/schema-extra-example.md`

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit ebfb6425f1e094efa98f77ff8b32debbc72ce3da at: https://c71f2ae7.fastapitiangolo.pages.dev

**Review by riroan — CHANGES_REQUESTED** [review]

**Comment by KaniKim** [comment]
Thanks to @riroan for your suggestions, I changed it.

**Comment by tiangolo** [comment]
📝 Docs preview for commit 78128181700f4a66b113a86102516c622bae6b2f at: https://80b9dfde.fastapitiangolo.pages.dev

**Review by riroan — APPROVED** [review]
LGTM :+1:

**Comment by alejsdev** [comment]
Great! Thanks @KaniKim 🚀✨

And thanks for the review @riroan 🤓

**Pull request merged**
