### PR TITLE
📌 Pin Swagger UI

### LINKED ISSUE #6249: 3.30.1 breaks path tags (endpoints don’t expand)
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: Chrome
 - Version: 84.0.4147.89
 - Method of installation: SwaggerUIBundle from unpkg
 - Swagger-UI version: 3.30.1
 - Swagger/OpenAPI version: OpenAPI 3.0.2

### Content & configuration

Example Swagger/OpenAPI definition: [example.yml](https://github.com/swagger-api/swagger-ui/files/4956212/example.txt)

Swagger-UI configuration options:
```js
SwaggerUIBundle({
    url: "openapi",
    dom_id: "#api-explorer",
    presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIBundle.SwaggerUIStandalonePreset
    ],
})
```

### Describe the bug you're encountering
When opening a path that is in a tag “group”, it disappears and then reappears underneath the `default` tag.

This is a regression in 3.30.1; I temporarily set my unpkg URL to `3.30.0` (https://unpkg.com/swagger-ui-dist@3.30.0/swagger-ui-bundle.js) and the behavior no longer happens. I set it back to `3`  to get the latest version and it started happening again.

### To reproduce...

1. Go to a path in a tag “group”
2. Click on the path item
3. See error: the path item will disappear and reappear further down the page under a new `default` tag group.
4. The path item under the `default` tag will sit and spin.

### Expected behavior
The path item should open in place.

### Screenshots
example

### PR DESCRIPTION
**Pull request by tiangolo**
📌 Pin Swagger UI while this is fixed: https://github.com/swagger-api/swagger-ui/issues/6249

### CODE REVIEW

**Comment by codefather-labs** [comment]
it's a problem of fastapi or swagger ui?

**Comment by Kludex** [comment]
Is a Swagger issue, not FastAPI.

**Comment by tiangolo** [comment]
Yep, it's a Swagger UI issue, not FastAPI.

But to alleviate the problem on the FastAPI side, I pinned it here and released it in FastAPI version `0.60.1`, check the conversation here: https://github.com/tiangolo/fastapi/issues/1762#issuecomment-662277612

**Comment by kiennguyen1101** [comment]
Swagger UI released a new version to fix this issue:
> New release to resolve this issue, [v3.30.2](https://github.com/swagger-api/swagger-ui/releases/tag/v3.30.2)

**Pull request merged**
