### PR TITLE
🌐 Add Turkish translation for `docs/tr/docs/newsletter.md`

### PR DESCRIPTION
**Pull request by hasansezertasan**
🌐 Add Turkish translation for `docs/tr/docs/newsletter.md`

Discussion: #9193

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit cfa7f71a295003bde104f87c2a6cbabf65b9fcb3 at: https://c8f0e998.fastapitiangolo.pages.dev

**Review by alperiox — APPROVED** [review]
cevirilecek icerik yok

**Review by SametEmin — APPROVED** [review]
LGTM

**Review by OzgunCaglarArslan — APPROVED** [review]
LGTM

**Review by aprilcoskun — APPROVED** [review]
LGTM

**Review by BilalAlpaslan — APPROVED** [review]

**Comment by tiangolo** [comment]
📝 Docs preview for commit fa1e7974d69bc9cae514489d0c9c3e2d35820a7c at: https://ba1f5971.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 92efa69427078f854f76078103ed1080364e4426 at: https://5a9e0700.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit afd6e97014ecc9ec16769044544d7144e9ed0fee at: https://3fbcca69.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
Awesome, thanks @hasansezertasan! 🍪 

And thanks for the reviews @aprilcoskun, @alperiox, @BilalAlpaslan, @OzgunCaglarArslan, @SametEmin 🙇 ☕

**Pull request merged**
