### PR TITLE
🐛 Fix openapi generation with responses kwarg

### PR DESCRIPTION
**Pull request by flxdot**
This PR fixes a bug where the schema of response models defined via the [`responses`](https://fastapi.tiangolo.com/advanced/additional-responses/?h=responses) keyword where generated as `validation` schema instead of `serialization` schema.

Additional discussions for that topic:
- #10596
- #9856

### CODE REVIEW

**Review by YuriiMotov — APPROVED** [review]
I've just checked that the problem is still relevant in FastAPI v. 0.109.2 (Pydantic 2.6.0).

This PR fixes this problem.
Code is nice

**Comment by simonwallace** [comment]
I am also affected by this issue. Is this PR ready to be merged?

**Comment by flxdot** [comment]
> I am also affected by this issue. Is this PR ready to be merged?

From my point of view, it is.

@tiangolo is there anything else you need me to do here?

**Comment by alejsdev** [comment]
Hi @flxdot, thanks for your interest in contributing to FastAPI. We're aware of your PR and we'll come back to review it in detail soon. Thanks for your patience :pray:

**Review by svlandeg — APPROVED** [review]
Hi @flxdot,

Thanks for the contribution, and apologies for the delay in reviewing this!

Thanks all for the review and comments as well!

I could reproduce the bug on `master` and confirm that the test fails on `master` and succeeds with this PR. I've also pushed a related test from #11517 to this PR, as both PRs include the same fix but tested slightly differently.

This PR was submitted earlier, so I suggest we merge this one and close the other. Either way, I'll leave the final decision with Tiangolo.

Thanks again!

**Comment by tiangolo** [comment]
Great, thank you @flxdot! :rocket: :cake: 

And thanks for the help and reviews @YuriiMotov, @svlandeg, @alejsdev :bow: 

This will be available in FastAPI `0.115.1` in the next hours. :tada:

**Pull request merged**
