### PR TITLE
Replace `typing.Optional[T]` by `typing.Union[T, None]`

### PR DESCRIPTION
**Pull request by Kludex**
Feel free to remove the `.libcst` file. I didn't remove it, so you can see how I ran it. 

Check https://github.com/Kludex/no-optional for more. 

Edit: currently the libcst file is not needed anymore.

### CODE REVIEW

**Comment by zoliknemet** [comment]
@Kludex why would you do this, Optional[int] is fine
Can You explain why Union[int, None] is better

**Comment by Kludex** [comment]
https://twitter.com/tiangolo/status/1531583406651363328?t=2Pq3vH9w6AxEiLANKb0XJA&s=19

**Comment by pedramardakani** [comment]
Ah you've done it @Kludex :laughing: I was just about to start, but thought maybe I should check if someone else has done it before :thinking: Good job :+1: And another :+1: for creating the [no-optional](https://github.com/Kludex/no-optional) package :smile:

**Review by yezz123 — APPROVED** [review]
Looks amazing 🤩

**Comment by Kludex** [comment]
There's no need for the yml file anymore, jfyk.

(I'm on the cellphone)

**Comment by tiangolo** [comment]
no-optional is very cool! Thanks for building that!

These specific files are the ones explaining how `Union` and `Optional` work, so, the `Optional` in them is intentional. Given that I'll close this one, but thanks again for no-optional!

I have to play with LibCST myself. :nerd_face: I keep telling you the things I want to try and then I get envious when you try them first! :joy:

**Comment by Kludex** [comment]
> I keep telling you the things I want to try and then I get envious when you try them first! 😂

hahaha I was only able to play with it because you told me about it ❤️

**Pull request closed without merging**
