### PR TITLE
✨ Add support for OpenAPI 3.1.0

### PR DESCRIPTION
**Pull request by tiangolo**
✨ Add support for OpenAPI 3.1.0

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit c719570d9605b8c84c9360f11de0fa5fc85083c8 at: https://649f03f3c002911c0a8b598b--fastapi.netlify.app

**Comment by tiangolo** [comment]
📝 Docs preview for commit 3483b4c3edbba7db8399dc9d79d858d784df1975 at: https://649f1770de745124017bddde--fastapi.netlify.app

**Comment by tiangolo** [comment]
📝 Docs preview for commit aad99887f7c0a7eb55fe58d2efc05fe426bbbc33 at: https://649f1b6f22c0772d2c878943--fastapi.netlify.app

**Comment by tiangolo** [comment]
📝 Docs preview for commit aad99887f7c0a7eb55fe58d2efc05fe426bbbc33 at: https://649f1db20103a834d44992e8--fastapi.netlify.app

**Comment by francipvb** [comment]
Hello,

Is there a way to downgrade to 3.0 while keeping up to date?

**Comment by francipvb** [comment]
I mean the FastAPI package itself...

**Comment by wlievens** [comment]
Is there a way to use recent FastAPI releases but emit v3.0 OpenAPI? I'm using OpenAPITools openapi-generator and they do not fully support v3.1 yet.

**Comment by felix-hilden** [comment]
Looking through the code, it seems that there is no way to do that unfortunately. The OpenAPI versions set in the code are only directly forwarded to the spec content instead of determining how it's generated.

---

A little awkward for me and I'm sure many others who committed to Pydantic 2 as well, because that now clashes :P But for me it seems to be mostly about transforming how optional types are represented so maybe there's a semi-easy way to do it by hand after generating the spec.

**Pull request merged**
