### PR TITLE
🌐 Add Portuguese translation for `docs/pt/docs/advanced/response-change-status-code.md`

### PR DESCRIPTION
**Pull request by ceb10n**

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit a44ba2a575db05bf477688d0f886b7a8f863460f at: https://4e017ee0.fastapitiangolo.pages.dev

**Review by nazarepiedady — APPROVED** [review]
It is good enough to be merged on the main branch. Thanks for your contribution.

**Review by lucasbalieiro — APPROVED** [review]
Nice!

**Comment by alejsdev** [comment]
Cool! Thank you for the contribution @ceb10n :medal_sports: :tada: 
And thanks to everyone for the review :rocket:

**Pull request merged**
