### PR TITLE
🌐 Add German translation for `docs/de/docs/tutorial/index.md`

### PR DESCRIPTION
**Pull request by fhabers21**
Started the tutorial translation

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 77c8ac72d9ae04264a13982a5e089a5e2e39ac91 at: https://649a2e8fcc19e51f17cad4a6--fastapi.netlify.app

**Comment by nilslindemann** [comment]
Hello @fhabers21 

Good translation, I approved it. I have a few suggestions, see this .md:

[index.md](https://github.com/tiangolo/fastapi/files/12812016/index.md)

**Review by nilslindemann — APPROVED** [review]

**Review by leo-hsk — APPROVED** [review]
Good and concise translation. I approved it.

**Comment by fhabers21** [comment]
@leo-hsk thanks!

**Comment by tiangolo** [comment]
📝 Docs preview for commit 3b6d35f4706bc16eeab6ff36a4af63d23cbfe1c9 at: https://d8f9db09.fastapitiangolo.pages.dev

**Comment by fhabers21** [comment]
@tiangolo we might be good to go! 🚀

**Comment by alejsdev** [comment]
Thank you! @fhabers21 🙇‍♀️ 

And thanks for the reviews @nilslindemann and @leo-hsk 🔍🧐

**Pull request merged**
