### PR TITLE
🐛 Fix custom response input output schema bug

### PR DESCRIPTION
**Pull request by slafs**
This PR addresses the issue (point 1.) from https://github.com/tiangolo/fastapi/discussions/10697

Add missing `mode` argument when calling `create_model_field`
for "custom" response models defined in the `responses` option of a route.
The same way we do that for the "main" response model (see the other call of `create_model_field`).

Otherwise that custom response model schema (if separate i/o models are enabled)
is generated with the "-Input" suffix (instead of `-Output`).

NOTE this PR doesn't address docs issues that are mentioned in https://github.com/tiangolo/fastapi/discussions/10697 (point 2.)

### CODE REVIEW

**Comment by slafs** [comment]
@alejsdev any chance on approving/merging this? 😬

**Comment by alejsdev** [comment]
Hi @slafs, thank you for your interest in contributing to FastAPI. We have a high volume of PRs, we're reviewing and classifying them. We'll come back to review your PR in detail, we appreciate your patience as we manage the queue. :bowing_woman:

**Comment by slafs** [comment]
Oh yeah. Cool. Although, I feel my test is more explicit about the custom `responses` bug.

**Review by svlandeg — COMMENTED** [review]
Hi @slafs,

Thanks for the contribution, and apologies for the delay in reviewing this!

Your unit tests & example code from #10697 clearly demonstrate the issue. I could reproduce the bug on `master` and confirm that the test fails on `master` and succeeds with this PR.

Because #10895 contains the same fix and was submitted earlier, I would suggest to merge that one and close this one. I have pushed your test to that PR as well though, as I agree that this test is slightly more clear.

I will leave this up to Tiangolo for a final review and then we'll hopefully be able to merge the fix soon 🙏 

Thanks again!

**Comment by slafs** [comment]
Thanks @svlandeg!

Is there anything I can do regarding the documentation issue mentioned in https://github.com/fastapi/fastapi/discussions/10697 (point 2.)?

**Comment by tiangolo** [comment]
Thank you @slafs! :rocket: 

And thanks for the help @alejsdev, @svlandeg :bow: 

This was fixed in https://github.com/fastapi/fastapi/pull/10895, it will be available in FastAPI `0.115.1` in the next hours. :tada: 

I'll now close this one, but thanks for your effort! :cake:

**Pull request closed without merging**
