### PR TITLE
Update sql-databases.md

### PR DESCRIPTION
**Pull request by hasnatsajid**
✏️ Corrected the link for async sql databases

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit b2797b9c9ba0fdbf401d79e6d5838c5e1bc13e4b at: https://15645400.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit bbdb950bfab44b65cacb3c9cf80daac6f47f37d5 at: https://55cd5f71.fastapitiangolo.pages.dev

**Review by ordinary-jamie — APPROVED** [review]
LGTM

**Comment by tiangolo** [comment]
Thanks @hasnatsajid! This was covered in another recent PR, so I'll close this one. But thanks for the effort! 🚀

**Pull request closed without merging**
