### PR TITLE
🐛 Prefer custom encoder over defaults if specified in `jsonable_encoder`

### PR DESCRIPTION
**Pull request by viveksunder**
In `encoders.py/jsonable_encoder`, default encoders for each type are specified first & are used in preference to custom encoders. 

This affects custom encoders specified for certain types like enums such that the default encoder is always executed and any custom encoders specified are ignored. See - https://github.com/tiangolo/fastapi/issues/1986 - for a description of this issue and example code as well that illustrates the problem.

This PR adds a change to prefer custom encoders if specified in preference to default encoders.

Disclaimer - I am completely new to this code base :-)

### CODE REVIEW

**Review by ycd — APPROVED** [review]

**Comment by viveksunder** [comment]
Hi @ycd - thanks for approving. Just wondering when PRs are typically merged in & what the process is. Is there anything else needed from me in order to get this merged in?

**Comment by Kludex** [comment]
Just wait for @tiangolo 's input.

**Comment by ycd** [comment]
Exactly, @tiangolo usually releases a new version in 14-21 days, but he just recently moved to Germany so he is probably too busy too look here, but i believe next release would not take longer than 1-2 weeks.

**Comment by viveksunder** [comment]
Gotcha, not a problem at all! Thanks @ycd & @Kludex  :)

**Comment by mikegrima** [comment]
Hello! This does appear to fix my issue at #2091. However, if I may make one suggestion to this PR, please also fix the mutable dictionary that is set as a keyword argument with this code:

```Python
    custom_encoder: dict = None,
    sqlalchemy_safe: bool = True,
) -> Any:
    custom_encoder = custom_encoder or {}
    if custom_encoder:
        if type(obj) in custom_encoder:
            return custom_encoder[type(obj)](obj)
        else:
            for encoder_type, encoder in custom_encoder.items():
                if isinstance(obj, encoder_type):
                    return encoder(obj)
```

More details on this is here: https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments

**Comment by viveksunder** [comment]
> Hello! This does appear to fix my issue at #2091. However, if I may make one suggestion to this PR, please also fix the mutable dictionary that is set as a keyword argument with this code:
> 
> ```python
>     custom_encoder: dict = None,     # <------- Make this change
>     sqlalchemy_safe: bool = True,
> ) -> Any:
>     custom_encoder = custom_encoder or {}       # <-------- And this change
>     if custom_encoder:
>         if type(obj) in custom_encoder:
>             return custom_encoder[type(obj)](obj)
>         else:
>             for encoder_type, encoder in custom_encoder.items():
>                 if isinstance(obj, encoder_type):
>                     return encoder(obj)
> ```
> 
> More details on this is here: https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments

I agree! I can make this change if there are no objections.

**Comment by viveksunder** [comment]
Hate to be a bother @ycd :) but just bumping this because I made the change @mikegrima suggested. 

Also, do we think this is going to be merged in soon? Trying to decide if I should use my personal fork to use this change (which I'd rather not on the off-chance that this change doesn't actually get merged in)

**Comment by mikegrima** [comment]
Would like to make a friendly bump to get this released soon.

**Comment by viveksunder** [comment]
Hi @tiangolo - We (and others) would really like to use this ASAP. Really appreciate it if you could review this & lmk if good.

**Comment by viveksunder** [comment]
Hello. Is there something preventing this from being merged? It's been open for a while now and we really need this change!

**Comment by mikegrima** [comment]
@viveksunder Can you rebase this PR?

@ycd one this is rebased, can you merge it in?

**Comment by viveksunder** [comment]
My git commit history got borked while rebasing :face_with_head_bandage: so I started a new one here - https://github.com/tiangolo/fastapi/pull/2567

**Comment by ycd** [comment]
@mikegrima I'd love to do it but the only @tiangolo can merge PR's.

**Comment by mojimi** [comment]
Really looking forward to this, any news from @tiangolo ?

**Comment by mikegrima** [comment]
@tiangolo Friendly bump to merge.

**Comment by dhofstetter** [comment]
@tiangolo Do you see any problems with the approach implemented here? Sometimes it's really useful to override the default encoder. E.g. encoding Decimals to json using a predefined quantization. Would be really great if you would accept this PR

**Comment by kovalevvlad** [comment]
+1 would really like to have a custom Enum serializer.

**Comment by mikegrima** [comment]
@tiangolo please click merge!

**Comment by philipbjorge** [comment]
Is this PR still necessary?

For my usecase at least, it seems like the following resolved.
https://github.com/tiangolo/fastapi/pull/1769

**Comment by kovalevvlad** [comment]
@philipbjorge indeed it is still needed, the check for `isinstance(obj, Enum)` in `fastapi/encoders.py` is performed before checking whether custom encoders exist, therefore it is currently impossible to create a functional custom encoder for an `Enum` type.

**Comment by mojimi** [comment]
For me this is very necessary, as I work with DynamoDB and it requires floats to be transformed to Decimal in the boto3 library.

My current solution makes another iteration on top of the result of jsonable_encoder to fix floats, quite unoptimal

**Comment by mikegrima** [comment]
Can someone please reach out to @tiangolo to get this merged in?

**Comment by JP-Globality** [comment]
@tiangolo is there anything else we can do to get this PR over the line and merged in?

I too have the same issue as @mikegrima and can verify this PR fixes my issue by allowing the user to specify custom json_encoders for Enums. Simply doing `enum.value` doesn't produce JSONable values for nested Enums.

**Review by JP-Globality — APPROVED** [review]

**Comment by inai-shreyas** [comment]
waiting for this to be merged as well. @tiangolo could you please look at it?

**Comment by darkpssngr** [comment]
waiting for this to be merged as well. @tiangolo could you please look at it?

**Comment by justinttl** [comment]
It will be fantastic to iron out this very surprising behavior and incompatibility between FastAPI and pydantic! Trying to implement https://github.com/samuelcolvin/pydantic/issues/1004 for my API at the moment and it relies on custom encoders working expectedly. @tiangolo

**Comment by pdenapo** [comment]
+1 It will be very helpful to fix this. For instance, I'm trying to use fastapi with Mongodb, and I'am having trouble with the Decimal128 type for pymongo.bson which is not  natively supported by pydantic, so I would need to provide a custom serialization.

**Comment by nicknotfun** [comment]
Also waiting on this fix, wondering what is holding it up? @ycd @JP-Globality @tiangolo ?

**Comment by aliereno** [comment]
I needed to implement custom encoder for decimal and enum types, but I couldn't. I am looking forward to this PR merged.

**Comment by yribeiro** [comment]
@tiangolo please merge this. My team rely on FastAPI and Pydantic quite heavily. Having to write custom types and using type ignores is not the best. Would be great if this can get merged into the next release!

**Comment by tiangolo** [comment]
Awesome, thank you @viveksunder! :coffee: 

And thanks everyone for the interest! :cake: 

This is available in FastAPI `0.73.0`, released in a couple of hours. :tada:

**Pull request merged**
