### PR TITLE
✏️ Fix internal links

### PR DESCRIPTION
**Pull request by pavelzw**
Currently, the links for dependencies and sub-dependencies are not working in the `Concurrency and async / await` chapter, see [here](https://fastapi.tiangolo.com/async/#dependencies).

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 0689c57609285e57189fa43a11c5453a9e5ffd26 at: https://649c2fdd9ba4b3077287e146--fastapi.netlify.app

**Comment by pavelzw** [comment]
The two links seem to work now 👍🏻 https://649c2fdd9ba4b3077287e146--fastapi.netlify.app/async/#dependencies

**Comment by tiangolo** [comment]
📝 Docs preview for commit f8fec3d3599d356d1b0f29cc5f8101c9c78ef9b3 at: https://649c345911cafb09007a7450--fastapi.netlify.app

**Comment by tiangolo** [comment]
📝 Docs preview for commit dec152f1114e6052d5d3bbcbcf6e69324990f55f at: https://ea21a43b.fastapitiangolo.pages.dev

**Review by Kludex — APPROVED** [review]

**Comment by pavelzw** [comment]
Superseded by #10498

**Pull request closed without merging**
