### PR TITLE
🌐 Add Ukrainian translation for `docs/uk/docs/fastapi-people.md`

### PR DESCRIPTION
**Pull request by rostik1410**
related https://github.com/tiangolo/fastapi/issues/1748
based on https://github.com/tiangolo/fastapi/pull/4553

### CODE REVIEW

**Comment by rostik1410** [comment]
@romashevchenko, @lizaliza123 Hey, could you pls look at this? You have already reviewed it some time ago in PR mentioned in this PR description, I made the changes that you requested.

**Comment by tiangolo** [comment]
📝 Docs preview for commit 98acbc7c736a09424f78874b9c6ce139a87521cc at: https://d535b9ae.fastapitiangolo.pages.dev

**Review by mpmeleshko — APPROVED** [review]

**Review by bisibuka — APPROVED** [review]

**Review by bisibuka — APPROVED** [review]

**Comment by tiangolo** [comment]
📝 Docs preview for commit e8372be70e50ba839961229bffe120d1609ff6b1 at: https://7a12e271.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
Great, thanks @rostik1410! 🍰 

And thanks for the reviews @bisibuka and @mpmeleshko 🙇

**Pull request merged**
