### PR TITLE
Fix typo in documents

### PR DESCRIPTION
**Pull request by urushio**

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 036e8af412737afcd4ee1fef4102bf0b432a4695 at: https://52a3fe25.fastapitiangolo.pages.dev

**Review by Jamim — CHANGES_REQUESTED** [review]
Hello @urushio,

Nice catch! But there are many more `onwer`s to fix 😅

<details>
<summary>$ ag Onwer</summary>

```
docs/en/docs/release-notes.md
45:        raise HTTPException(status_code=400, detail=f"Onwer error: {e}")

tests/test_tutorial/test_dependencies/test_tutorial008b.py
17:    assert response.json() == {"detail": "Onwer error: Rick"}

tests/test_tutorial/test_dependencies/test_tutorial008b_an.py
17:    assert response.json() == {"detail": "Onwer error: Rick"}

tests/test_tutorial/test_dependencies/test_tutorial008b_an_py39.py
17:    assert response.json() == {"detail": "Onwer error: Rick"}

docs_src/dependencies/tutorial008b.py
20:        raise HTTPException(status_code=400, detail=f"Onwer error: {e}")

docs_src/dependencies/tutorial008b_an_py39.py
22:        raise HTTPException(status_code=400, detail=f"Onwer error: {e}")

docs_src/dependencies/tutorial008b_an.py
21:        raise HTTPException(status_code=400, detail=f"Onwer error: {e}")
```
</details>

**Comment by tiangolo** [comment]
📝 Docs preview for commit 66d92ee0ed63b3d3e5cb644efabbfb13dac66393 at: https://91f23638.fastapitiangolo.pages.dev

**Review by Jamim — APPROVED** [review]

**Review by nilslindemann — APPROVED** [review]

**Review by hasansezertasan — APPROVED** [review]
I am with @Jamim, can you also fix those?

**Comment by nilslindemann** [comment]
I think he already has fixed all seven.

**Comment by hasansezertasan** [comment]
@nilslindemann I just double-checked it and there are no `onwer`s anymore.

**Comment by urushio** [comment]
Another pull request and commit fixed the same location, so I closed this pull request.
https://github.com/tiangolo/fastapi/pull/10847
https://github.com/tiangolo/fastapi/commit/040ad986d48bb9a400de804f7f25abb856d85e1a

**Pull request closed without merging**
