### PR TITLE
✏️ Fix typos in `docs/en/docs/alternatives.md` and `docs/en/docs/tutorial/dependencies/index.md`

### PR DESCRIPTION
**Pull request by s111d**
Looks like "plug-ins" is used across the docs, and it is a common plural form in general.

P.S.: somebody with native English please check the next paragraph, namely "way that allow" – shouldn't there be "allowS" (or "will allow" alternatively)?

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 16f352b39f48883bf693b438050a79182a7aaa32 at: https://b927d9bc.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 39f2ebc39d7fdbd425363ad2bf9a9dd3c73ccf37 at: https://384c2bce.fastapitiangolo.pages.dev

**Comment by s111d** [comment]
NOTE: https://fastapi.tiangolo.com/alternatives/#starlette
– ASGI hover reads "The new standard for building asynchronous Python web" – shouldn't it end with "applications" or it is left like this intentionally?

**Comment by aanchlia** [comment]
> Looks like "plug-ins" is used across the docs, and it is a common plural form in general.
> 
> P.S.: somebody with native English please check the next paragraph, namely "way that allow" – shouldn't there be "allowS" (or "will allow" alternatively)?

Yeah, should be `way that allows`. Can you make that change too ?

**Comment by s111d** [comment]
> > Looks like "plug-ins" is used across the docs, and it is a common plural form in general.
> > P.S.: somebody with native English please check the next paragraph, namely "way that allow" – shouldn't there be "allowS" (or "will allow" alternatively)?
> 
> Yeah, should be `way that allows`. Can you make that change too ?

Done:
https://github.com/tiangolo/fastapi/pull/10906/commits/339e5bc735f7cca67822bc2d1e3044a59132a186

**Review by alejsdev — APPROVED** [review]

**Review by hasansezertasan — APPROVED** [review]

**Comment by tiangolo** [comment]
> NOTE: [fastapi.tiangolo.com/alternatives/#starlette](https://fastapi.tiangolo.com/alternatives/#starlette)
– ASGI hover reads "The new standard for building asynchronous Python web" – shouldn't it end with "applications" or it is left like this intentionally?

This was intentional, thinking that it would refer to both application frameworks and servers, but it makes sense that it sounds clearer with "applications" there, I just added it here! 🤓

**Review by aanchlia — APPROVED** [review]

**Pull request merged**
