### PR TITLE
Add basic healthcheck operation to example Dockerfiles

### PR DESCRIPTION
**Pull request by nikstuckenbrock**
Fixes issue #5037.

### CODE REVIEW

**Review by iudeen — COMMENTED** [review]
Can you also add what the user has to add in the route? By default localhost/ would result in 404 NOTFOUND. 

Also, we should mention if bind port is changed, that port has to be given accordingly.

**Comment by nikstuckenbrock** [comment]
Hey @iudeen,

thanks for the feedback.

> Can you also add what the user has to add in the route? By default localhost/ would result in 404 NOTFOUND.

I've chosen the root route on purpose because every api needs one. I don't think it's a problem that the endpoint will result in a 404. The docker `HEALTHCHECK` command will only check the process result status of curl, which in case of a valid response, is 0, so the container is considered healthy.

> Also, we should mention if bind port is changed, that port has to be given accordingly.

Yes, but the example is build using port 80. Maybe I should just include the port in the URL so it's more intuitive?

**Comment by iudeen** [comment]
> Yes, but the example is build using port 80. Maybe I should just include the port in the URL so it's more intuitive?

Yes! and may be a comment or small note in the doc about it.

**Comment by nikstuckenbrock** [comment]
Hey @iudeen,

I've provided a new version. Is that what you had in mind?

**Review by iudeen — APPROVED** [review]

**Review by ComicShrimp — APPROVED** [review]

**Comment by tiangolo** [comment]
Thanks @nikstuckenbrock! 🤓 

The consideration of what it means to be "healthy" would be quite dependent on the actual app, it could require a bunch of extra docs explaining all that... and there are also many other possible ideas or options that could be thought of as best practices, and it would not be feasible to include them all, or link to them all, also because it depends a lot on the specific team, etc.

So, for now, I'll pass on this one, but thanks for the effort! ☕

**Pull request closed without merging**
