### PR TITLE
🌐 Add German translation for `docs/de/docs/reference/responses.md`

### PR DESCRIPTION
**Pull request by nilslindemann**
← `reference/response.md` (#10824)
→ `reference/middleware.md` (#10837)

[German translation progress](https://github.com/tiangolo/fastapi/discussions/10582)

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit c660f8bf6ac67bacb457a95906e3afc04e17472b at: https://7cddde53.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 321730685a01b248daf04fb7b856c961d28073b3 at: https://42263f2d.fastapitiangolo.pages.dev

**Review by dpinezich — APPROVED** [review]
Well done 👍

**Comment by alejsdev** [comment]
Thank you! @nilslindemann  🐱✌️ 

And thanks for the review @dpinezich 🚀

**Comment by nilslindemann** [comment]
Danke sehr!

**Pull request merged**
