### PR TITLE
📝 Update example validation error from Pydantic v1 to match Pydantic v2 in `docs/en/docs/tutorial/path-params.md`

### PR DESCRIPTION
**Pull request by giuliowaitforitdavide**
After testing the tutorial for the first time, I noticed that the error message is different and maybe changed during the years

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit d509e8d37897b3c78fe202d86409645dcbd5967d at: https://73d61a27.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit df84147d667a96769e4e8f73ce06718bc035de23 at: https://71c84e08.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 7ef9166f335bc089e4d15d56a9d1053d50be87f8 at: https://a253c794.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 43a98ef834114fd9ea76169dd1f662d0fd0b1cd5 at: https://58a365f0.fastapitiangolo.pages.dev

**Review by Kludex — APPROVED** [review]

**Comment by tiangolo** [comment]
Cool, thank you @giuliowaitforitdavide! 🤓

**Pull request merged**
