### PR TITLE
⬆️ Allow Starlette 0.38.x, update the pin to `>=0.37.2,<0.39.0`

### PR DESCRIPTION
**Pull request by musicinmybrain**
I ran the tests (with Starlette 0.38.1) and did not observe any regressions.

https://github.com/encode/starlette/releases/tag/0.38.0

https://github.com/encode/starlette/releases/tag/0.38.1

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit a03ad2aa8bc9bc974ebf340146bf8d9a8afc0dbb at: https://c05c2fad.fastapitiangolo.pages.dev

**Comment by voltagex** [comment]
Any chance this can make it into a patch release? https://github.com/encode/starlette/releases/tag/0.38.2 will silence an annoying Snyk alert that isn't mentioned in the changelog (see https://github.com/encode/starlette/discussions/2653)

**Comment by Kludex** [comment]
> Any chance this can make it into a patch release? [encode/starlette@`0.38.2` (release)](https://github.com/encode/starlette/releases/tag/0.38.2) will silence an annoying Snyk alert that isn't mentioned in the changelog (see [encode/starlette#2653](https://github.com/encode/starlette/discussions/2653))

Wouldn't Snyk continue to complain anyway? 🤔 Or was it because Starlette removed the pin of anyio on the test requirements?

**Comment by Kludex** [comment]
> I ran the tests (with Starlette 0.38.1) and did not observe any regressions.

I didn't add anything that would break FastAPI on 0.38.0 as well, FYI.

**Comment by voltagex** [comment]
> > Any chance this can make it into a patch release? [encode/starlette@`0.38.2` (release)](https://github.com/encode/starlette/releases/tag/0.38.2) will silence an annoying Snyk alert that isn't mentioned in the changelog (see [encode/starlette#2653](https://github.com/encode/starlette/discussions/2653))
> 
> Wouldn't Snyk continue to complain anyway? 🤔 Or was it because Starlette removed the pin of anyio on the test requirements?

You know, now I'm not sure. I guess I'll find out?

**Review by Kludex — APPROVED** [review]

**Comment by jarey** [comment]
Could this be included in 0.112.1?

**Comment by Jaza** [comment]
+1

0.38.0 included https://github.com/encode/starlette/pull/2583 , which is a (non-critical but niggling) issue that's still currently affecting my apps running fastapi / starlette.

**Comment by tiangolo** [comment]
Great, thank you @musicinmybrain and @Kludex! This will be available in FastAPI `0.112.1`, released in the next hours. :rocket:

**Pull request merged**
