### PR TITLE
📝 Fix typo in `docs/es/docs/async.md`

### PR DESCRIPTION
**Pull request by fabianfalon**
Fix minor typo errors in the 'async' esp documentation

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 4d029893557aa1b976d24b44e5006cfec972b893 at: https://110afc3b.fastapitiangolo.pages.dev

**Review by JavierSanchezCastro — APPROVED** [review]

**Review by tiangolo — CHANGES_REQUESTED** [review]
Thanks! I wanna keep the word `libraries`, because in Spanish "librería" is inaccurate, and "biblioteca", which is more accurate, is not widely used, so, given it is a technical term, I prefer to keep the English version.

Please, remove those changes and leave only the "Coges", and I'll take it. Thanks! :coffee:

**Comment by fabianfalon** [comment]
@tiangolo  Perfect, reverted the changes and pushed.
Thank you.

**Comment by tiangolo** [comment]
📝 Docs preview for commit 9e3133f6e160ec09a66d9346efa6b51ccd256091 at: https://9e76f17a.fastapitiangolo.pages.dev

**Comment by alejsdev** [comment]
Good catch, thanks! :nerd_face: :100: @fabianfalon

**Pull request merged**
