### PR TITLE
🌐 Add Korean translation for `docs/ko/docs/advanced/additional-status-codes.md`

### PR DESCRIPTION
**Pull request by nahyunkeem**

### CODE REVIEW

**Comment by nahyunkeem** [comment]
~~Started translation of `docs/ko/docs/advanced/additional-status-codes.md`~~
Add Korean translation to `docs/ko/docs/advanced/additional-status-codes.md` https://github.com/fastapi/fastapi/pull/12622

**Comment by sodaMelon** [comment]
@nahyunkeem hi
this PR has too much files for review.
how about making another PR with only ``docs/ko/docs/advanced/additional-status-codes.md``?

**Comment by sodaMelon** [comment]
image
it still has problem.

this is a solution to solve it. (i write by korean)
안녕하세요! 이대로는 merge가 될 수없어서, 해결 방법을 하나 알려드립니다.
(★잘 모르시겟으면 discord sodam_012 로 친추 주세요~)

1. 일단 forked 해온 nahyunkeem 님의 [nahyunkeem의 fastapi](https://github.com/nahyunkeem/fastapi/tree/master)에 가서 '
master 브랜치를 synk fork 하겠습니다. (이러면 현재 원본 fastapi repository랑 코드가 똑같아집니다.)
image

2. git 도구를 이용해서 새로 브랜치를 따줍니다: 예 ```git checkout -b pr-12622``` -> ```git origin push pr_12622```
3. 새로 만든 브랜치에 번역한  파일 ```docs/ko/docs/advanced/additional-status-codes.md```를 알맞게 넣고, push 합니다. 
4. 이 PR에 연결하거나, 혹은 새로 PR을 만듭니다. 
5. (이렇게 하시면 다른 번역 파일처럼 File changed가 1개인 PR을 생성하실 수 있습니다.)

**Comment by alejsdev** [comment]
Hi @nahyunkeem, thanks for your interest in contributing to FastAPI, and thanks for your support! @sodaMelon 

You can create a new PR that includes only the changes related to the new translation. This PR has too many changes so I'll be closing it. Thanks for your understanding! :relaxed:

**Comment by alejsdev** [comment]
Hi @nahyunkeem, thanks for your interest in contributing to FastAPI, and thanks for your support! @sodaMelon :grinning: 

You can create a new PR that includes only the changes related to the new translation. This PR has too many changes so I'll be closing it. Thanks for your understanding! :raised_hands:

**Pull request closed without merging**
