### PR TITLE
fix: allows user to set example(s) value(s) when using Form and/or multiple Body parameters

### LINKED ISSUE #5249: How to have multiple str in body with an example for each of these str (while typing those value as string)
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from fastapi import FastAPI, Body
from pydantic import BaseModel

app = FastAPI()


@app.post("/one_body")
def one_body(
    sentence_1: str = Body(
        default=None,
        example="This should works fine",
    ),
):
    return "'I'm one_body"


@app.post("/only_body")
def only_body(
    sentence_1: str = Body(
        default=None,
        example="some example value (1)",
    ),
    sentence_2: str = Body(
        default=None,
        example="some example value (2)",
    ),
):
    return "'I'm only_body"


class Sentence1(BaseModel):
    sentence_2: str

    class Config:
        schema_extra = {
            "example": "This is the first sentence that I have hard-coded",
        }

class Sentence2(BaseModel):
    sentence_2: str

    class Config:
        schema_extra = {
            "example": "This is the second sentence that I have hard-coded",
        }


@app.post("/with_base_model")
def with_base_model(
    sentence_1: Sentence1 = Body(
        default=None,
        example=Sentence1.Config.schema_extra["example"],
    ),
    sentence_2: Sentence2 = Body(
        default=None,
        # example=Sentence2.Config.schema_extra["example"], # NOTE: volontarely comment this line to show that it changes nothing
    ),
):
    return "'I'm only_body"
```

### Description

I'm trying to find a way to :
- create a route with two str params required in the body
- those params being typed as `str`
- providing an example value for those two `str`

But seems that if we provide two value in the body we must use `BaseModel` ([cf](https://github.com/tiangolo/fastapi/pull/1267#issuecomment-762557261)) to describe it example value, however if we do that the param will no longer be typed as an `str` but as an `object`.

How can I create a route requiring two str in the body while providing an example for those two str and still have those values typed as `str`?

In the example code I create three routes :

1. `/one_body` to show that we can provide an example when there is only one value in the body
2. `/only_body` to show that when provide two values in the body we can no longer provide an example
3. `/with_base_model` to show that when use `BaseModel` to provide an example, the value is no longer typed as an `str`

<details>
<summary>/openapi.json</summary>

```json
{
  "openapi": "3.0.2",
  "info": {
    "title": "FastAPI",
    "version": "0.1.0"
  },
  "paths": {
    "/one_body": {
      "post": {
        "summary": "One Body",
        "operationId": "one_body_one_body_post",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "title": "Sentence 1",
                "type": "string"
              },
              "example": "This should works fine"
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    },
    "/only_body": {
      "post": {
        "summary": "Only Body",
        "operationId": "only_body_only_body_post",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Body_only_body_only_body_post"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    },
    "/with_base_model": {
      "post": {
        "summary": "With Base Model",
        "operationId": "with_base_model_with_base_model_post",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Body_with_base_model_with_base_model_post"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {
                  
                }
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Body_only_body_only_body_post": {
        "title": "Body_only_body_only_body_post",
        "type": "object",
        "properties": {
          "sentence_1": {
            "title": "Sentence 1",
            "type": "string"
          },
          "sentence_2": {
            "title": "Sentence 2",
            "type": "string"
          }
        }
      },
      "Body_with_base_model_with_base_model_post": {
        "title": "Body_with_base_model_with_base_model_post",
        "type": "object",
        "properties": {
          "sentence_1": {
            "$ref": "#/components/schemas/Sentence1"
          },
          "sentence_2": {
            "$ref": "#/components/schemas/Sentence2"
          }
        }
      },
      "HTTPValidationError": {
        "title": "HTTPValidationError",
        "type": "object",
        "properties": {
          "detail": {
            "title": "Detail",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ValidationError"
            }
          }
        }
      },
      "Sentence1": {
        "title": "Sentence1",
        "required": [
          "sentence_2"
        ],
        "type": "object",
        "properties": {
          "sentence_2": {
            "title": "Sentence 2",
            "type": "string"
          }
        },
        "example": "This is the first sentence that I have hard-coded"
      },
      "Sentence2": {
        "title": "Sentence2",
        "required": [
          "sentence_2"
        ],
        "type": "object",
        "properties": {
          "sentence_2": {
            "title": "Sentence 2",
            "type": "string"
          }
        },
        "example": "This is the second sentence that I have hard-coded"
      },
      "ValidationError": {
        "title": "ValidationError",
        "required": [
          "loc",
          "msg",
          "type"
        ],
        "type": "object",
        "properties": {
          "loc": {
            "title": "Location",
            "type": "array",
            "items": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "integer"
                }
              ]
            }
          },
          "msg": {
            "title": "Message",
            "type": "string"
          },
          "type": {
            "title": "Error Type",
            "type": "string"
          }
        }
      }
    }
  }
}
```

</details>

### Operating System

Linux

### Operating System Details

_No response_

### FastAPI Version

0.79.0

### Python Version

Python 3.8.10

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Thytu**
This would allow the user to use and display `example(s)` value(s) when using `Form` (or multiple `Body` param).

**Explication**: `f.field_info.extra` was empty, thus when calling `create_response_field` the return value also has en empty `extra` field. 

**Note** : I know this is not a perfect fix as it does not handle every cases (and is hard-coded) but this would fix the issue while giving time for a developing a better fix to come latter.

**Better fix for latter** : When creating the `field_info` in `get_param_field`, we should determine which value to put into the `extra` field.

Closes #5249

### CODE REVIEW

**Comment by Thytu** [comment]
@JarroVGIT is the test coverage KO?

It's running since yesterday 🫤

**Comment by JarroVGIT** [comment]
That is weird, I am not the maintainer of this project (@tiangolo) is, maybe it’s just stuck and a nonsense commit would force it to restart?

**Comment by Thytu** [comment]
> To be honest, that is up to @tiangolo . He is the sole maintainer on this project. I don't mean this with any disrespect, but what is merged (and when) and what is not is basically something he alone decides without any community interference. It's a great project (hence my active contributions on helping people out with it), but the governance around it is currently a bottleneck I am afraid.

Thanks for your honest response (and for your help for this PR).
Hope this could be released soon, we're currently using my fork in order to provide example values 😬

🤞

**Review by BilalAlpaslan — APPROVED** [review]

**Comment by Thytu** [comment]
Thanks @BilalAlpaslan 🥲

**Comment by Thytu** [comment]
@tiangolo any chance for that PR to be merged? 🙂

**Comment by Thytu** [comment]
Legend says that one day, this PR will be either merger or closed, but no one know which and when 🫠

**Comment by Thytu** [comment]
I'm stubborn (and working on a fork since Aug 2022 🤡)

**Comment by Thytu** [comment]
Cleaning my PR history (take WAY too long to be merged...)

**Comment by JarroVGIT** [comment]
@tiangolo this is a great example on why there needs to be a better format for managing this project. You ask for help specifically on this project, but if you don’t even comment on active code contributions, people will move away.

**Comment by tiangolo** [comment]
Thanks for the input @JarroVGIT, I'm trying to work on the things that can make the biggest impact, switching back and forth in reviewing things and the others that are already planned. In this particular case, I have been wanting to support Pydantic models for Form, Query, and others, but I haven't been able to see how that would work and if it would be feasible or not, so I didn't (and still don't) know if this would be the approach to go or not, so I didn't comment before, as I don't really have something valuable to comment yet.

**Comment by Thytu** [comment]
@tiangolo I have no doubt that you're are prioritizing the PR / Issues than can produce the biggest impact, but @JarroVGIT's point is still valid.

You should consider changing the current format of management for this project for one than could result in a faster iteration rate and thus biggest impact.

The current working do results in people moving away and in our case considering switching FastAPI for something else.
FastAPI is still the most pleasant way to write API in python, you did a great job on that, but those little bug/issues results in a non-"prod proof" package.

I hope you'll consider those elements, either way well done for the work accomplished.

**Pull request closed without merging**
