### PR TITLE
🌐 Update Chinese translation for `/docs/advanced/security/http-basic-auth.md`

### PR DESCRIPTION
**Pull request by nick-cjyx9**

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 07b7ae55a6dc1c722a75e298af878cf837d8d1b4 at: https://322ffc4b.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit f3e7bbfab95ab4e9daaa2c1132d8b455ce2047e1 at: https://699878b5.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 1d46f311a71825aafe3cc51770ccd460eaa5975e at: https://1ae48ed3.fastapitiangolo.pages.dev

**Review by mahone3297 — APPROVED** [review]

**Comment by alejsdev** [comment]
Thanks for your contribution! @nick-cjyx9  :smile: 

And thanks for the reviews @mahone3297 :rocket:

**Pull request merged**
