### PR TITLE
✏️ Update links in `docs/en/docs/async.md` and `docs/zh/docs/async.md` to make them relative

### PR DESCRIPTION
**Pull request by hasnatsajid**
Updated async.md for a url fix 🐛

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 251f852dcff664a716704d808f0a624fc2e4f8e6 at: https://a5157a7b.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit ad386f1103d76ac53481c70f3e315a154d856d31 at: https://2a6dad0f.fastapitiangolo.pages.dev

**Comment by nilslindemann** [comment]
The fixes are correct, but

* the resulting URLs are absolute, the [doc server](https://fastapi.tiangolo.com/contributing/#docs-for-tests) complains about that in its console log. To make them relative, replace `/tutorial/dependencies/` with `tutorial/dependencies/index.md` and `/tutorial/dependencies/sub-dependencies/` with `tutorial/dependencies/sub-dependencies.md`
* the links can also be fixed in the documents `docs/em/docs/async.md` and `docs/zh/docs/async.md`.

**Comment by hasnatsajid** [comment]
Ok fren. Let me check

**Comment by tiangolo** [comment]
📝 Docs preview for commit 0f6f145b655d2ea7b78eb484ebba4514950f1aa4 at: https://0dbdf476.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit dfe1e39984b48696796c388af87355eaaa3bd57f at: https://059cfd30.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
Thanks @hasnatsajid! 🚀 

And thanks for the help @nilslindemann! 🙇

**Pull request merged**
