### PR TITLE
🌐 Add Japanese translation for External Links

### PR DESCRIPTION
**Pull request by tokusumi**
This PR translates the external-links.md to Japanese.

### CODE REVIEW

**Comment by amazyra** [comment]
@tokusumi If you'd like, I'm going to do a review for this PR.

**Comment by tokusumi** [comment]
@amazyra
Sure. Review is really welcome. However, this section is not high priority. It is better to review other PR at first to save your time.

**Comment by komtaki** [comment]
LGTM 👍

**Review by komtaki — APPROVED** [review]
LGTM 👍

**Review by delhi09 — APPROVED** [review]
LGTM

**Comment by tiangolo** [comment]
Awesome! Thanks @tokusumi :rocket: :coffee: 

And thanks @komtaki and @delhi09 for the reviews :bow:

**Pull request merged**
