### PR TITLE
🌐 Add Turkish translation for `docs/tr/docs/advanced/testing-websockets.md`

### PR DESCRIPTION
**Pull request by hasansezertasan**
🌐 Add Turkish translation for `docs/tr/docs/advanced/testing-websockets.md`

[Original File](https://github.com/tiangolo/fastapi/blob/master/docs/en/docs/advanced/testing-websockets.md)

Discussion: #9193

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit f1c6a39a33133561d10bd2ff1ead852e7e4c73ef at: https://3a69b610.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit adfb52828c4788f2c3b70cfe09ad9582968b2932 at: https://f799dbfc.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit dbbf41fd29f5189aef1c9b3fd3094eec2762e5ba at: https://4b617e81.fastapitiangolo.pages.dev

**Review by OzgunCaglarArslan — APPROVED** [review]

**Comment by tiangolo** [comment]
📝 Docs preview for commit 2160703eb6891d5fea3ac54efbcba43827e22d51 at: https://c4d7692e.fastapitiangolo.pages.dev

**Review by OzgunCaglarArslan — APPROVED** [review]

**Comment by alejsdev** [comment]
Thanks for the help :partying_face: @hasansezertasan @OzgunCaglarArslan

**Pull request merged**
