### PR TITLE
🌐 Add Turkish translation for `docs/tr/docs/external-links.md`

### PR DESCRIPTION
**Pull request by hasansezertasan**
🌐 Add Turkish translation for `docs/tr/docs/external-links.md`

Discussion: #9193

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 4af1bba983be74fdf34b17fded68cad5b8b3afc1 at: https://00840d32.fastapitiangolo.pages.dev

**Review by alperiox — APPROVED** [review]

**Review by SametEmin — APPROVED** [review]
LGTM

**Review by SametEmin — APPROVED** [review]
LGTM

**Review by OzgunCaglarArslan — APPROVED** [review]
LGTM

**Review by aprilcoskun — APPROVED** [review]
LGTM as a native speaker.

**Review by BilalAlpaslan — APPROVED** [review]

**Comment by tiangolo** [comment]
📝 Docs preview for commit a5e1db2276663a1d76155b2e2044cd982ea5cb77 at: https://ff674a45.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 8886b32afab7c048fcc538a273a496624a9a4cd3 at: https://b2b87a22.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit fa8899d4ef688b93520f69f2f31af422c12e57bc at: https://c6548f30.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit a3c690192f860e08093872239ba239550af773bb at: https://76bc049f.fastapitiangolo.pages.dev

**Pull request merged**
