### PR TITLE
📝 Add blog for FastAPI & Supabase

### PR DESCRIPTION
**Pull request by theinfosecguy**
Added blog for Supabase & FastAPI Integration.

Link to blog: https://blog.theinfosecguy.xyz/building-a-crud-api-with-fastapi-and-supabase-a-step-by-step-guide

### CODE REVIEW

**Review by peidrao — APPROVED** [review]

**Review by Ryandaydev — APPROVED** [review]
Interesting article.

**Review by Kludex — APPROVED** [review]

**Comment by tiangolo** [comment]
Cool! Can you move it to the top of the list, please?

**Comment by theinfosecguy** [comment]
> Cool! Can you move it to the top of the list, please?

@tiangolo It's done!

**Comment by tiangolo** [comment]
📝 Docs preview for commit 44d19c5a0065871416d8b56efb58a6625b80aab0 at: https://d202abb1.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
Great, thanks @theinfosecguy! 🚀

**Pull request merged**
