### PR TITLE
🐛 Fix parameterless `Depends()` with generics

### PR DESCRIPTION
**Pull request by nzig**
Previously, using parameterless `Depends()` in a generic context would bind the dependency to the first encountered concrete type.

Fixes #9450.

### CODE REVIEW

**Review by odiseo0 — APPROVED** [review]
Nicely done, very clean

**Review by yezz123 — APPROVED** [review]

**Review by Ryandaydev — APPROVED** [review]
Tests pass.

**Review by Jaza — APPROVED** [review]
Nice thorough tests, well done

**Comment by PinkOatmeal** [comment]
Looking forward to this fix. I want to use code from #9450 as example to implement injection of contollers in my project

**Comment by 9en9i** [comment]
Hi @nzig, I've been watching this pr all month. And I'm already beginning to think that if it will be put in, it will not happen very soon. But it's a very cool fix, which will allow to write less monotonous code for your classes. Maybe it's possible to do something to get this pr accepted faster?

**Comment by nzig** [comment]
@9en9i That's up to @tiangolo. He's the only one that can merge PRs.

**Comment by 9en9i** [comment]
@tiangolo hi, is it possible that this bug fix request will ever be accepted?

**Comment by 9en9i** [comment]
@Kludex @JarroVGIT @jgould22 @ycd Perhaps one of you can somehow contribute to the promotion of this pull request? This request fixes a feature that was added a little less than a year ago, and it would be nice to get full functionality.

**Comment by FieryDruid** [comment]
@tiangolo hi! This is a very cool feature that makes the code more readable and clean. Should we hope for its will be accepted?

**Review by Kludex — APPROVED** [review]

**Comment by tiangolo** [comment]
Thanks @nzig! :rocket: 

And thanks everyone for the discussion. :coffee: 

This will be available in the next hours in FastAPI 0.110.1 :tada:

**Pull request merged**
