### PR TITLE
🌐 Add Chinese translation for `docs/zh/docs/tutorial/dependencies/classes-as-dependencies.md`

### PR DESCRIPTION
**Pull request by Zssaer**
Translates docs/zh/docs/tutorial/dependencies/classes-as-dependencies.md and add deploy menu in Chinese.
related: https://github.com/tiangolo/fastapi/issues/1228

### CODE REVIEW

**Review by 1320555911 — APPROVED** [review]

**Comment by Jedore** [comment]
@Zssaer I reviewed your changes and made some optimization. How can I push optimization to your PR ?

**Review by Jedore — CHANGES_REQUESTED** [review]
I reviewed your changes and made some optimization. Can I push them ?

**Comment by Zssaer** [comment]
> I reviewed your changes and made some optimization. Can I push them ?

Sure

**Comment by Jedore** [comment]
> > I reviewed your changes and made some optimization. Can I push them ?
> 
> Sure

But it seems  I have no permission:
```
$ git push zssaer head:zssaer-translation-classes-as-dependencies
ERROR: Permission to Zssaer/fastapi.git denied to Jedore.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Am I something wrong ? Or how can I push changes to this PR? Thanks. @tiangolo @Zssaer

**Comment by ASpathfinder** [comment]
> > > I reviewed your changes and made some optimization. Can I push them ?
> > 
> > 
> > Sure
> 
> But it seems I have no permission:
> 
> ```
> $ git push zssaer head:zssaer-translation-classes-as-dependencies
> ERROR: Permission to Zssaer/fastapi.git denied to Jedore.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> ```
> 
> Am I something wrong ? Or how can I push changes to this PR? Or can I only comment some lines in per review. Because I reviewed and changed much lines. Thanks. @tiangolo @Zssaer

Looks like you don't have permission to do that.  See [https://docs.github.com/cn/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork](url)

**Comment by Zssaer** [comment]
> > > I reviewed your changes and made some optimization. Can I push them ?
> > 
> > 
> > Sure
> 
> But it seems I have no permission:
> 
> ```
> $ git push zssaer head:zssaer-translation-classes-as-dependencies
> ERROR: Permission to Zssaer/fastapi.git denied to Jedore.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> ```
> 
> Am I something wrong ? Or how can I push changes to this PR? Or can I only comment some lines in per review. Because I reviewed and changed much lines. Thanks. @tiangolo @Zssaer

Only the upstream repository maintainers can direct change it.
Try to create pull request.

**Comment by Jedore** [comment]
@Zssaer  Yeah, starting a review and making a suggested change is a normal way, you can agree or reject them.

**Comment by Jedore** [comment]
> 



> > @Zssaer Yeah, starting a review and making a suggested change is a normal way, you can agree or reject them.
> 
> Jedore，你目前还是否有意愿进行提交一些修改？如果你嫌一段一段Request changes麻烦的话，我的意思是 你可以将这个PR的Branch给Fork下来，然后再进行PR给这个Branch。

之前没有对你的branch推送的权限，所以我已经将我所有的修改建议在上面以review的形式提交了，需要你去按需选择接受或拒绝就可以了。目前我没有其他的修改建议了，所以也不用再提PR给你的branch了 :joy:

**Comment by Zssaer** [comment]
> > 
> 
> > > @Zssaer Yeah, starting a review and making a suggested change is a normal way, you can agree or reject them.
> > 
> > 
> > Jedore，你目前还是否有意愿进行提交一些修改？如果你嫌一段一段Request changes麻烦的话，我的意思是 你可以将这个PR的Branch给Fork下来，然后再进行PR给这个Branch。
> 
> 之前没有对你的branch推送的权限，所以我已经将我所有的修改建议在上面以review的形式提交了，需要你去按需选择接受或拒绝就可以了。目前我没有其他的修改建议了，所以也不用再提PR给你的branch了 😂

可是我并没有收到你的相关review的提交

**Review by Jedore — CHANGES_REQUESTED** [review]

**Comment by Jedore** [comment]
@Zssaer 现在可以看到了吗？第一次 review， 打开review， 忘记提交review了

**Review by Jedore — APPROVED** [review]

**Pull request merged**
