### PR TITLE
📝 Add warning about lifespan functions and backwards compatibility with events

### PR DESCRIPTION
**Pull request by jacob-indigo**
Backwards compatibility with `startup`/`shutdown` events in implemented in Starlette with a default lifespan function that calls the registered event handlers. If there is a user-provided lifespan function, those event handlers will no longer be called.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit a117d0e0106a8baa3a7ce010293e5f318d59068c at: https://a824f295.fastapitiangolo.pages.dev

**Comment by jacob-indigo** [comment]
@tiangolo This is my first time contributing to FastAPI. Is there anything else I need to do for this PR?

**Comment by tiangolo** [comment]
📝 Docs preview for commit df51abb1287a0c1fac5bf8bbc023da312bd03e8b at: https://e35849a0.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 19db41c2426352c106736e25d5df93c54a822b96 at: https://1d141478.fastapitiangolo.pages.dev

**Review by alejsdev — APPROVED** [review]

**Comment by tiangolo** [comment]
Good idea, thank you for your contribution @jacob-indigo! 🍰 ☕

**Pull request merged**
