### PR TITLE
📝 Review and rewording of `en/docs/contributing.md`

### PR DESCRIPTION
**Pull request by nilslindemann**
* Explain more detailed how to translate links (`#hash-parts`!). Explain a few other things, like not to translate `!!! note`, etc.
* Remove some redundacies and restructure some headings.
* Improve venv setup instructions.

This PR does not break markdown files linking to it.

#10487 is a translation of this.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit e56d9b2d8660677166a637da721598231fdbcf33 at: https://2bc59bfa.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit ce8df22c6c76478982b436785070f7f2335c7735 at: https://a744d637.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 9fcacee65886f6fa56a0384cca5d8db28e36a693 at: https://2582cf28.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit c6f38a011d1e2ab36c94d68728e96bcecfa3111d at: https://e6f04daa.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 2dfc8cde0234bff6cb5dae00d0e31130cb74c296 at: https://3ca71f01.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 3f54fb9c3871649efb871e2456a710ba5cab7192 at: https://4c71ea3d.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 416aac22dcb2eb2cd3dc800e37234ebacf3f8144 at: https://caf77f6e.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 8d332acc665e70c3227deb4d1c1d79e37bfdc922 at: https://f445fcb7.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 86b73e0b7603e5f28e3bb3f56cc6906d90efe13e at: https://7dc8f815.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit b8f5057ff7a911d005ad42ae4f87699820a668c9 at: https://28622332.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit b7a9dd59b3460797543aba12527c8e5db313b68e at: https://1aac5feb.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit 6aba7988d094ff4b90c74b596abd1cc9bbf6a944 at: https://710b5b26.fastapitiangolo.pages.dev

**Comment by nilslindemann** [comment]
Thank you @tiangolo. Was away a few days, checking the backlog now XD

**Comment by tiangolo** [comment]
Thanks for all your help @nilslindemann! Would love to chat with you. 😁

I wrote to your email (the one that appears on GitHub), but if there's any other method feel free to write me an email or anything! 🤓

**Comment by nilslindemann** [comment]
Thanks, @tiangolo, I come back to you.

**Pull request merged**
