### PR TITLE
🌐 Add Vietnamese translations for `docs/vi/docs/tutorial/first-steps.md` and `docs/vi/docs/tutorial/index.md`

### PR DESCRIPTION
**Pull request by magiskboy**

### CODE REVIEW

**Review by HealerNguyen — APPROVED** [review]
GOOD

**Comment by tiangolo** [comment]
📝 Docs preview for commit 1d03ddbd852f73247fe58125034dfc336df7952b at: https://97c88042.fastapitiangolo.pages.dev

**Review by phamquanganh31101998 — APPROVED** [review]

**Comment by magiskboy** [comment]
@tiangolo please review this pr

**Comment by tiangolo** [comment]
Great, thanks @magiskboy! 🚀 

And thanks for the reviews @HealerNguyen, @phamquanganh31101998 ☕

**Pull request merged**
