### PR TITLE
🌐 Update Russian translation for `fastapi-people.md`.

### PR DESCRIPTION
**Pull request by NiKuma0**
This "Ку" has not stood the test of time, let's face it. Maybe just "хай" or "привет" would be better.

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 601ab034c3fc103089359cf0c21ab40db01cba42 at: https://2c84cd5f.fastapitiangolo.pages.dev

**Comment by sshevlyagin** [comment]
I'm a russian speaker, this looks a-ok.

**Review by frwl404 — APPROVED** [review]
Confirm - nobody uses `Ку`. `Хай` is nice!

**Comment by alejsdev** [comment]
Thanks @NiKuma0 🤓 

And thanks for the reviews @achivkun and @sshevlyagin 👏

**Pull request merged**
