### PR TITLE
⬆️ Upgrade Starlette to `>=0.29.0,<0.33.0`, update docs and usage of templates with new Starlette arguments

### PR DESCRIPTION
**Pull request by tiangolo**
⬆️ Upgrade Starlette to `>=0.29.0,<0.33.0`, update docs and usage of templates with new Starlette arguments

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit bbc6a5ffc08156982d113d0a46c4ea8e31f601ee at: https://7944a948.fastapitiangolo.pages.dev

**Comment by tiangolo** [comment]
📝 Docs preview for commit c8a5cd982ebcb607df250d1325043a30c37b2d0c at: https://a0b453f6.fastapitiangolo.pages.dev

**Comment by Kludex** [comment]
❤️ 👍

**Comment by CFelipezapata** [comment]
Hey @tiangolo I'd like to point out this issue, I don't really know where to post it, I left a comment on the PR for the previous release, but it's also happening on this version of fastapi.

https://github.com/tiangolo/fastapi/pull/9636#issuecomment-1869813473

**Pull request merged**
