### PR TITLE
🐛 Fix support for prefix on APIRouter WebSockets

### LINKED ISSUE #2639: prefix parameter in APIRouter does not work for websocket
```Python
# main.py
from fastapi import FastAPI
import myroute

import myroute
app = FastAPI()
app.include_router(myroute.router)

@app.get("/")
async def root():
    return {"message": "hello world!!"}
```

```Python
# myroute.py
from fastapi import APIRouter

router = APIRouter(prefix="/prefix")

# you'd expect ws://localhost:800/prefix/ws to work but only ws://localhost:800/ws connects
@router.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):

    await websocket.accept()
    await websocket.send_text("hi")
    await websocket.close()

# this works fine if you go to http://localhost:8000/prefix
@router.get("/")
def read_root():
    return {"Hello": "World"}
```

### Description

Hi,

So with APIRouter(), the prefix path does not seem to be prepended to the websocket router path. 
Not sure if its by design but if it is I feel like its quite misleading

### Environment

* OS: macOS Catalina 10.15.4
* FastAPI Version: 0.63.0

* Python version: 3.8.2

### PR DESCRIPTION
**Pull request by Kludex**
Related to #2639

### CODE REVIEW

**Review by aviramha — APPROVED** [review]

**Comment by Sh4pe** [comment]
Any chance on getting this PR merged?

**Review by jpribyl — APPROVED** [review]
Looks good to me, would love to see this merged soon!

**Comment by gtors** [comment]
Is there any reason why this PR is still not merged?

**Review by RuellePaul — APPROVED** [review]

**Comment by MaratBR** [comment]
Hi! Will this PR get merged any time soon? It's been more than a year

@tiangolo

**Review by yezz123 — APPROVED** [review]

**Comment by tkieft** [comment]
@tiangolo Please merge this!

**Review by BilalAlpaslan — APPROVED** [review]

**Comment by mohamed-aziz** [comment]
Why is this not merged yet ? Are you guys afraid it will deprecate existing code ?

**Comment by tiangolo** [comment]
Awesome, thanks @Kludex as always! :bow: :cake:

Thanks everyone for your input. :cookie: 

This will be available in FastAPI version `0.75.2` in a couple of hours.

**Comment by genagurbanguliyev** [comment]
Try this [solved](https://github.com/tiangolo/fastapi/pull/3280#issuecomment-1945519007)

**Pull request merged**
