### PR TITLE
✏ Tweak wording to clarify `docs/en/docs/project-generation.md`

### PR DESCRIPTION
**Pull request by chandra-deb**
"You can use a project generator to ...... database and first API endpoints already done for you."  - In this sentence, the word "first" does not fit the context. It should be "some API".

### CODE REVIEW

**Review by fabioueno — APPROVED** [review]
LGTM!

**Comment by chandra-deb** [comment]
Sorry! I unknowingly closed my pull request. @fabioueno

**Review by fabioueno — APPROVED** [review]
No problem, @chandra-deb. 😉

**Review by Ryandaydev — APPROVED** [review]
Tests pass. (Not surprising, since it's just some text changing but...)

**Comment by tiangolo** [comment]
Sounds good, thanks @chandra-deb! :coffee:

**Pull request merged**
