### PR TITLE
✨ Add FastAPI CLI, the new `fastapi` command

### PR DESCRIPTION
**Pull request by tiangolo**
✨ Add FastAPI CLI, the new `fastapi` command

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit c98c1513ec5cde506380890182f536ce544dcd15 at: https://a98e0cab.fastapitiangolo.pages.dev

**Comment by Olegt0rr** [comment]
Thanks for this great feature. 

It also would be nice to support module's `__main__.py` as well as `main.py`

**Comment by zoola969** [comment]
Why do we need it for production? Could you make it optional dependency?

**Comment by metakot** [comment]
Really, why, of all the things...

**Comment by parfeniukink** [comment]
> So now my servers will depend on some CLI packages? 🤔

I think you still available to run `pip install fastapi --no-deps` if this is an issue for you.
Probably, it depends on the package manager that you use, but anyway, I guess that `piptools`, `poetry` or `pipenv` allow you to achieve that, aren't they?

**Comment by rafalkrupinski** [comment]
@parfeniukink poetry doesn't, besides, I don't want to manage dependencies myself.

I'm migrating over to Litestar.

**Comment by parfeniukink** [comment]
> @parfeniukink poetry doesn't, besides, I don't want to manage dependencies myself.
> 
> I'm migrating over to Litestar, it has more than one maintainer.

Good choice I guess :)
I've heart that it is quite stable.

**Comment by limosin** [comment]
@tiangolo I understand fastapi cli is running uvicorn under the hood.
How can I modify the uvicorn configurations like `--loop` type and `--http`?

**Comment by Jaza** [comment]
@tiangolo a few comments:

- I'm a FastAPI fan, I've been using it for the main codebases that I work on at my full-time job for about 2 years, no plans for that to change anytime soon
- I know there has been criticism of the way the FastAPI project is run, but personally I don't have a problem as such with your ongoing BDFL role, it's your baby, you can keep holding all the keys to the castle if you want, the quality of FastAPI has in my opinion benefitted greatly from your oversight
- You can of course give priority to whatever you want, you can build whatever features you want, that's what open source is all about, if you have an itch to scratch then go for it

However:

- FastAPI is now quite a mature project with hundreds of contributors
- This is a fairly significant new feature
- You merged this PR less than an hour after you opened it
- Nobody had time to review it or to give any feedback whatsoever
- AFAICT there was no issue thread to discuss this, nor was there prior discussion anywhere else
- No mention of a CLI in the [roadmap](https://github.com/tiangolo/fastapi/issues/10370), or anywhere else that I'm aware of, AFAICT nobody had any heads-up about this
- Many of the comments, since this PR was merged, have been critical - some are critical of the feature itself, others are critical of the rationale and the process (or lack thereof) behind it

Personally I think it's a decent feature (and, on par with FastAPI's high standards, it appears to be thoroughly tested and clearly documented). It will probably help out FastAPI newcomers the most, with a friendlier getting-started experience. I don't need it urgently, not sure if I'll use it, I might give it a try. Anyway, what the feature is that you built, isn't the point here.

In future, could you at least leave a PR (for a non-critical new feature) open for a reasonable time, before merging it? I would suggest one week, to give people some time to review and comment.

And ideally, could you advise the community in advance, in a separate issue thread, and/or in the roadmap, of features that you plan to work on?

I'm not suggesting a radical overhaul of how the project is managed. I just think that a little bit more transparency, and a little bit more engagement, are not unreasonable expectations of the community, for a project that thousands of people now rely on. And I don't want to see people abandon FastAPI on account of these concerns (as some of the comments in this PR have suggested, and as I've seen suggested in a number of discussions elsewhere), I think it's a great project, and I'm saying all this in the hope that it helps rather than harms the project's future.

**Comment by tiangolo** [comment]
Thanks for the feedback @Jaza and everyone!

As having `fastapi` include by default the standard dependencies has been inconvenient to several people, I decided to make those standard dependencies an optional extra group `standard`.

So, to get the standard optional dependencies people now have to install it with:

```bash
pip install "fastapi[standard]"
```

**Note**: remember to use the quotes, depending on your terminal that might be required.

Having the optional extra, square brackets, quotes, is not as nice as just `fastapi`, it's extra things to have in mind, and extra things for newcomers to learn from the beginning. But anyway, it seems that having the default standard dependencies installed by default, and having to change the installed package to be `fastapi-slim` when people didn't want those standard dependencies instead was being too inconvenient for some people so I decided to switch back to have `fastapi` as the minimal/slim version and the standard extra dependencies in the group `standard`.

This is available in FastAPI version 0.112.0. :tada:

**Comment by bnbong** [comment]
Hello @tiangolo !

I'm a Korean student who loves FastAPI very much, and I've been using and studying FastAPI for years.

I am writing to introduce you to my project "[FastAPI-fastkit](https://pypi.org/project/FastAPI-fastkit/)," which I recently released as a dedicated supporter and developer within the FastAPI community.

## Project Background

I've been following the community's response to the `fastapi-cli` package introduced in FastAPI version 0.111.0. While some users expressed concerns about functionality of `fastapi-cli`, I was deeply inspired by your intention to lower the entry barrier for newcomers to the FastAPI framework.

Motivated by your philosophy, I developed a project that aims to provide a richer experience for FastAPI beginners while also being valuable for experienced developers.

## Introducing FastAPI-fastkit

FastAPI-fastkit is a comprehensive CLI tool inspired by the strengths of SpringBoot Initializer and django-admin CLI. It's designed to allow users to quickly generate and extend structured FastAPI projects with simple commands.

GitHub: https://github.com/bnbong/FastAPI-fastkit

## Key Features

- Creation of structured FastAPI projects with simple CLI commands
- Consistent project structure through modularized boilerplates
- Easy expandation : ex) attaching a new router endpoint at FastAPI project via cli
- Time reduce for configuring FastAPI projects

I started this project to contribute to your goal of "lowering the entry barrier to FastAPI" that you aimed to achieve with fastapi-cli, and I recently released version 1.0.0.

`FastAPI-fastkit` was just released today, it doesn't have that many features yet. However, the functions currently implemented have been developed with a focus on improving a lot of what I think is a barrier to entry for FastAPI based on the experiences of FastAPI around me and the response of the domestic community in my home country, Korea.

I would appreciate your thoughts or advice on this project that aims to benefit the FastAPI community. I would also be delighted to discuss how this project could further contribute to the FastAPI ecosystem.

Thank you for your time and consideration.

Best regards,

**Pull request merged**
