### PR TITLE
📝 Several docs improvements, tweaks, and clarifications

### PR DESCRIPTION
**Pull request by nilslindemann**
These are more ambiguous changes subtracted from #11389. Smaller PR, but look more closely. The first two commits are improvements in my opinion. I am unsure about the third commit.

### CODE REVIEW

**Comment by svlandeg** [comment]
Hi @nilslindemann, thanks for the PR! Especially appreciate you breaking out more ambiguous changes into its separate PR - these kind of considerations certainly help us push "less ambiguous" fixes through more easily 🙏 

I'll get this PR updated with the latest of `master` and will then review the changes.

**Review by svlandeg — COMMENTED** [review]
These edits mostly look good to me. Rewriting words like "it" to more clear references helps with readability for new users as well, so I'm all for it.

Also really appreciate you checking all links and rewriting them to better suited links where relevant 🙏

**Comment by tiangolo** [comment]
Awesome, thanks a lot for this @nilslindemann! :rocket: You rock! :guitar: 

And thanks a lot @svlandeg for the thorough review! :bow: 

I tweaked a couple of places and included Sofie's suggestions, this is now ready. Thank you! :cake:

**Comment by nilslindemann** [comment]
Thanks people, especially @svlandeg! I know this was quite some work. Well done!

**Pull request merged**
