### PR TITLE
Simplify and improve jsonable_encoder

### PR DESCRIPTION
**Pull request by blkst8**

### CODE REVIEW

**Comment by uriyyo** [comment]
Hi @MashhadiNima, 

I update this function in my PR #1753.
I used `collections.defaultdict` in order to replace usage of `dict.setdafault`.

**Comment by MashhadiNima** [comment]
Hi dear @uriyyo
Thank you for informing me of this.
My goal was to eliminate the second `for` loop. In the next commit, I will use `collections.defaultdict` to make the code cleaner.

**Comment by uriyyo** [comment]
> My goal was to eliminate the second `for` loop. In the next commit, I will use `collections.defaultdict` to make the code cleaner.

@MashhadiNima  What is the reason to eliminate the second `for` loop?
There can be a performance issue if we will use `tuple` concatenation in every `for` iteration.
```python
encoders_by_class_tuples[encoder] += (type_,)  # this line will create new tuple every time
```

Correct me if I missed smth.

**Comment by MashhadiNima** [comment]
I eliminate the second `for` loop for better performance.
`encoders_by_class_tuples[encoder] += (type_,)` create new tuple in every time but it's faster than cascades each list to tuple.
I tested it again and found cascading got bad performance.

**Comment by uriyyo** [comment]
@MashhadiNima My bad, just tested it out, you are totally right.

**Comment by tiangolo** [comment]
Clever! :nerd_face: 

And thanks for testing it @MashhadiNima and @uriyyo ! :zap: 

Thanks for your contribution @MashhadiNima ! :cake: :coffee:

**Pull request merged**
