### PR TITLE
🌐 Add Indonesian translation for `docs/id/features.md`

### PR DESCRIPTION
**Pull request by Alnyz**

### CODE REVIEW

**Comment by tiangolo** [comment]
📝 Docs preview for commit 167d9a722f556271f15e6a2b741ef5aec3fde095 at: https://79cb74e4.fastapitiangolo.pages.dev

**Comment by rizkyarlin** [comment]
I am sorry @tiangolothese these translations seems taken straight from the google translate without editing. 

A lot of mistranslation and some terms shouldn't be translated at all. Like "request", if translated to Bahasa Indonesia, it will just confuse the readers.

**Comment by tiangolo** [comment]
Thanks @rizkyarlin! 🤓 

@Alnyz, if you want, you could translate the page manually, not with Google Translate or similar. Otherwise, it would be better to close this one and let this doc available for others to translate. 🚀

**Comment by tiangolo** [comment]
As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR.

**Pull request closed without merging**
